### ISSUE TITLE
Fix dynamic fee rate for rollover and contract setup

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1021]
Note: This ticket should be tackled after rollover (https://github.com/itchysats/itchysats/pull/1014) merged.

We have several of these TODOs in code:

```
// TODO: Where should I get the fee rate from?
```

When producing events for contract setup / rollover we don't know the fee-rate in the `Cfd`. 
I don't think the `Cfd` should know about the current fee rate, but we will have to pass the fee rate to the "start" functions of the protocols (at the time of writing this issue: `start_contract_setup`, `start_rollover_taker` and `receive_rollover_proposal`).

Then the caller would have to know the fee rate, which would mean that we have to fetch the fee rate inside the rollover/setup actors.

In a later iteration we should give the repsonsibility of fee rate to a dedicated actor that can be queried for it (or even let an actor broadcast fee rate changes). I don't see this in scope of this ticket.

**Comment by thomaseizinger** [comment]
Descoped because not critical with rollover. Worst case the commit tx sits in mempool for a couple of days.

**Comment by luckysori** [comment]
This must have been fixed a while ago.
