### ISSUE TITLE
Reintroduce housekeeping module

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#1034]
After introduction of "started" events denoting start of one of the ephemeral actor protocols, we once again run the risk of the system being stuck with an unfinished cfd after a crash etc.
 In short, during startup, we should check whether any of the cfds end with `ContractSetupStarted`, `RolloverStarted`, `CollaborativeSettlementStarted` and append a corresponding "...Failed" event with adequate reason (e.g. "cleaned up during housekeeping phase").

Note: Failure cases that can be detected during application operation (e.g. #1035 ) ought to be fixed immediately by appending a new cfd event. In other words, housekeeping should be treated as a last-resort solution to recover from an unexpected crash.

**Comment by da-kami** [comment]
I ran into a related problem already here: #1048 

I would prefer not to bring back housekeeping as separate task, but see to handle all failed cases directly by adding another Event to the Cfd. Housekeeping appears to be an easy solution, but I feel it is always a tape solution. @thomaseizinger what do you think?

**Comment by klochowicz** [comment]
> I ran into a related problem already here: #1048
> 
> I would prefer not to bring back housekeeping as separate task, but see to handle all failed cases directly by adding another Event to the Cfd. Housekeeping appears to be an easy solution, but I feel it is always a tape solution. @thomaseizinger what do you think?

#1035 talks about handling cases directly - housekeeping seems needed after a crash? It seems to me that some part of the system needs to go through all the cfds and append an event if they didn't move correctly.

**Comment by da-kami** [comment]
I see how a crash might make this module necessary, but I think we should really design it as a last resort, i.e. it should only handle cases where the application crashes.

What I want to avoid is "misusing" the housekeeping for cleaning up too many things. That's what we did before by saying "we ignore this case because it will just be cleaned up when we restart". That lead to us depending on restarts which does not result in a good UX.

**Comment by klochowicz** [comment]
> 

I agree with you - that was my intention when I created this ticket, I will update the description to be more clear about it. Situations like #1035 should immediately be cleaned up by a following command, otherwise we might be waiting for a week to fix errors!

**Comment by thomaseizinger** [comment]
> Housekeeping appears to be an easy solution, but I feel it is always a tape solution. @thomaseizinger what do you think?

Agreed. Housekeeping will be necessary but only as a last resort.

**Comment by thomaseizinger** [comment]
Descoping because it is only a last resort and hence not important for now.
