### ISSUE TITLE
Extend actor rollover tests

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#1036]
After #1014, we have rollover actor tests which verify that the `projection::CfdState` changes as expected throughout the rollover protocol.

We would like to also assert that:

- Accepting and succeeding in rolling over results in a new `Dlc` and `oracle_event_id`.
- Rejecting the rollover keeps the CFD the same.

_Originally posted by @klochowicz in https://github.com/itchysats/itchysats/pull/1014#discussion_r779338129_

**Comment by klochowicz** [comment]
@da-kami has your recent additions selved this issue?
