### ISSUE TITLE
Simplify invariant checks for completing protocols (contract-setup, rollover, collab settlement)

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#1038]
At the moment, we use the `can_XYZ` functions at the top of these commands.

That is not entirely correct. Those functions should only be used to check if we can _start_ these protocols. All command handlers for completing these protocols should simply check if there has been any event applied in-between (by passing in an expected aggregate version). If there is a version mismatch, the protocol must fail because it would act on stale data.

**Comment by bonomat** [comment]
@luckysori : this sounds outdated. I'll close it but feel free to re-open and update the description if you disagree.
