### ISSUE TITLE
Check sanity of `oracle_event_id` sent by maker after accepting rollover

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#1039]
When we handle the `RolloverAccepted` message from the maker in the `rollover_taker::Actor`, we trust the maker to send a sane `oracle_event_id` value.

We should add some logic to only continue with the rollover if the `oracle_event_id` is within an acceptable range e.g. a few hours in the future.

**Comment by thomaseizinger** [comment]
Closing in favor of https://github.com/itchysats/itchysats/issues/1622.
