### ISSUE TITLE
Sometimes maker stops sending the heartbeat

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#1041]
During today's testing on master (debug mode), I realised that sometimes maker stops sending heartbeats to the taker; this results in a taker being in stuck in a connect -> disconnect -> connect loop every 20s.

This seems to be an error uncovered, but not caused by #906. More logs or debugging is needed to see where does maker get stuck (I wasn't able to update cfd offer either, which might indicate a more serious problem).

After restart, everything carried on without a problem.

**Comment by thomaseizinger** [comment]
Likely outdated.
