### ISSUE TITLE
Disconnected from feed is triggered *a lot*

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1047]
What I did:

1. Start taker daemon without maker running
2. Start taker UI

Expected behaviour:

The taker does not have connection to maker (because the maker was not started).
The taker UI displays "limited functionality", i.e. the warning `No maker! You are not connected to any maker. Functionality may be limited` is shown, but the user interface is usable.

Actual behaviour:

`No maker! You are not connected to any maker. Functionality may be limited` is shown but additionally I keep getting toasts that claim I am not connected to the feed. That is incorrect. The taker UI is connected to the taker daemon. These toasts should not be triggered. The user is advised to refresh, but refresh results in the same behaviour.

Due to the problem described in #1042 the user interface is not really usable.

I am not entirely sure that the problem of the taker not having a connection to the maker causes this problem. But, in that scenario it was reproduceable. I saw the error of not being connected to the daemon generally very frequently - could it be that we are reacting to *all* error scenarios somehow and always print that error?

![image](https://user-images.githubusercontent.com/5557790/148673494-b9d5a55c-d201-42ba-b09b-79b1b4ef8a44.png)

**Comment by da-kami** [comment]
The problem might not actually be related to the maker not being available. After starting the maker I still get the error - but not always. I could not find a pattern yet.

**Comment by thomaseizinger** [comment]
In any case, we should not pile up this notification. It should either be active or inactive.

**Comment by da-kami** [comment]
To make clear: I was using the dev setup and accessed the UI at `localhost:3000`. It has to be verified that the same problem exists exists when accessing the UI served by the daemon on `localhost:8000`.

**Comment by da-kami** [comment]
I also see this when using the UI served by the taker daemon locally: 

![image](https://user-images.githubusercontent.com/5557790/148891781-5d73efe7-99f3-4b8a-b04a-a2e66ee73216.png)
