### ISSUE TITLE
CI occassionally fails on tests in debug mode

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#1064]
The actor tests running on a single thread are problematic as they sometimes result in failures due to hitting timeouts.

Some proposals to fix it
- use `tokio::spawn_blocking` for signing and verifying during contract setup
- use multi-threaded tokio scheduler in tests (this would require adjusting tracing config)

Alternatively, as a temporary workaround:
- increase the timeout yet another time (we already did from 60s to 70s, it improved things but not fully)

**Comment by da-kami** [comment]
I am surprised we hit the `70s` timeout so often - are we sure there are no other (blocking / starving) issues that cause this problem? 

The assumption is, that loading from the database increases the runtime with the event sourcing changes - but I am not totally convinced that is the actual issue. We can give multi-threaded environments a try, but might also want to look into what could potentially starve message-sending during contract setup.

**Comment by klochowicz** [comment]
IMHO the commits referenced above have nothing to do with the issue posted above - it got fixed last Friday, with #1084.
