### ISSUE TITLE
Prevent the taker from acting on outdated state

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1077]
Add a fingerprint to every projection that is sent out. 
When the taker UI makes a request to the daemon we include the fingerprint the UI knows and compare it in the daemon against the fingerprint of the last projection sent out. 

That way we can detect if we are acting on outdated state and can fail the request with a warning to the user.

**Comment by thomaseizinger** [comment]
Nice summary, don't really have anything to add so will unassign myself.

**Comment by bonomat** [comment]
This project is unmaintained
