### ISSUE TITLE
sats / BTC switch in the UI

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1079]
With small amounts the BTC display can be annoying. Umbrel offers a `sats / BTC` switch, so one can switch between displaying BTC and sats. I think we should have that as well. 

In order to make that happen I propose the following changes:

- change the projection API to always return `bitcoin::Amount` `as_sat`
- Add a `Amount` component to the UI that holds the satoshi amount and allows display in BTC and sat. The conversion is trivial multiplication that should not lead to any loss; we could even opt for using a decimal type so we can just shift the dot. Use this new component for all amount displays.
- Add a toggle switch to the user interface to allow switching `sats / BTC`

Note: We don't send any bitcoin related amounts to the daemon, so no changes there. If we ever send bitcoin related amounts in request we should send them in sats.

**Comment by thomaseizinger** [comment]
> * Add a `Amount` component to the UI that holds the satoshi amount and allows display in BTC and sat. The conversion is trivial multiplication that should not lead to any loss; we could even opt for using a decimal type so we can just shift the dot. Use this new component for all amount displays.
> 
> * Add a toggle switch to the user interface to allow switching `sats / BTC`

Note: If we want a global switch for this, we should utilize a `React.Context` to store the global state and pass it to all `Amount` components implicitly.

**Comment by klochowicz** [comment]
we could go even further, and have Settings/Preferences that are stored in the backend (e.g. `Rocket::State` for the time being), and then just emit `String` based on the preference from Projection actor.

**Comment by da-kami** [comment]
> we could go even further, and have Settings/Preferences that are stored in the backend (e.g. `Rocket::State` for the time being), and then just emit `String` based on the preference from Projection actor.

I would not enable different serialization because it will be hard to maintain. We would have to align all APIs to have both BTC and sats. This includes the feeds as well. I think the serialization should always be in `sat` - so the API should always hand out sats and the UI decides how to display. 

On top of that we can enable some settings API that allows the user to store his preferences. I see that as independent feature.

**Comment by klochowicz** [comment]
> > we could go even further, and have Settings/Preferences that are stored in the backend (e.g. `Rocket::State` for the time being), and then just emit `String` based on the preference from Projection actor.
> 
> I would not enable different serialization because it will be hard to maintain. We would have to align all APIs to have both BTC and sats. This includes the feeds as well. I think the serialization should always be in `sat` - so the API should always hand out sats and the UI decides how to display.
> 
> On top of that we can enable some settings API that allows the user to store his preferences. I see that as independent feature.

I think you misunderstood me - you could expose `String` or a `Decimal` in projection, no need for different serialisations. Depending on the preferences, you could write in a different format. (it's all for the UI representation, and if no calculations would be happening in the UI, it doesn't matter what type it is?

**Comment by bonomat** [comment]
This project is unmaintained
