### ISSUE TITLE
Price recommendation for the maker's sell offer creation

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#108]
What we currently have:

![image](https://user-images.githubusercontent.com/5557790/134262042-b992cb2d-629f-4516-9ee0-c679e7968e94.png)

The maker currently has to enter a price manually when pricing the CFD. 
This is quite cumbersome and can be optimized.

In an initial iteration I propose that we change the fields to:

1. Instead of an editable field `OrderPrice` have an editable field `Spread` (in percent) that is defaulted to `3%`
2. Maker the `OrderPrice` field non-editable
3. Calculate the `OrderPrice` from current price and spread.

(3.) can easily be achieved with a calculation endpoint (similar to the taker's `/calculate/margin`) that is triggered on either a price change or a spread change. 

Note: This ticket is depending on having a price feed as described in #96 

Note: This could eventually be extended with automated offer re-publication,  but that is out of scope for this ticket.

**Comment by da-kami** [comment]
One thing we should definitely do once we have a price feed is change the `Order Price` initial value upon startup to be in relation to the price feed's price.

**Comment by da-kami** [comment]
I see this as a `ready-to-play` ticket. For the `happy-path-clickthrough` it might as well just be the editable price field.

**Comment by thomaseizinger** [comment]
The idea of `ready-to-play` was to be a lot more _bare-bones_ than `happy-path-clickthrough`! It should only contain things that stand inbetween us and doing a release and using it whatever "using" means at that point in time from a feature-set perspective.

**Comment by bonomat** [comment]
This seems to be done: we pre-load the order price with a number and add a spread.
