### ISSUE TITLE
Adapt our protocol to use the attestation scheme implemented by olivia

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#111]
At the moment, we are using the attestation scheme defined in the DLC specs. This is not compatible with Olivia and might actually have security problems if used in the wrong way.

The implementation in Olivia is here: https://github.com/LLFourn/olivia/blob/master/olivia_secp256k1/src/lib.rs

We need to adapt our protocol to be compatible with that.

**Comment by luckysori** [comment]
Done with #201.
