### ISSUE TITLE
Taker does not recognize being unconnected from maker

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1112]
This happened when testing op top of the `funding-rate` branch, commit: `45f599a34fcf74bc90f750593cda07c4eb2268b7`

What happened:

- both taker and maker running
- shutdown maker
- taker noticed maker gone after some time
- start maker again
- taker notices maker back up
- shutdown maker
- taker does never notice maker gone (even after 10 minutes)

Screenshot:

![image](https://user-images.githubusercontent.com/5557790/149688745-a71c7292-9629-487b-bd6c-49bda7e644b3.png)

**Comment by da-kami** [comment]
When restarting it works as expected, but I don't understand why it would not recognize the maker's absence sometimes.

**Comment by luckysori** [comment]
Unable to reproduce this on master with fresh maker and taker, after multiple maker restarts.

What I have noticed is that every time we lose connection to the maker we briefly display the `Please ensure taker daemon is running`, which is wrong. I'll open an issue about it.

**Comment by da-kami** [comment]
ok, closing for now
