### ISSUE TITLE
Charge funding fee based on the *counterparty* margin instead of *margin* (or "amount of contracts")

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#1114]
Just pointing this out, we don't have to action it now, but we should keep in mind that this might not be what we want:

I am not sure collecting the fee based on our margin is correct. When discussing this with @bonomat we were talking about charging the fee on the `counterparty` margin, because that is what you borrow. 
That has the effect, that higher leverage will result in higher fees. 

Note that BitMEX is charging based on the amount of contracts (an abstraction that is still missing in our model):

> `Funding = Mark Value * Funding Rate`
> Your Mark Value is irrespective of leverage. For example, if you hold 100 XBTUSD contracts, funding is charged/received on the notional value of those contracts, and is not based on how much margin you have assigned to the position.

see: https://www.bitmex.com/app/perpetualContractsGuide#Funding

Maybe you can add a comment so we don't forget discussing this with @bonomat ?

_Originally posted by @da-kami in https://github.com/itchysats/itchysats/pull/1102#discussion_r785622066_

**Comment by da-kami** [comment]
@bonomat would be great to hear your opinion on this. 

From what I heard in discussions with @bonomat then our goal is to align our model with Bitmex, because that is what a lot of people are used to.

**Comment by bonomat** [comment]
@klochowicz : 

> With high leverage, a trader that pays for funding may suffer losses and get liquidated even in low volatility markets. 

That should not be the case but I see how I confused people :D 

The link you shared is actually quite good. 
A few things to repeat from the linked document: 

```
Interest Quote Index = USD Lending Rate in the BitMEX Index (.USDBON)
Interest Base Index = XBT Lending Rate in the BitMEX Index (.XBTBON)
```

So, there is an interest rate on the USD and on the XBT (BTC). 

Funding rate is calculated as follow: 

```
Interest Quote Index = 1.00% per day
Interest Base Index = 0.25% per day

Funding Rate = Interest Quote Index - Interest Base Index
Funding Rate = (1.00% - 0.25%) / 3 = 0.25%
```

Bitmex has a funding round every 8 hours. Hence `/3`. 

If this value is positive, the longs pay the short, if it is negative, the shorts pay the longs. 
Or differently said: 

The longs _borrowed_ the quote currency from the shorts. 
The shorts _borrowed_ the base currency from the longs. 

Note: How to come up with these interest rates is a different topic and my old opinion of "in a bear market the quote interest outperforms the base interests" does not really hold. But this is not important atm. 

Now to the funding rate calculation. 

I said, 
> the funding rate depends on the **counterparty's** margin

Might not be perfectly accurate but I think it works in our case. 
Let's consider the general case according to the example from the doc: 

The taker bought $15k contracts at the price of $750/BTC 
```
15,000 Contracts * 1 USD * 1/750 = 20 XBT`
```

In our case, the counterparty (the maker) always has leverage 1, meaning, he has to put up 20 BTC as collateral. 
The leverage of the taker has no effect in this case, as the counterparty's margin remains always `quantity/price=15k/750=20BTC`. Differently said, even if the taker's leverage is high, the maker still has to provide `quantity/price` as collateral as we fixed his leverage to 1. 


That being said, the funding rate is calculated with: 

```
Funding Amount = Mark Value * Funding Rate 
```

```
Mark Value = Contracts / Spot price 
=> 15k/750 = 20
=> 20 XBT * 0.25% = 0.05 XBT
```

Meaning, the taker has to pay 0.05 XBT at the next funding round.

Interestingly, if the value rises, your position value decreases and hence you pay less funding. 

For example, let's say you bought 10 XBTUSD contracts at a price of $20/BTC.

```
#Contracts * 1/EntryPrice = Position Value
10000 * 1/20000 = 0.5XBT

Funding amount = Value * Funding Rate = 0.5XBT * 0.25% = 0.5XBT * 0.0025 = 0.00125XBT
```

If the price of Bitcoin rises to 40.000 then your position value would be only worth 0.25XBT (10k/40k)  what also leads to less funding (0.000625).


-------


I've created a spread sheet to play around with it: https://docs.google.com/spreadsheets/d/1P_i5_bKhAi-eqNI8h0psslYfqTxbaby2tO87yIskT84/edit?usp=sharing

Best is to make a copy and edit as this is a publicly accessible link

**Comment by bonomat** [comment]
@klochowicz / @da-kami : please re-read the response. I've received a response from Bitmex and updated the description slightly and added another example.

**Comment by bonomat** [comment]
@klochowicz : we made a new learning: the funding amount is independent of the counterpary's margin and depends only on the position value. There is a lengthy description in here: #1167 

I'll close this ticket for now. Lets keep the discussion in one place and open a new ticket once we know how to move forward.
