### ISSUE TITLE
Taker UI keeps "flickering" because we show for a split second that we are unconnected from the daemon

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1128]
This happens really frequently for me and is annoying because it keeps "moving" the UI up and down because the warning appears at the top for a split second and then is gone again. 

Maker and taker running locally. The logs don't show any connection issues so I assume the problem is the user interface.
I could not see any relationship between what's happening in the daemon logs and the message appearing.

![2022-01-18 13 59 39](https://user-images.githubusercontent.com/5557790/149864266-449c809e-c109-4860-ab93-eb5a4a9b2a1f.gif)

(don't get distracted by the red dots appearing, that's just me clicking ;)

**Comment by da-kami** [comment]
note: sometimes the message appears a bit longer, about 1sec

**Comment by klochowicz** [comment]
perhaps it might be due to the timers not being cancelled by the timer handle so it means that they are triggered sometimes?

**Comment by rishflab** [comment]
Ok me and @luckysori tried on latest master and it is not working. I had to `yarn build` to get it not to flicker?????

**Comment by da-kami** [comment]
was unable to reproduce this lately, closing.

**Comment by da-kami** [comment]
I see with quite often on Umbrel in production. The behaviour is the same as reported before. Reopening this issue.

**Comment by bonomat** [comment]
I've noticed this also more than once.

**Comment by thomaseizinger** [comment]
We should investigate that we are actually running on top of HTTP2!

**Comment by rishflab** [comment]
I was unable to reproduce this.

I tried against a local testnet maker, remote testnet maker and created a bunch of CFDs. I tried against a remote mainnet maker but did not create CFDs. 

Update:
Apparently this issue only occurs when the taker UI is running on a different machine to the taker daemon.

**Comment by klochowicz** [comment]
looking briefly at the current code in the frontend, I suspect that you still will have the flickering each time the connection gets broken, even for a short whileit essentially recreates the whole `useEffect` whenever any arguments change, one of them is being connected. and then it is being set to false before it is set to true.
the old code used separate `useEffect` for the actual event stream and for heartbeat measurements & alert raising, so it likely did not suffer from this problem.
