### ISSUE TITLE
Store the funding fees in a Cfd event

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#1131]
we need to store the funding fees to be able to:
1) present aggregated fees to date to the user,
2) account for already paid fees for the rollover (the margin changes slightly due to them)

IMHO it would be most convenient to include them in  `ContractSetupCompleted` and `RolloverCompleted`, but as the events are immutable, that can't really be done? (unless we treat this as the "last" time we change them, as it's the first release including event sourcing?)
Creating a separate event to store them seems a bit excessive...

**Comment by da-kami** [comment]
> IMHO it would be most convenient to include them in `ContractSetupCompleted` and `RolloverCompleted`, but as the events are immutable, that can't really be done? (unless we treat this as the "last" time we change them, as it's the first release including event sourcing?)

I agree that in `ContractSetupCompleted` and `RolloverCompleted` we should record the effective fee that was charged.
I don't really see the problem you state as immutable. I think we should know the fee when we emit `ContractSetupCompleted` and `RolloverCompleted` so why can't we add it to these events?

---

Eventually the taker will also have to check for sanity and ensure that the fee that is charged actually corresponds to what the maker claims he will charge. But that can be added later.
