### ISSUE TITLE
Unlock temporarily locked UTXOs on failed contract setup

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1135]
1. Include failed transaction in event
2. Extract inputs from transaction
3. Ping wallet actor to unlock UTXOs

**Comment by luckysori** [comment]
Does this situation ever resolve itself? E.g. by restarting the application? In any case I think this issue is important.

**Comment by thomaseizinger** [comment]
Nope, it does not resolve itself without a restart of the application or the wallet actor (once we can restart that one: https://github.com/itchysats/itchysats/issues/1284).
