### ISSUE TITLE
Takes does not have price results in not being able to close (forever...)

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1137]
commit: `60bfc38b7a0fa5520f869b067e54a6eadc5af1de` (`funding-rate` branch rebased on latest master, on top of commit `bac0b131e8f9cddcc355043d54f684bbe4a4086d`)

The result of this problem is not being able to collaboratively close. But I don't have the possibility to force-close, so I am basically stuck in having to roll over forever 😅

I keep running into this issue locally with the taker:

```
2022-01-18 19:51:43 TRACE daemon::oracle: Skipping /x/BitMEX/BXBT/2022-01-19T08:00:00.price?n=20 because it likely hasn't occurred yet
2022-01-18 19:51:44 TRACE daemon::projection: Price feed actor currently unreachable
```

I went through the logs and saw the `Price feed actor currently unreachable` several times, but no related errors or warnings. 

![image](https://user-images.githubusercontent.com/5557790/149903336-fba5edfe-0ddb-40fe-bbbe-51db1fe6e80e.png)

**Comment by da-kami** [comment]
After a restart of the taker I got a price again and was able to collab settle.

**Comment by da-kami** [comment]
I run into this issue with the maker as well, causing weird side effects like not being able to do a contract setup (?).
If I see this problem contract setup keeps timing out. Since both sides can run into this problem it can result in being unable to settle / contract creation.

**Comment by thomaseizinger** [comment]
> After a restart of the taker I got a price again and was able to collab settle.

Yep, that is sort of expected at the moment. Given that a workaround exists (restart), this has pretty low priority IMO.
Settling should eventually get a price from the maker so this issue would go away then. Also see the discussion here: https://github.com/itchysats/itchysats/discussions/1108

I am going to remove this from the milestone for now.

Did you see any logs in regards to the supervisor restarting the price feed actor?

**Comment by thomaseizinger** [comment]
The price feed actor should be restarted if it fails due to a connection error. If it panicked, then it is gone at the moment.

I opened https://github.com/itchysats/itchysats/pull/1157 to address this so that might solve this issue!
