### ISSUE TITLE
Add order_id to log statements

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1140]
Due to the nature of our program being async it is sometimes hard to know which log message belongs to what. 
It would be useful to add a the `order_id` (or similar) to all logs that belong together. 
Our logging library should support this using _instrumenting_

**Comment by klochowicz** [comment]
I think this has been implemented - do you agree @bonomat  ?

**Comment by bonomat** [comment]
Jan, 19 ... good times ... :D
