### ISSUE TITLE
Monitor actor does not follow ADR013 for blockchain events

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1149]
[ADR013](https://github.com/itchysats/itchysats/blob/master/docs/adr/013-all-actors-can-hydrate-cfd.md) states that a CFD should be loaded and hydrated wherever needed.

The monitor actor does not follow this as it sends blockchain events to the `maker_cfd` / `taker_cfd` actor. Instead, it should use the `command::Executor` to call the corresponding command (`lock_tx_confirmed` etc) on the corresponding CFD.

The difficulty with making this happen is that our current test framework relies on sending the events directly to the `maker_cfd` and `taker_cfd` actor. This will have to be changed to interact with the monitor mock instead.

**Comment by klochowicz** [comment]
changing the tests this might be really difficult, and I suspect the trade-off can not be worth it - perhaps we could re-evaluate pros and cons of ADR013?

**Comment by thomaseizinger** [comment]
> changing the tests this might be really difficult, and I suspect the trade-off can not be worth it - perhaps we could re-evaluate pros and cons of ADR013?

Happy to discuss ADR013 but I don't think that it is particularly difficult to achieve. I'd probably just replace the `monitor` mock with a hand-written one similar as the price feed: https://github.com/itchysats/itchysats/blob/master/daemon/tests/harness/mocks/price_feed.rs

That mock would have access to the DB and have functions like:

```rust
impl MockMonitor {
	pub async fn lock_transaction_confirmed(&self, id: OrderId) {
		self.executor.execute(...);
	}
}
```

Those can then be easily called from the test.
