### ISSUE TITLE
Connection actor in taker binary does not follow ADR006

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1150]
[ADR006](https://github.com/itchysats/itchysats/blob/master/docs/adr/006-actors-for-resources.md) defines that resources should be tied to the lifetime of an actor.

The connection actor in the taker binary currently does not follow this decision. There is a draft PR here that might contain worthwhile commits: https://github.com/itchysats/itchysats/pull/851

**Comment by luckysori** [comment]
This connection actor doesn't exist anymore 🎉
