### ISSUE TITLE
Connections in maker binary does not follow ADR006

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1154]
[ADR006](https://github.com/itchysats/itchysats/blob/master/docs/adr/006-actors-for-resources.md) defines that resources should be tied to the lifetime of an actor.

The connections managed by the `maker_inc_connections::Actor` don't follow this decision. They are not modeled as actors at all but instead, the `maker_inc_connections::Actor` supervises ALL connections.

It is at this stage unclear how this will interact with https://github.com/itchysats/itchysats/issues/1126.

**Comment by luckysori** [comment]
This actor won't exist for much longer.
