### ISSUE TITLE
Stop logging password for maker

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1161]
We should stop printing the passwords in the maker logs as this bears a security risk. 

I noticed this because I would like to use a log analyzer such as [Loki](https://grafana.com/oss/loki/). I feel uncomfortable with using a hosted version of Loki if the log files contain the password.

//edit// I was able to create a filter which prevented me from pushing the password to Loki. Nevertheless, I think this ticket is relevant.

**Comment by thomaseizinger** [comment]
I guess we could provide a command to print the password to the stdout instead? Somehow the user has to get ahold of the password!

**Comment by klochowicz** [comment]
> I guess we could provide a command to print the password to the stdout instead? Somehow the user has to get ahold of the password!

that sounds like a good idea! that gives a more vigilant user an opportunity to pipe it straight to the clipboard, removing it from being printed out at all.

and let's not forget that majority of our users are on umbrel now, so they read the password in the app store, not in the logs - they won't have a way of triggering the command, but at the same time no need for it :)

**Comment by bonomat** [comment]
An alternative would be to not derive the password from the seed but have it default one for the beginning which the user has to change.

**Comment by klochowicz** [comment]
> An alternative would be to not derive the password from the seed but have it default one for the beginning which the user has to change.

it would work too, although it would require an UI change and would have an impact for umbrel - the option discussed above is really simple, and most people (umbrel users) would not even need to use the command.

**Comment by thomaseizinger** [comment]
> An alternative would be to not derive the password from the seed but have it default one for the beginning which the user has to change. 

But then we would have to store it (securely). This ties in with the discussion #1088 as well - how do we want this to behave on different platforms.

I agree with @klochowicz that for an umbrel user, changing the password doesn't make any sense.

**Comment by bonomat** [comment]
What do think of using the same flow as for the taker on the maker? Meaning, we pass in the password when starting? 
That way we don't have to print it in the logs neither and don't have to provide an additional command to print the password?

**Comment by thomaseizinger** [comment]
> What do think of using the same flow as for the taker on the maker? Meaning, we pass in the password when starting? That way we don't have to print it in the logs neither and don't have to provide an additional command to print the password?

Not a whole lot to be honest. The requirements are quite different.

We added the parameter for umbrel to provide a better user experience for the user because umbrel manages these passwords.
We have no such system for the maker, meaning that adding a parameter would just introduce additional friction in starting up the application.

I don't see any value in off-loading password generation to the user when we can also do it for them. The seed should already be backed up so generating the password for the user is one less thing they need to deal with.

**Comment by bonomat** [comment]
(let's focus on the maker only for now - I've updated the description) 

I think the passwords should be 
- independent of the public key (and hence the seed)
- changeable
- not be printed in the logs
 
once a maker's passwords was compromised the only way to get a new one is to create a new seed, which requires him to have a new wallet, he has to close all open positions first and then he has to tell all his takers to reconnect with a new pk.

**Comment by thomaseizinger** [comment]
> once a maker's passwords was compromised the only way to get a new one is to create a new seed, which requires him to have a new wallet, he has to close all open positions first and then he has to tell all his takers to reconnect with a new pk.

That is a fair point.

The original design of the seed was inspired by https://smallstep.com/blog/command-line-secrets/. Following the same idea, a file containing the password would be the best option.

Does that work for you? I think it fulfills all the listed criteria.

- Independent of PK
- Can be changed even without the application (just write a new password to the file)
- We can remove the printing from the logs

**Comment by thomaseizinger** [comment]
Closing in favor of https://github.com/itchysats/itchysats/issues/1630.
