### ISSUE TITLE
Price Alignment in the Taker UI

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1163]
When I started with this funding rate UI changes #1066 I came to the conclusion that the "reference price" is not really important when opening a position
I expect that with the perpetual position the spread will either go away or be minimal. Nevertheless, I think we need the current "closing" price as known in the taker daemon - that would be the reference price for me; the fact that we are not using the index price there is an implementation detail of the daemon.
The price that is currently displayed in the bubble is the maker's ask price, which is not enough. We definitely need bid once we add short, but we should also display the reference price again.

Now, I am not sure about my initial thoughts anymore. The reference price might be important when opening a position as well, because it shows the spread of the maker. If we assume that there is no spread then it is not important there. But I think this is not guaranteed, so we have to display the reference price. The relationship between the different prices should be made clear though.
For closing the position the reference price is the only price that matters which makes me think that we might want to display it in the top bar, because then it is available throughout the whole program.

Additionally, if we ever want to distinguish between the maker's closing price and the index price used by the Oracle, we would have yet another price - that is only relevant for closing the position with the maker.

So, in the end we have 4 prices:

1. Maker's ask for opening long
2. Maker's bid for opening short
3. Maker's closing price 
4. Index price used by the Oracle

I would propose, that for now we don't distinguish (3.) and (4.) but only bring (4.) back as "reference" price in the top bar. That way the user has an indicator if there is a spread when opening a position, and an indicator what the current price is when closing (even though that is not the effective price used).

**Comment by da-kami** [comment]
The reference price is actually back. The other problems can be tackled as part of going short. @klochowicz might be worth reading through this ticket concerning the scope for going short in the UI. I think we should change this ticket or create a new more dedicated ticket for short though and then close this.

**Comment by klochowicz** [comment]
@da-kami,  is there anything actionable here still? The current UI on master somewhat solves the problem of differentiating between 1 and 2. The 3 only comes into play in the closed positions (which is fine, and expected), and 4 is at the top.
This all looks pretty good to me!
Are you ok with me closing this ticket?

**Comment by bonomat** [comment]
I'm closing this for now. If deemed as actionable, please re-open.
