### ISSUE TITLE
Margin and Cost relationship in the Taker UI

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1164]
This is a follow-up of #1066 

Given that we cannot add to lock at the moment our margin is not constant but changes with every funding event (i.e. we never add "fresh" money to keep the margin constant or reduce it).

The relationship of margin and fees is currently not clear enough. I will see to display the margin as current margin (i.e. initial margin - fees) and add a tooltip that shows initial margin and costs. That way we also don't show the costs in the tile itself.

This includes keeping track of the initial margin in the internal model and exposing it in the projection. It should be trivial to keep the initial margin that was used in the contract setup internally.

**Comment by da-kami** [comment]
@bonomat in a comment on #1066 you mentioned

> I think, the _current_ `margin` should be _initial_ `margin` minus `fees_paid`. 
Meaning, the longer your position is running, the more fees you have paid, the lower your margin. 
That being said, we could display this to the user ala `Margin = initial funding - fees paid = 0.003 - 0.0001 = ...` (provided we have this data available. 

What would that mean for the opening fee? 
I think currently there is not way around "reducing"the margin when rolling over. But, we can ensure that the `opening_fee` is charged on top of the margin, as displayed in the UI. We have to ensure that this is what we actually do internally! - The amount locked up should not just the margin, but margin + opening fee. For not I would assume that the taker always has to pay an opening fee, while the maker only locks up the maker's margin. Eventually we could make this dependent on the current funding fee as well, so either the taker OR the maker would then pay the opening fee.

Reducing the margin on rolling over is a bit odd as discussed here https://github.com/itchysats/itchysats/discussions/1167

For now, I would keep the contracts constant, but reduce the margin only upon rollover. So, we deduct additional costs after opening from the margin and use that reduced margin for calculations like P/L as discussed in #1165.

**Comment by bonomat** [comment]
I would model the `opening_fee` the same way as `additional_fees`. To keep the discussion in one place, let's continue in 
 #1167 .

**Comment by da-kami** [comment]
> I would model the `opening_fee` the same way as `additional_fees`. To keep the discussion in one place, let's continue in #1167 .

After discussion with @bonomat we came to the conclusion that the opening fee is not a funding fee (but a separate fee that always goes from taker to maker for opening the position) and is to be treated separately.

**Comment by klochowicz** [comment]
> > I would model the `opening_fee` the same way as `additional_fees`. To keep the discussion in one place, let's continue in #1167 .
> 
> After discussion with @bonomat we came to the conclusion that the opening fee is not a funding fee (but a separate fee that always goes from taker to maker for opening the position) and is to be treated separately.

cool. I can change the code to act this way, but would you mind opening a ticket for it and adding it to the milestone so I can work on it? :)

**Comment by da-kami** [comment]
After discussion with @bonomat  we came to the conclusion that the funding rate should always be charged on the `initial_counterparty_margin`, so the funding rate is charged on a constant amount and then subtracted from the `current_margin`. Note: If the funding fee is negative for the party then it will be added; one party's loss is the others gain.

**Comment by klochowicz** [comment]
> > I would model the `opening_fee` the same way as `additional_fees`. To keep the discussion in one place, let's continue in #1167 .
> 
> After discussion with @bonomat we came to the conclusion that the opening fee is not a funding fee (but a separate fee that always goes from taker to maker for opening the position) and is to be treated separately.

how do you want to calculate this opening fee? is it truly a fixed fee independent of the amount of contracts taken by the taker? or do you want to send it as a percentage of the initial margin? 

It makes a difference as to what I should expose on the API level (a fixed `maker_fee: Amount` or `maker_rate : Decimal` (the latter being a percentage of the initial margin).

**Comment by da-kami** [comment]
> how do you want to calculate this opening fee? is it truly a fixed fee independent of the amount of contracts taken by the taker? or do you want to send it as a percentage of the initial margin?

I see it as a fixed, independent fee. However the maker wants to calculate it (i.e. based on funding rate ...) is up to the maker. It does not have to be a signed amount because it cannot be negative - the lowest it gets is `0`. The assumption is that it is always paid from taker to maker.

**Comment by klochowicz** [comment]
> > how do you want to calculate this opening fee? is it truly a fixed fee independent of the amount of contracts taken by the taker? or do you want to send it as a percentage of the initial margin?
> 
> I see it as a fixed, independent fee. However the maker wants to calculate it (i.e. based on funding rate ...) is up to the maker. It does not have to be a signed amount because it cannot be negative - the lowest it gets is `0`. The assumption is that it is always paid from taker to maker.

I'm with you with the `Amount`, that's the type I proposed above. Happy to just expose that in the maker's API, and the maker can calculate it outside of itchysats.
