### ISSUE TITLE
Use the payout curve to determine unrealized P/L 

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1184]
We had an old ticket for this a long time ago, but I did not bother finding it. 

With #1182 I am properly locking in the profit/loss based on the payout.

The calculation for the payout and p/l according to the current price (i.e. unrealized p/l) should also be based the payout curve to be more correct. At the moment we use a separate calculation based on the initial contract terms. 
This is not optimal because the payout curve is used to determine the payout for both collab and non-collab settlement, so we should always use it for unrealized payout and unrealized p/l as well. This will also simplify things, because that calculation will go away. 

For CFDs where we already have a DLC we can determine the unrealized payout from the CETs. This means, we don't have to come up with the payout curve every time we ping the projection for changes.

For CFDs where we don't have a DLC we could either keep some calculation, always calculated the payout curve and pick according to the current price or *just don't show payout and P/L*.
I think it would actually be correct not to show any P/L and payout for something that is not set up yet. If we opt for that our separate calculation of payout and p/l based on current price can just go away.

**Comment by da-kami** [comment]
This is actually not as easy as I thought. From the `Cet`s alone we cannot easily determine the payout. For the collaborative settlement we also don't do that but calculate the payout curve and use that. I wonder if it would make sense to store the current payout curve somewhere so we can use it.

**Comment by thomaseizinger** [comment]
> I wonder if it would make sense to store the current payout curve somewhere so we can use it.

We can always recalculate it. If that is too in-efficient, we can think about caching that computation somewhere.

**Comment by da-kami** [comment]
Closed in favor of https://github.com/itchysats/itchysats/issues/1608
