### ISSUE TITLE
How to deal with limbo offer state

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#120]
With the current model, offers will "disappear" if a taker took it. 

With this model we have an in-between state on the maker side: the state in between of a taker requesting to take an offer and the maker accepting/rejecting it. 

Differently said: multiple takers might want to take the same offer from the same maker. 

This has some further implications: 
Atm an incoming `TakeOrder` request will overwrite an existing one. This can lead to a problem where the user (the maker) wants to accept an order for one user but it gets overwritten by an incoming request from a different taker. 

The question is how do we want to deal with this?

**Comment by thomaseizinger** [comment]
I guess in an ideal world, we would present the maker with all the orders and let them chose one.

That is a bit trickier to implement so I would suggest the following:

- Incoming order from taker removes the current offer for all other takers
- Maker rejecting that order re-activates the offer and updates all other takers
- Maker accepting the order moves forward with contract setup, maker has to manually create a new offer if they want another one

**Comment by bonomat** [comment]
That's resolved in #119 : an offer can only be taken once. The maker has to manually create a new offer
