### ISSUE TITLE
Taker UI `BitcoinAmount` displays number in user unreadable form

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1243]
![image](https://user-images.githubusercontent.com/5557790/151472132-2387b774-cc67-4f53-8773-22a93beb8639.png)

not really a bug, but we should probably tackle that.

**Comment by luckysori** [comment]
Is the solution to show 8 decimal places? That looks pretty silly to me :(

**Comment by da-kami** [comment]
can't reproduce anymore, maybe I'm an idiot

**Comment by thomaseizinger** [comment]
Also unreadable is a bit bold. Scientific notation is not that hard to read :)
