### ISSUE TITLE
Links to lock and payout transactions visible in 'PendingSetup' state

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#1247]
we didn't manage to set it up yet, these links are misleading (especially now that they're inactive):
<img width="451" alt="image" src="https://user-images.githubusercontent.com/8319440/151479565-182feb70-1ee3-4c6b-b163-d8d22b6db53d.png">

It seems like it's regression from 0.3.6.

**Comment by thomaseizinger** [comment]
> It seems like it's regression from 0.3.6.

I agree.

**Comment by luckysori** [comment]
After determining that this was primarily the result of using `DarkReader` with our dark theme, can we close this? We could also create an issue to redesign the way we display these possible transactions.
