### ISSUE TITLE
Do not look for `LockTransaction` again after rollover

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#1248]
Our event-sourcing system does not seem to suffer because of the `LockConfirmed` event being emitted twice, but it's still unnecessary. We should not just start monitoring all transactions after rollover.

**Comment by thomaseizinger** [comment]
I agree. I think this is basically an artifact of the API design of `StartMonitoring`. That is a pain in multiple places so we should probably just decompose that into smaller parts where we can be more fine granular on what we want to happen.
