### ISSUE TITLE
`Failed to load CFDs: missing field` should be an error 

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1249]
If loading from db fails, we only display a warning. 
Imho this should be an error so that it is easier detectable.

**Comment by thomaseizinger** [comment]
> Imho this should be an error so that it is easier detectable.

Does it prevent operation of the application? If it is not massively severe, a warning should be sufficient. We should definitely monitor for warnings and investigate every single one.

**Comment by bonomat** [comment]
> Does it prevent operation of the application? If it is not massively severe, a warning should be sufficient. We should definitely monitor for warnings and investigate every single one.

Yes it did. The maker was unusable unfortunately (cc @klochowicz )
