### ISSUE TITLE
Committed CFDs should display expected attestation time

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#1251]
If either party has triggered force-close, I would like to be able to see when the attestation is expected. We could even link to the `outcome-observer`: https://outcome.observer/h00.ooo/x/BitMEX/BXBT/2022-01-29T01:00:00.price?n=20.

I'm not sure if this would make as much sense if/when we combine positions.

**Comment by bonomat** [comment]
This project is unmaintained
