### ISSUE TITLE
Rollover error - cannot verify enc sig

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#1260]
I've run into this one:
`2022-01-28 12:04:55  WARN daemon::model::cfd: Rollover failed: Rollover protocol failed: CET signatures don't verify: enc sig on CET does not verify: failed to verify encsig spend tx: failed to verify adaptor signature order_id=e1f0caea-a84f-4805-a95b-de1f46917f1a`

One of the side effects of it is that the CFD gets stuck in "Rollover Proposed" state for longer than usual.
In eventually went back to open, but I have no idea whether the rollover worked or not via the UI - a "Funded until:" or similar field would be really beneficial.

**Comment by thomaseizinger** [comment]
Certainly a bug but nothing critical. The error handling (timeout waiting for the other parties response) worked as expected.

> but I have no idea whether the rollover worked or not via the UI

I am tempted to say the we shouldn't even expose when exactly rollover happens. I am not against a "Funded until" field but it is not really in the spirit of a CFD so I would like to hide the technical details of how we achieve perpetual positions. For example, if we would precompute 10 commit transactions that are all timelocked so we might not use them, what should `Funded until` display?

**Comment by klochowicz** [comment]
"Funded until" or something like that could be an useful prompt for the users who don't plan on having the app running 24/7 and would still like to enjoy a perpetual CFD without surprises - that was my line of reasoning

**Comment by bonomat** [comment]
closed because it might be outdated.

**Comment by klochowicz** [comment]
might be the same as: #1617
