### ISSUE TITLE
Handle orders (positions) rejected due to `Invalid OrderID` differently

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1268]
Imho we should handle rejections due to an invalid orderid differently. 
At the moment it happens to me quite often that I try to take an order and get 
```
2022-01-31 04:15:52 TRACE wire: Received InvalidOrderId
2022-01-31 04:15:52  INFO daemon::setup_taker: Order got rejected order_id=43e976dd-47d1-4f5d-b748-291aa99565be
```

In the UI I don't see why the order was rejected. 

Maybe a rejection should not even show up anymore ... (this was already mentioned by @thomaseizinger in #556 sometime ago)

**Comment by klochowicz** [comment]
IMHO it's also bizarre that we have stale order ids - this should not happen, we're supposed to clear order id (by broadcasting `None`) as soon as one taker proposes to take it!

**Comment by luckysori** [comment]
I think this isn't relevant once the legacy connection is phased out i.e. very soon.
