### ISSUE TITLE
Dissect `Dlc` struct according to new usage in event sourcing

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1288]
Previously, the `Dlc` struct needed to aggregate information internally to represent a newly setup but also rolled over CFD.

With event sourcing this is no longer the case.

- The lock transaction will remain the same across all rollovers so it shouldn't need to be stored within the data structure that is stored in `RolloverCompleted`.
Same thing for the refund transaction.
- The revoked commit transactions don't need to be kept within the `Dlc` struct but should instead be tracked as part of the `RolloverCompleted`.
- The stored CETs store extremely redundant data.
- We might be able to get rid of the `n_bits` field of `Cet`: https://github.com/itchysats/itchysats/issues/1301.

**Comment by thomaseizinger** [comment]
As part of this, try to make as many fields of `Dlc` private as possible.

**Comment by thomaseizinger** [comment]
Tagging this as performance because a big part of the deserialization problem might be the redundant storage of data.

We need to figure out, what the absolute minimal data is that we need to store and compute the rest on-demand.

**Comment by bonomat** [comment]
This project is unmaintained
