### ISSUE TITLE
Somehow "ignore" old CETs during rehydration

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1289]
Previous CETs are irrelevant after a rollover. However, due to the use of event sourcing, those are still kept around and pro-actively deserialized upon every hydration, regardless of whether or not they are used.

The deserialization of those CETs (around 1.3MB per event) incurs a big performance hit that is significant over time.

We need to somehow address this within the bounds of event sourcing (i.e. deleting the old event is not really a solution :upside_down_face:).

Ideas:

1. Have a `Lazy` wrapper around data types that allows to delay deserialization up until the data is actually accessed.
2. Have an in-memory read-model that keeps the applied CFD around so we don't go to the database for every update but only load the new events.

**Comment by da-kami** [comment]
Why is pruning event (data) not an option?
I think it's fair to keep the event around but remove the data of old ones when storing a new, successful rollover.

**Comment by a5an0** [comment]
drive-by, unsolicited suggestion: one way to handle this in event-sourced systems (I haven't dug into the ES in itchysats, so I'm going to be general and hand-wavy) is:
- Have a "snapshot" event type that reifies/materializes the state as of event `t` in the log and store that as entry `t+1`.
- store a `start-index` on disk with the log that points to the latest snapshot event

Periodically write a new snapshot entry to the log and bump the index stored in `start-state`. Whenever a node starts up or needs to rehydrate its state (after an update or something), it reads event-log[`start-index`] to initialize state and then starts replaying all the events that came after it. In this case with old (and no longer relevant) CETs, the CETs would still be in the log, but would be older than the latest state so you won't deserialize them again.

**Comment by thomaseizinger** [comment]
> drive-by, unsolicited suggestion:

Very appreciated nonetheless!

> * Have a "snapshot" event type that reifies/materializes the state as of event `t` in the log and store that as entry `t+1`.
> 
>     * store a `start-index` on disk with the log that points to the latest snapshot event
> 
> 
> Periodically write a new snapshot entry to the log and bump the index stored in `start-state`. Whenever a node starts up or needs to rehydrate its state (after an update or something), it reads event-log[`start-index`] to initialize state and then starts replaying all the events that came after it. In this case with old (and no longer relevant) CETs, the CETs would still be in the log, but would be older than the latest state so you won't deserialize them again.

This is very interesting. I hadn't considered the idea of a snapshot _event_! This should definitely improve the performance for rehydration. 

I also added the idea of an in-memory read-model to the original ticket description. When given the choice, would you pick the read-model or the snapshot event as an initial performance improvement?

**Comment by thomaseizinger** [comment]
> Why is pruning event (data) not an option? I think it's fair to keep the event around but remove the data of old ones when storing a new, successful rollover.

I am hesitant to do this because it is a pretty unexpected way of dealing with the problem. At the moment we assume that historical CETs are absolutely useless and there is a very high chance that this is the case. However, I'd prefer if we find solutions that mitigate the problem in different ways before we go down the path of selectively deleting data out of old events.

My current, preferred order would be (to optimize rehydration performance, not disk usage):

1. Check how much we can shave off with https://github.com/itchysats/itchysats/issues/1288, i.e. reduce the storage down to the absolute minimum required
2. Introduce an in-memory read-model
3. Snapshot closed CFDs and delete all of their events

Optimizing for long-term disk storage is a different concern but (1) and (3) would also help with that!

**Comment by thomaseizinger** [comment]
The projection actor now keeps in-memory read-model, meaning this problem is solved for now.
