### ISSUE TITLE
Remove bitmex price feed

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1290]
Atm: The bitmex price feed is used for the maker to come up with a rate when creating offers and for maker and taker for computing P/L. 

A few thoughts: 
- Offers are created using the HTTP Api and it's unnecessary to have the binary to provide the price feed, send out the price information via SSE, and then post the price again. This extra roundtrip is not needed and was removed in our personal automation. 
Hence, the maker is no longer making use of the price feed to create new offers. 

- The current price feed is used for computing P/L for positions: this is semi correct. The maker's P/L is calculated differently than the taker's P/L
  - maker's P/L: the maker has its own opinion on the price, meaning, his P/L should better be calculated from the outside. 
  - taker's P/L: the taker has not an own opinion on the price, he either gets what the maker is willing to offer (for settlement) or what the oracle attests to (force close). 

We want to show a P/L to the taker though: we have already two price feeds for the taker: 
1. the maker's offers
2. the bitmex index price feed

--> For the taker's unrealized P/L we probably should make use the maker's offers as this is what he would get when settling a position. 
--> We let the maker compute his P/L from the outside

Given that we can remove the bitmex price feed altogether. 

Note: For a precise P/L computation we should know the payout curve, meaning, if we want to compute P/L from the outside, we will need to expose this information via the HTTP Api.

**Comment by thomaseizinger** [comment]
Related https://github.com/itchysats/itchysats/discussions/1108.

**Comment by thomaseizinger** [comment]
> Note: For a precise P/L computation we should know the payout curve, meaning, if we want to compute P/L from the outside, we will need to expose this information via the HTTP Api.

We could also pass the current price into the maker, either via a parameter per endpoint or as a state in general. For creating a new order, we currently pass it in as a parameter. A solution for P/L that is consistent with this approach would be a query parameter on the `/cfds` endpoint that computes P/L based on this price for all currently open CFDs.

**Comment by thomaseizinger** [comment]
Closing in favor of the discussion https://github.com/itchysats/itchysats/discussions/1108.
