### ISSUE TITLE
`Not yet implemented: deal with revoke ` Error

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1300]
Version: latest master: 10ae1fb98c152e1d323edd22913d6b5378368287

I have 5 positions open, the taker and maker were running over night, restarted the taker and get these errors: 

```
thread 'rocket-worker-thread' panicked at 'not yet implemented: Deal with revoked', daemon/src/monitor.rs:277:32
thread 'rocket-worker-thread' panicked at 'not yet implemented: Deal with revoked', daemon/src/monitor.rs:277:32
thread 'rocket-worker-thread' panicked at 'not yet implemented: Deal with revoked', daemon/src/projection.rs:501:32
```

This kills some workers and the CFDs don't get published via SSE events anymore.

**Comment by thomaseizinger** [comment]
Replace panic with `error!` log for now.
