### ISSUE TITLE
Can we get rid of `n_bits` in `Cet`?

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#1301]
The field `n_bits` of `Cet` represents the number of relevant bits of the price range used when calculating adaptor points based on oracle announcements, and decryption keys based on oracle attestations.

This *appears* to be an optimisation. One could simply multiply by all the leading, zero bits of the price range. That may be inexpensive and it would allow use to remove this `n_bits` field which we have to remember for every CET.

Before we do anything, we need to determine if `n_bits` is simply an optimisation. Also, we may need to modify `maia` as part of this change.

_Originally posted by @luckysori in https://github.com/itchysats/itchysats/pull/1295#discussion_r797100686_

**Comment by bonomat** [comment]
This project is unmaintained
