### ISSUE TITLE
Make `Cet::to_tx` infallible to further optimize CET storage

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1303]
I am curious whether or not we can make this function infallible if we pass the outpoint in and make all fields private. Assuming you construct the struct correctly, the output of this function would be what you want. That could shave off the storage of the txid.

Let's explore this at some point.

_Originally posted by @thomaseizinger in https://github.com/itchysats/itchysats/pull/1295#discussion_r797106284_

Pre-condition for this: Figure out how we can safely make breaking changes to the event structure.

**Comment by bonomat** [comment]
This project is unmaintained
