### ISSUE TITLE
Close button is on different position on different CFDs

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#1306]
The button seems to change its position based on the UI state name:
![image](https://user-images.githubusercontent.com/8319440/152075365-a005d1c6-9b5d-4f4d-80e2-c9192739160f.png)

**Comment by da-kami** [comment]
This problem is related to the state changing in size. We could add a min-width to the tile that is enough accoring to the longest state name. 
Changing long state name labels into something shorter could also resolve this.

**Comment by bonomat** [comment]
Closing this for now. I don't think it's worth our efforts to move a button a few pixel down.
