### ISSUE TITLE
Re-think ADR005

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1313]
In [ADR005](https://github.com/itchysats/itchysats/blob/master/docs/adr/005-actors-for-protocols.md), we decided that containing protocols in an actor was a good idea.

We've since learned, that this causes several problems:

1. If this actor somehow stops, we are unable to change the state of the CFD. This was temporarily fixed in https://github.com/itchysats/itchysats/pull/1307 but that is certainly more of a band-aid than a proper fix.
2. We need to load the CFD and run a command against it multiple times within the life-time of such an actor. At the same time, we need to return multiple things from commands that are executed within those actors because we need to "carry on" with certain data, for example [`setup_params`](https://github.com/itchysats/itchysats/blob/28d6a8e4f1214867674ae0687129140d9bd0bcdc/daemon/src/setup_taker.rs#L73-L76).

Scope of this issue:

Draft up an ADR for re-designing these protocol executions, trying to address the above points. Some further questions to consider are:

- Should sending a message to the other party be an action that is performed by the process manager as a result of an event happening?
- Should we have multiple process managers (i.e. a `ContractSetupProcessManager`) that oversees the execution of such a process and handles things like timeouts?

**Comment by bonomat** [comment]
Closing this as not directly actionable.
