### ISSUE TITLE
Extension trait on Address for a delayed send

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1316]
This would generally be useful, but would especially help us with reducing code duplication in the protocol actors for setting up a contract, rollover and collaborative settlement. 

This is a follow up of sending the timeout message in https://github.com/itchysats/itchysats/pull/1307

**Comment by klochowicz** [comment]
@da-kami do you think there is still any need for this?

I suspect we can close this issue - if we decide we need it at a later stage, we can always reopen.
