### ISSUE TITLE
Re-introduce housekeeping to actually fail "failed" setups

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1317]
At the moment when restarting the daemon at an unfortunate point in time we can run into the problem, that we started a protocol (setup, rollover, collab settlement) but after the restart the actor that handled that protocol is gone, so it can happen that we never append an event that actually fails the protocol. This leads to awekward display and behavior in the UI.

We should have housekeeping again for both taker and maker and add an `xxxFailed` event if our last event is an event from where we can't continue (i.e. any protocol started).

Note that for the current collaborative settlement implementation this might be a bit tricky, because the maker *might* have actually published the settlement transaction. I would still add it to housekeeping - once the settlement transaction is picked up from the blockchain it will be transitioned to close.

**Comment by da-kami** [comment]
I think this is more critical than we think, because this does not only happen upon restart, but also if the maker becomes unavailable. We can run into bugs where we get "stuck" in Rollover and then cannot force close!
The CFD below is in state `Funding` forever until we are able to re-connect to a maker.

![image](https://user-images.githubusercontent.com/5557790/153530927-ababbcee-9a2e-43b9-b12b-46ea2eb8bafc.png)

**Comment by thomaseizinger** [comment]
I am going to draft an ADR for this.

**Comment by thomaseizinger** [comment]
> I am going to draft an ADR for this.

Here it is: https://github.com/itchysats/architecture/pull/7

**Comment by da-kami** [comment]
Closing until https://github.com/itchysats/itchysats/discussions/2128 has a conclusion.
