### ISSUE TITLE
Maker with a CFD they can't accept/reject

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#132]
After rejecting first offer and creating a new one which was meant to be accepted (to test the happy path), I discovered that I could not accept or reject the offer.

Maker log:

```

2021-09-24 10:27:38  INFO POST /api/order/sell application/json:
2021-09-24 10:28:02 DEBUG Taker wants to take an order taker_id=e53977ec-fb86-4e81-bd23-d1a45320153f quantity=101 order_id=15762b72-9644-4da7-80d4-ad62d56cc74b
2021-09-24 10:28:08  INFO POST /api/order/reject text/plain:
2021-09-24 10:28:08 DEBUG Maker rejects an order msg.order_id=15762b72-9644-4da7-80d4-ad62d56cc74b
2021-09-24 10:28:15  INFO BitMex quote updated bid=44638 ask=44638.5
2021-09-24 10:28:23  INFO POST /api/order/sell application/json:
2021-09-24 10:28:30 DEBUG Taker wants to take an order taker_id=e53977ec-fb86-4e81-bd23-d1a45320153f quantity=101 order_id=2438638b-8897-4f1c-ab25-50ae1443852d
2021-09-24 10:28:35  INFO POST /api/order/accept text/plain:
2021-09-24 10:28:35 DEBUG Maker accepts an order msg.order_id=2438638b-8897-4f1c-ab25-50ae1443852d
thread 'rocket-worker-thread' panicked at 'called `Result::unwrap()` on an `Err` value: no rows returned by a query that expected to return at least one row', daemon/src/maker_cfd_actor.rs:276:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'thread 'rocket-worker-threadrocket-worker-thread' panicked at '' panicked at 'all branches are disabled and there is no else branchall branches are disabled and there is no else branch', ', daemon/src/routes_maker.rsdaemon/src/routes_maker.rs::3232::55
```

After restarting the maker the faulty CFD is still stuck in the database and still crashes the maker when one of the buttons is clicked.

**Comment by bonomat** [comment]
I was able to reproduce this:

1. maker: create offer
2. taker: take
3. maker: reject
4. maker: create offer
5. taker: take
6. maker: accept

Maker has now 2 CFDs 
1. `CFD #0` "Requested" state
2. `CFD #1` "Accepted" state

Taker has 2 CFDs
1. `CFD #0` "Rejected" state
2. `CFD #1` "Contract setup" state

**Comment by bonomat** [comment]
Some more information: 
It looks like the taker is expecting a `Msg0` but received `Msg1`: 

```bash
thread 'rocket-worker-thread' panicked at 'called `Result::unwrap()` on an `Err` value: Msg1(Msg1 { commit: EcdsaAdaptorSignature(0346c418bbfe46dbf6e966d4473c3990ea0e09ebaece825be8c4ec63457e263df8021e330b857ea22bdcfa37bef2dfeb9208b6259d620b8ff6445b3e11411e2b030ef9359279c1b4b8a868d8df8bc80935b378a8962eaffe950cba3bd55b312e5036fab718dae2ba693d6264f83f9b4d50aedd0b77e2cd52941cd1542d0073ac51ae4f8374b26ced62e28814aa4f6a5bb10a49bffcf4340f9729c8e7345d3f64df2a), cets: [], refund: 304502210085257c3c8809ceafa608223f0b28c27d5db3d99b153782ba5b2193775a23d3190220486a0ff729fa0dfed2a33cf198e8e2b800baf0b0abbeea65249b89e225696bb3 })', daemon/src/setup_contract_actor.rs:51:71

```


I guess it's a race condition here: 

Maker side: 
- send msg0
- receive msg0
- send msg1

Taker side: 
- send msg0
- receive msg0

by the time taker wants to receive msg0, maker already sent msg1 and taker received the wrong message?

**Comment by thomaseizinger** [comment]
This might have to do with the buffering:

- msg0 comes in without the contract setup being active yet, we buffer msg0
- contract setup gets initialized, we send msg0 into the inbox
- the order of messages read from the stream is now msg1, then msg0

Not 100% sure how to solve this but fairly confident that this is the issue.

**Comment by da-kami** [comment]
Can confirm, that this not only happens for expected `Msg0` but received `Msg1` but can also happen for expected `Msg1` but received `Msg2`. Just got that as error.

Given that, does your theory still hold @thomaseizinger ? This is beyond the initial buffer...

Is awaiting a message enforced, or can it happen that the taker sends multiple messages before the maker starts?
(I thought it is enforced... i.e. after sending Msg0 the taker would wait to receive a message. before sending the next one..)

**Comment by thomaseizinger** [comment]
Interesting. IMO the way to fix this is to get rid of the entangled buffer in the actor and just create a dedicated actor. I was working on that yesterday already, not sure if I can get that in today.

**Comment by da-kami** [comment]
Hm... could the problem be that there are multiple messages returned by the receiver and we always get the latest one out?

**Comment by da-kami** [comment]
> Interesting. IMO the way to fix this is to get rid of the entangled buffer in the actor and just create a dedicated actor. I was working on that yesterday already, not sure if I can get that in today.

That's definitely a good way forward. the actor can just ensure the order of the messages I suppose.

**Comment by da-kami** [comment]
It's weird because the `UnboundedSender` buffers the values and from what the documentation says it shoudl come out in the order we expect, so if `Msg01` is sent and also `Msg2` we should get `Msg1` out first upon `recv()`

see: https://docs.rs/tokio/1.12.0/tokio/sync/mpsc/struct.UnboundedReceiver.html
This is very odd behaviour

**Comment by thomaseizinger** [comment]
I've ran several setups successfully now, I believe this bug report is stale.
