### ISSUE TITLE
The order of the CFD tiles display in the UI is not always ensured

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1328]
We added an `order by` when loading from the db at some point

https://github.com/itchysats/itchysats/blob/79fa34250b237f7b0971c29f39a508734a9646e1/daemon/src/db.rs#L267-L277

but that does not seem to be enough anymore with the recent changes of sending the cfds loaded by id async:

https://github.com/itchysats/itchysats/blob/eaad7c3bfaf3c28c7dda70ed53153c40aae3fef8/daemon/src/projection.rs#L731-L733

I think we have to ensure the sorting in the UI - but for that we need an indicator that allows sorting chronologically; i.e. we need to expose the CFD's opening timestamp.

**Comment by da-kami** [comment]
Note: Creation timestamp is actually hard, because we don't safe that in the database. Only the events have timestamps, but not the cfd itself. I think the cfd should also have a creation timestamp. We could add a column and default the value for existing cfds to current date of some past timestamp.

**Comment by da-kami** [comment]
We could mitigate this for now, by sorting by state in the UI, i.e. `Open` first and then `Pending Close` / `Force` (...) - that way at least new positions would end up at the top. At the moment it's quite random: 

![image](https://user-images.githubusercontent.com/5557790/152946857-cb39ca15-5ed3-4302-aa86-d78f7cc10df1.png)

Took me a while to spot my newly opened position...

**Comment by thomaseizinger** [comment]
> We could mitigate this for now, by sorting by state in the UI, i.e. Open first and then Pending Close / Force (...)

That is a fantastic idea! Lets remove the ordering in the DB and sort it in projection.

**Comment by bonomat** [comment]
If you sort by state the list might still be jumpy if you have multiple positions with the same state. 
You might want to additionally sort by `order_id`.

**Comment by thomaseizinger** [comment]
> You might want to additionally sort by `order_id`.

Within the state though right?

**Comment by bonomat** [comment]
> > You might want to additionally sort by `order_id`.
> 
> Within the state though right?

yes, not sequential sorting on the whole list 😅

**Comment by da-kami** [comment]
> If you sort by state the list might still be jumpy if you have multiple positions with the same state. You might want to additionally sort by `order_id`.

That's what we had initially (on the whole list) and it was super confusing, because sorting by UUID just does not make sense. It "solves" the problem of jumps, but I think we should really get the opening date into the database... It's not like that is super hard - we can also just default old ones. 

After another round of thought, I think we should just add the opening timestamp and default old CFDs to the timestamp of the first event (that would be the cleanest migration - can also be more blunt and just default it to some timestamp in the past).
On top of that we can still apply sorting them by certain states. I just wonder how that will feel. Like, you click close and then the CFD jumps down to the end of the open-list. I'll see to get the opening timestamp in, I think it can generally come in handy. I don't see any harm in storing this information.

**Comment by da-kami** [comment]
Additionally we could just use the first event timestamp for sorting. If no events then prepend the CFD to the front of the list.

But in the long run the easiest solution would probably still be: Add a creation timestamp to the `cfds` table. We can write a migration that defaults old ones to either the first event timestamp, or to some constant timestamp in the past. I wonder if it's not easier to just do that after some more thought.

**Comment by bonomat** [comment]
Adding a `creation_timestamp` seems to be generally useful 👍

**Comment by thomaseizinger** [comment]
> But in the long run the easiest solution would probably still be: Add a creation timestamp to the `cfds` table. We can write a migration that defaults old ones to either the first event timestamp, or to some constant timestamp in the past. I wonder if it's not easier to just do that after some more thought.

Yeah happy with that!

**Comment by thomaseizinger** [comment]
Algorithm to use:

- Default to `now` in projection CFD upon construction
- Override with the _first_ event that is passed to `apply`
