### ISSUE TITLE
Retrieve next price attestation event from oracle

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#133]
We should do something similar as with the BitMex's rate:

1. A loop that keeps refreshing it.
2. Store the result in a `watch` channel.
3. When making an offer, get the next event ID and put it in the offer.

**Comment by da-kami** [comment]
Should 1. be handled by the Oracle actor as well? 

I suppose we can implement this as: Oracle actor broadcasts new Oracle event (when known) and attested price.

**Comment by thomaseizinger** [comment]
I think for (1), we should do something similar as with the BitMex's rate:

1. A loop that keeps refreshing it.
2. Store the result in a `watch` channel.
3. When making an offer, get the next event ID and put it in the offer.

**Comment by thomaseizinger** [comment]
(2) is already defined in https://github.com/comit-network/hermes/issues/110.

**Comment by luckysori** [comment]
Looking at how `olivia` announces events ahead of time, and considering how it seems to create an event per minute of the day, is there really a need to constantly look for the "next" event? My question comes after looking at https://outcome.observer/h00.ooo/.

Wouldn't it be better to get the announcement which corresponds to a price attestation in `X` hours from `olivia` on demand?

**Comment by thomaseizinger** [comment]
> considering how it seems to create an event per minute of the day

I don't think this is true?

Someone, either us or @llfourn, will have to write a cronjob that feeds events into redis which are then picked up by Olivia. If I remember correctly, we agreed that there will be only one price event per 24h under the `/bitmex` scope (which does not exist yet).

**Comment by luckysori** [comment]
> I don't think this is true?

You could be right. I was just going off what's already there with `random` and `time`. But maybe for the price it will only be every 24h as you point out.

With that in mind, I suppose we can just assume that with the current time and knowledge of `olivia`'s price signing interval we can figure out the `id` of the next event and attempt to update the actor's internal `next_event` state in a loop.

**Comment by thomaseizinger** [comment]
This was done as part of https://github.com/comit-network/hermes/pull/145.
