### ISSUE TITLE
Expose initial prometheus metrics from binaries

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1331]
- Consider whether the metrics should be per actor (i.e. fields that are owned by an actor) or global static metrics
- Expose via HTTP endpoint (reuse rocket, don't open a 2nd port)

**Comment by bonomat** [comment]
> Consider whether the metrics should be per actor (i.e. fields that are owned by an actor) or global static metrics

I propose to introduce a `metric-actor` to keep the metric logic contained. 
Every other actor can then send events to this actor, e.g. : `position opened` event, and the metric actor knows how to track this.

**Comment by thomaseizinger** [comment]
> > Consider whether the metrics should be per actor (i.e. fields that are owned by an actor) or global static metrics
> 
> I propose to introduce a `metric-actor` to keep the metric logic contained. Every other actor can then send events to this actor, e.g. : `position opened` event, and the metric actor knows how to track this.

I am worried that this will introduce a lot of messages _just_ for the sake of collecting metrics. It is like having a `LoggingActor` that you send messages to for logging.

Do you see a downside of exposing static metrics on a _module_ level? I think we would just need to be careful to only track metrics that make sense on a global scale instead of doing something like "metrics per connection" which would be easier to reason about if the metrics were bound to the lifetime of an actor (and thus to the state that is tracked by the actor).

**Comment by thomaseizinger** [comment]
We would need to investigate if a global metric registry must be initialized for this work or whether or not these metrics would just not do anything then.

**Comment by thomaseizinger** [comment]
> We would need to investigate if a global metric registry must be initialized for this work or whether or not these metrics would just not do anything then.

We could eventually solve this with feature flags.

A problem I can see with static metrics is that if they require a registry to be present and we want to use this module (a specific actor) in a binary that doesn't have metrics, then this wouldn't work. Not saying that this will be the case any time soon but it is a good test of "when will this design break". In that circumstance, we can feature-flag the `prometheus` dependency and `cfg(feature = "prometheus")` all the metrics.

A 2nd problem with static metrics might be that we cannot as easily track actor-local state. However:

a) I don't think we will have that any time soon (like running two wallet actors and hence a global "Balance" metric would be ambiguous)
b) Even in the case of multiple actors, I think the proper way to record these metrics is the the `XyzVec` kinds, like [`GaugeVec`](https://docs.rs/prometheus/0.13.0/prometheus/type.GaugeVec.html) for a set of wallet balances with one _label_ representing one wallet.

Can you think of any other problems that static metrics might impose on us? I think it would be really beneficial if we don't have to introduce a lot of messages but can just record metrics right where stuff happens. Otherwise I can see this bloating our application code a lot.

**Comment by thomaseizinger** [comment]
In regards to the scope of this issue, I think we can consider this done by implementing some of the scaffholding and start with a few simple metrics like:

- Wallet balance
- Number of connected takers

We can then in future iterations port all the existing metrics over into this application.

**Comment by thomaseizinger** [comment]
> Consider whether the metrics should be per actor (i.e. fields that are owned by an actor) or global static metrics

I think the decision we have to make here might warrant writing up an ADR. 

@bonomat Are you interested in drafting one, summing up the situation or do you want me to do it?
