### ISSUE TITLE
Can't settle - because maker automation does not react

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1349]
Previously we reported https://github.com/itchysats/itchysats/issues/1298 the problem where we can't settle 
I am still running into this problem with the taker running `0.4.0` - I will see to upgrade my Umbrel taker to `0.4.1` manually to be able to better 

I am quite certain that the issue I encountered was not related to an outdated price. 

Behaviour: 

1. I wanted to close a position on the taker (the taker had been running without restart for quite a while)
2. I clicked close
3. It showed `Closing`, but after about 30 secs it would jump back to `Open` - Closing ran into an error.
4. The taker acted sane, it sent out the request as expected.
5. I am not totally sure the maker received the request (see ad below)
6. After trying a few I restarted the maker. But the problem persisted (same behavior)
7. After the maker was restarted the taker did not receive offers 
7. I checked on the automation and saw some errors there
8. I restarted the automation and the automation would pick up a bunch of my previous requests upon restart and reject / fail them (because they were outdated)
9. I tried again and this time it worked, the CFD got settled. I could see the settlement in the automation logs.

ad. 4: Occasionally I ran into `Latest quote is older than 1 minute. Refusing to settle with old price` - but after retrying it would work eventually and the request would go through. 
ad.5: I tried to filter for the `order_id` in the logs, but somehow I was unable to achieve it. Filtering for `taker_id` worked, but it would not show me all logs. I only saw very few logs that did not make sense. Here's the filter I used: `{container="maker",setup="mainnet"} | json  | fields_taker_id="87785a1289d567417a590105b8920cb3feffc3928d976cf2425eb10cd7bc7879"`
ad.7 I restarted the taker *again* after that to make sure the problem was on the maker side, and it was

Taker logs of timeout:

```
2022-02-04 22:29:03  WARN daemon::model::cfd: Collaborative close failed: Maker did not respond within 30 seconds order_id=08cf9246-8a84-4066-bcd8-153803be5467
2022-02-04 22:29:03 TRACE daemon::db: Appending event to database event=CollaborativeSettlementFailed order_id=08cf9246-8a84-4066-bcd8-153803be5467
```

Automation errors (I think after the restart of the maker, but not entirely sure):

```
{"timestamp":"2022-02-05 09:23:28","level":"ERROR","fields":{"message":"Could not connect to ItchySats maker due to transport error: retry in 5s. request or response body error: error reading a body from connection: unexpected EOF during chunk size line"}}
{"timestamp":"2022-02-05 09:23:33","level":"ERROR","fields":{"message":"invalid type: null, expected f64 at line 1 column 300"}}
{"timestamp":"2022-02-05 09:23:33","level":"ERROR","fields":{"message":"invalid type: null, expected f64 at line 1 column 300"}}
{"timestamp":"2022-02-05 09:23:33","level":"ERROR","fields":{"message":"invalid type: null, expected f64 at line 1 column 300"}}
{"timestamp":"2022-02-05 09:23:34","level":"ERROR","fields":{"message":"invalid type: null, expected f64 at line 1 column 300"}}
{"timestamp":"2022-02-05 09:23:34","level":"ERROR","fields":{"message":"invalid type: null, expected f64 at line 1 column 300"}}
{"timestamp":"2022-02-05 09:23:35","level":"ERROR","fields":{"message":"invalid type: null, expected f64 at line 1 column 300"}}
{"timestamp":"2022-02-05 09:23:35","level":"ERROR","fields":{"message":"invalid type: null, expected f64 at line 1 column 1105"}}
{"timestamp":"2022-02-05 09:23:36","level":"ERROR","fields":{"message":"invalid type: null, expected f64 at line 1 column 1105"}}
```

Automation logs picking up my previous attempts and failing them:

```
{"timestamp":"2022-02-05 09:38:45","level":"INFO","fields":{"message":"Connecting to maker feed"}}
{"timestamp":"2022-02-05 09:38:45","level":"INFO","fields":{"message":"Settlement proposal not acceptable. Rejecting. \"No recent price information present\"","order_id":"08cf9246-8a84-4066-bcd8-153803be5467","counterparty":"87785a1289d567417a590105b8920cb3feffc3928d976cf2425eb10cd7bc7879"}}
{"timestamp":"2022-02-05 09:38:45","level":"INFO","fields":{"message":"Settlement proposal not acceptable. Rejecting. \"No recent price information present\"","order_id":"08cf9246-8a84-4066-bcd8-153803be5467","counterparty":"87785a1289d567417a590105b8920cb3feffc3928d976cf2425eb10cd7bc7879"}}
{"timestamp":"2022-02-05 09:38:45","level":"ERROR","fields":{"message":"Could not post action: {\"status\":500,\"title\":\"rejectSettlement failed\",\"detail\":\"Reject failed: No settlement in progress for order 08cf9246-8a84-4066-bcd8-153803be5467\"}"}}
```

**Comment by thomaseizinger** [comment]
Closing because outdated.
