### ISSUE TITLE
ItchySats `0.4.1` "got stuck" after startup

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1351]
Behavior:

* Start the daemon after upgrading
* The usser interface is reachable everything seems fine
* Run into the `Not connected to daemon` error in the UI. The wallet balance goes to `0`
* Refresh does not help.
* Check the logs, the logs are stale, no new logs are printed anymore (for more then a minute); unfortunately don't have the logs, but there were no errors or warnings. The last message I saw was the one saying that the `Heartbeat pulse measurements fell behind more than heartbeat interval (10), likely missing a heartbeat from the maker. Diff between pulses: 10` - but we see that one quite often at the moment, so not sure if that is relevant
* Restarted daemon and did not run into issues

Might have been a glitch with Electrum not being available (yet). My guess goes to Electrum because the wallet balance was `0`. Not sure we can make that a better experience? 
The fact that we did not see any more log messages points more towards a deadlock somewhere, hard to say. I thought I'll report it and see if I can ever reproduce it.

I don't think this should be related to the changes between `0.4.0` and `0.4.1`.

**Comment by thomaseizinger** [comment]
Closing because this version is no longer running in production.
