### ISSUE TITLE
Payout calculation can underflow on negative funding rate

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1353]
This can underflow if the rate is negative which can cause being unable to calc payout:

https://github.com/itchysats/itchysats/blob/c6ae9dd69f824a4b1beb82b264a308df2567f330/daemon/src/payout_curve.rs#L115

We should fix this before using negative funding rates

**Comment by luckysori** [comment]
@da-kami: Was this what we fixed with https://github.com/itchysats/itchysats/pull/1454?

**Comment by luckysori** [comment]
This code changed with #1454.
