### ISSUE TITLE
Don't commit if already in settlement

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1355]
We should prevent the publishing of a commit transaction if there is already a settlement ongoing. 

At the moment, the mempool takes care that this does: these two transactions are competing and  only one can be included at a time in the mempool. Since we pay the same fee, the minors don't prefer one over the other. 

If we were, a commit transaction could RBF (replace by fee) a settlement transaction. 

Which, imho, we should prevent.

**Comment by da-kami** [comment]
This is related to the general problem, that we don't treat *having* a collaborative settlement transaction as closed already. This was similar to rollover where I added having the transaction to the condition for not allowing a rollover.

I think we should just extend `is_final` to treat having a collab settlement transaction as final.
