### ISSUE TITLE
Taker to initiate CFD rollover

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#136]
The taker should be able to say that he wants to roll over the contract for another iterations. 

The maker should only accept this if the taker should not have gotten liquidated already.

Proposal: 
Initially we can make this a manual step, e.g. the user has to click a button to say: `roll over`. Eventually I'd see this as an automated action. Whenever the user comes online, he rolls over to the next iteration.

**Comment by thomaseizinger** [comment]
Moved your issue to the other epic, `ready-to-play` primarily concerns itself with infrastructure tasks (see description).
