### ISSUE TITLE
2nd connection warnings

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1360]
We get heaps of warnings that takers are trying to connect twice: 

e.g. 

```
{"message":"Refusing to accept 2nd connection from already connected taker d528d61e4265cc0f1dcf93f73aa3c9f45789612912de74444e4be4f1e660081d!"}
```

We should look into this if this is expected.

**Comment by thomaseizinger** [comment]
I think this might be a bug of some sorts.

**Comment by bonomat** [comment]
Still happening regularly on latest mainnet release

**Comment by thomaseizinger** [comment]
Possible way of fixing this: Drop the old connection in favor of the new one. Need to think about the consequences of this!

**Comment by klochowicz** [comment]
> Possible way of fixing this: Drop the old connection in favor of the new one. Need to think about the consequences of this!

I'd be in favour of this - recent mainnet maker logs show that there are some takers in this unfortunate position for long periods of time. This causes grief for the users (and causes lots of warnings in the logs)

**Comment by thomaseizinger** [comment]
> > Possible way of fixing this: Drop the old connection in favor of the new one. Need to think about the consequences of this!
> 
> I'd be in favour of this - recent mainnet maker logs show that there are some takers in this unfortunate position for long periods of time. This causes grief for the users (and causes lots of warnings in the logs)

We have to be careful with this. If there are actually two clients with the same ID (because the user synced the seed file or something), this will result in a constant connection bounce between the two.

**Comment by thomaseizinger** [comment]
Can we get some data on how many clients this is happening to?

**Comment by klochowicz** [comment]
> Can we get some data on how many clients this is happening to?

I think it was around 5-6 yesterday within 24h last time I checked.

**Comment by klochowicz** [comment]
> > > Possible way of fixing this: Drop the old connection in favor of the new one. Need to think about the consequences of this!
> > 
> > 
> > I'd be in favour of this - recent mainnet maker logs show that there are some takers in this unfortunate position for long periods of time. This causes grief for the users (and causes lots of warnings in the logs)
> 
> We have to be careful with this. If there are actually two clients with the same ID (because the user synced the seed file or something), this will result in a constant connection bounce between the two.

we could allow them both at the same time actually, it's arbitrary that we only use the taker-id there. we could e.g. use a tuple `(TakerId, index)`

**Comment by bonomat** [comment]
Oldie but goldie... we are still seeing this :/ I'm closing this now as this is hopefully resolved using libp2p
