### ISSUE TITLE
The locking fee should be on top of the margins locked up

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1362]
When we create lock, the transaction fee for lock should be on top of the margin, i.e. once locked up the complete amount should be locked up as `margin_taker + margin_maker + fee`. At the moment it is just `margin_taker + margin_maker` which means that we effectively don't use the complete margin for calc because it's always minus the transaction fee.  

Note that this change will have to be pulled through to the UI where we should add the transaction fee to the opening fees.

**Comment by da-kami** [comment]
After discussion what this ticket describes might actually not be true, because fees are only paid when spending from lock. Needs more investigation.

**Comment by thomaseizinger** [comment]
Fees are paid from initial inputs and not from the margin so this is a non-issue.
