### ISSUE TITLE
Ensure `bors.toml` does not get stale

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1378]
With https://github.com/itchysats/itchysats/pull/1335, we ensure that we are testing every crate in our workspace in a different job. This improves CI runtime and coverage but also makes it possible that `bors.toml` gets stale and `bors` is not waiting for a positive result of a certain check.

We should automate that we cannot run into this.

**Comment by bonomat** [comment]
Let's be conscious about what we do instead of automating everything.
