### ISSUE TITLE
Make sure the taker actually reconnects and does not get stuck in reconnecting

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1401]
1. Taker Hotfix on top of 0.4.2  
	1. Add timeouts to all statements related to establishing the connection
	1. Add unit test to test things
	1. Introduce some randomness so that not all takers re-connect at exactly the same point in time

**Comment by klochowicz** [comment]
Unfortunately, unit tests have proven to be extremely hard to write - I have not been able to reproduce the failure.
