### ISSUE TITLE
If `closing_price > 2  * opening_price` no CETs are unlocked

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#1402]
Our payout curve only generates payouts between 0 and `2 * opening_price`. This means that if Olivia attests to `closing_price > 2 * opening_price` no CETs are unlocked for that particular CFD. We want to be able to support these rare instances where the price more than doubles.

To fix this we should, extend the highest range of the payout curve up to the maximum price that Olivia can attest to.

**Comment by bonomat** [comment]
@luckysori : this was fixed right?

**Comment by luckysori** [comment]
Done with https://github.com/itchysats/itchysats/pull/2862.
