### ISSUE TITLE
Make it cheaper to load closed CFDs from the database

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1404]
As a follow up of https://github.com/itchysats/itchysats/issues/1317 we could think about adding an event to CFDs that already have a spend transaction (i.e. are closed) so we can make it cheaper to load them from the database.

At the moment e.g. handling the attestation is quite a bottleneck because we load *all* CFDs with all events (including all rollovers) which is super expensive. 

By adding a dedicated event that markes the CFD as closed and only provides the information necessary we can treat closed CFDs differently and make it a lot cheaper to load them.

This should solve parts of the issue of consuming a lot of CPU power at startup as described here https://github.com/itchysats/itchysats/issues/1399

**Comment by thomaseizinger** [comment]
> By adding a dedicated event that markes the CFD as closed and only provides the information necessary we can treat closed CFDs differently and make it a lot cheaper to load them.

There are two options here:

1. Record a dedicated closed snapshot event and store a pointer to that event in the CFD. This preserves the event history of a CFD.
2. Record a dedicated closed snapshot event and delete all prior events of the CFD. This saves some storage as well.

I am leaning towards solution (1) for now. The event history might be useful for some debugging and actually pruning these events is quite a big change architecturally so I'd like to be careful with that.

**Comment by thomaseizinger** [comment]
Closing favor of https://github.com/itchysats/itchysats/issues/1651.
