### ISSUE TITLE
Serving frontend via rocket in releases is broken

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#143]
For some reason, the serving the frontend via rocket is broken.

Happens for release and debug builds (i.e. it has nothing to do with the actual embedding)

**Comment by klochowicz** [comment]
Tried it out with the recent 'preview' builds - I get error 400 on the maker, 404 on the taker. Can confirm it's broken.

**Comment by klochowicz** [comment]
After doing `APP={maker,taker] yarn build` in the frontend directory, and building a release version of the binaries, I was able to successfully see the served frontend on both sides

**Comment by bonomat** [comment]
I also checked the preview binaries for MacOS which are working. 
Since all binaries are built the same I would assume for the other platforms it works as well.

**Comment by thomaseizinger** [comment]
Can confirm, works for me as well now.

Not sure what exactly was broken :upside_down_face:
