### ISSUE TITLE
Ideas for splitting crates further

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1443]
- Move maker/taker stuff into their respective crates (https://github.com/itchysats/itchysats/pull/1337)
- Extract the `State` bit of `monitor.rs` into a dedicated crate (this part is xtra-indepedent, can be tested in isolation and might be useful otherwise)
- `setup_contract` if we make it actor/xtra independent. Perhaps by doing https://github.com/itchysats/itchysats/issues/698?

**Comment by bonomat** [comment]
Closing this as not directly actionable.
