### ISSUE TITLE
Create a composable `Address::send` API that is misuse resistant

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1469]
With more usage of actors, we learned the following things:

- Asynchronously sending a message where the handler returns `Result` is dangerous: It drops the return value, which could potentially be an error.
- Sending synchronous messages between actors can cause deadlocks
- Sending messages without a timeout can halt entire actors and eventually the entire system

We worked around some of these issues with extension traits to `Address`. It is time to design a more holistic solution for these problems. To avoid an explosion in APIs on `Address`, we need a composable API for sending a message. In particular, we want:

- Good defaults (esp. for timeouts)
- Misuse resistant: f.e. don't allow async sending of messages that return a `Result` without handling it
- Concise: Sending a message shouldn't require any more "chained" API calls than necessary

To achieve the above, we will need some form of builder pattern to combine the various requirements. The builder will likely utilise the type system to make it impossible to compose bad requirements.

**Comment by thomaseizinger** [comment]
Assigning @luckysori and @klochowicz because I think you would be a good fit for this problem.

**Comment by luckysori** [comment]
@thomaseizinger: How relevant is this issue after the new network layer is introduced?

**Comment by bonomat** [comment]
Sounds old to me. Please reopen and update description if still needed.
