### ISSUE TITLE
UTXO management strategy

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1473]
Related to #1467 and #1134

This error message keeps happening: 

```
{"message":"Contract setup failed: Failed to build party params: InsufficientFunds { needed: 518211, available: 291747 }"}
```

We need a UTXO management strategy

**Comment by bonomat** [comment]
I'm not sure anymore we need a UTXO management strategy. 
Maybe we should not allow to parallelize CFD creation, that way we should be able to guarantee that have utxos available.

**Comment by thomaseizinger** [comment]
I think we can also manually tell BDK about our new UTXOs, directly after signing and thus be quicker and avoid the wait for the sync?

**Comment by bonomat** [comment]
Do you mean something like this? 

1. start CFD setup 1: starts and gets UTXO, creates new change UTXO
2. tell wallet about change UTXO
3. start CFD setup 2: starts and gets UTXO, creates new change UTXO
4. tell wallet about change UTXO
5. setup 1 finishes and publishes tx lock
6. setup 2 finishes and publishes tx lock

A problem is if setup 1 fails, setup 2 will also fail because the change UTXO does not exist. 

I think best if if we can delay step 2 as long as possible to have high certainty that the setup was successful.

**Comment by thomaseizinger** [comment]
Yes that was the idea.

It shouldn't fail though and if it does, we should fix the bugs around it.

Sequencing the setups is another band-aid solution that hurts user experience. I'd rather explore the others first, including requiring enough UTXOs to be present.

Number of UTXOs is probably also a metric we should monitor.

**Comment by bonomat** [comment]
I don't think this is a bug. Closing for now until we decide we need this.
