### ISSUE TITLE
Transition maker/taker to long/short where possible

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1482]
Requires https://github.com/comit-network/maia/issues/16.

**Comment by luckysori** [comment]
Imo, Blocked on figuring out how to make changes to our CFD events.

**Comment by bonomat** [comment]
@luckysori : is this still relevant?

**Comment by luckysori** [comment]
Definitely still the case that we have places where we would prefer to talk about long/short instead of maker/taker.

**Comment by bonomat** [comment]
This project is unmaintained
