### ISSUE TITLE
Fix release workflow to bump version of crates correctly

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1488]
The "draft new release" workflow bumps the version of the wrong crate since after the crate split: https://github.com/itchysats/itchysats/blob/a6f858e496ee7385092d7896ab86efb769f781fc/.github/workflows/draft-new-release.yml#L32-L36

This needs to be changed to `maker` & `taker`.

**Comment by da-kami** [comment]
Would `daemon` then not be versioned at all?

**Comment by thomaseizinger** [comment]
> Would `daemon` then not be versioned at all?

Yes, doesn't need to because it is a library crate and we are not publishing it.
