### ISSUE TITLE
Tag docker container of latest release with `latest`

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1489]
Currently, we only tag released docker containers with their corresponding tag.

It would be good to have some automation that automatically tags the latest release with `latest`. The tricky part here is that I think we should define `latest` as the greatest version number, i.e. if there are two versions `0.5.0` and `0.4.4`, `0.5.0` would be latest.

Now, there might very well be circumstances in which we publish `0.4.4` AFTER `0.5.` and in that case, `latest` should not get updated. This is the reason why I did not do this as part of https://github.com/itchysats/itchysats/pull/766.

**Comment by da-kami** [comment]
At the moment we use `latest` for the preview release. If we change this we will have to use a different tag (initially we used `preview`) and update any automation that deploys `preview`.

**Comment by klochowicz** [comment]
@thomaseizinger perhaps for the really unusual events like releasing 0.4.x after 0.5.x we could manually overwrite the tag? they should not happen often, in fact they might as well not happen at all!

**Comment by thomaseizinger** [comment]
> At the moment we use `latest` for the preview release. If we change this we will have to use a different tag (initially we used `preview`) and update any automation that deploys `preview`.

No, that is not true. See PR https://github.com/itchysats/itchysats/pull/766.

**Comment by thomaseizinger** [comment]
> @thomaseizinger perhaps for the really unusual events like releasing 0.4.x after 0.5.x we could manually overwrite the tag? they should not happen often, in fact they might as well not happen at all!

Could be yes. We just need to be aware of that which is a really nasty thing to remember.

**Comment by bonomat** [comment]
This project is unmaintained
