### ISSUE TITLE
Initial balance `0` after starting setup after longer time

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1510]
I waited for quite a while until I transferred funds. 
After transferring funds it picked up the complete balance.

I think this goes back to how many addresses we check back. But that was a temporary fix. I think we should really get the managed wallet back.

**Comment by thomaseizinger** [comment]
That bug originates in BDK and needs to be fixed there.

Although I guess we can assume that users never delete their DB and as such it would be fixed by a persistent DB.

**Comment by bonomat** [comment]
Duplicate of #1538
