### ISSUE TITLE
Cleanup and harmonize contract setup protocol error handling

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1517]
When working on https://github.com/itchysats/itchysats/pull/1515 we noticed that contract setup protocol does not handle all error pathes within the protocol actor, but some errors are passed out of the actor back to the connection. 

This means we might not add a `Failed` event, we might not even stop the contract setup actor, but just keep it running forever (which is basically a memory leak).

Cleanup:

1. contract setup handlers should not be fallible, but error should be handled within the actor.
2. once contract setup handler was cleaned up: evaluate if `address_map::send_fallible` is still used and necessary.

**Comment by bonomat** [comment]
This project is unmaintained
