### ISSUE TITLE
Actually send leverage choices to the taker

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1573]
Hardcode them to only allow "2" for now.

The point of this task is to prepare the underlying infrastructure for configurable leverage.

**Comment by klochowicz** [comment]
pending decision: is there any use-case for having *different* set of allowed leverages for long and short orders? cc @bonomat @da-kami

**Comment by bonomat** [comment]
yes, I think it would make sense to account for it: 
 
-From the taker perspective: if the price drops hard it would make sense to go high leverage short to make more profit
-From the maker perspective: if the price looks like it will drop hard, offer low leverage to short but high leverage for long as this is low risk for him
