### ISSUE TITLE
Consider writing a native-async electrum RPC client

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1593]
We use `electrum_client` in two places:

1. As our bdk backend
2. As the client for implementing our monitoring

We can't do much about the bdk part because that is super involved but for our monitoring, we only use 3 RPC calls:

- `blockchain.headers.subscribe`
- `blockchain.scripthash.get_history`
- `blockchain.transaction.get`

Investigate whether we can replace the usage of `electrum_client` with a handrolled client. Evaluate if https://github.com/thomaseizinger/rust-jsonrpc-client is of any use here.

**Comment by thomaseizinger** [comment]
The `electrum_client` is problematic because:

1. It is blocking and our entire application is built on top of `async`.
2. We regularly see errors in the logs saying something like:

```
call 'block_headers_subscribe_raw' failed with EOF while parsing a value at line 1 column 0, retry: 1/1
```
or
```
got error for req_id 1863855: JSON(Error("EOF while parsing a value", line: 1, column: 0))
```

**Comment by bonomat** [comment]
This project is unmaintained
