### ISSUE TITLE
Design new network layer based on top of `libp2p-xtra`

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1595]
With the introduction of libp2p-xtra, we need to remodel our network communication by introducing protocols. This issue aims to collect a high-level view of what is going to be affected by this change.

---

- ~Commandline interface is going to change. The connection details are now a multi-address.~
- We will need to derive a `libp2p::Keypair` from our seed.
- Chuck out `maker_inc_connections::Actor`
	- We will need to re-introduce the `p2p_connections_total` metric
- Chuck out the `connection::Actor`
	- We will need to find an alternative way of implementing the "always maintain a connection"-policy. `libp2p-xtra` purposely does not expose when connections get established / dropped. Instead, it is recommended to observe the `ConnectionsStats` by querying the `Node` in an interval.

All of the above tracked in: https://github.com/itchysats/itchysats/issues/1766

---

- Design a protocol for sending out offers. Got a choice between:
	- _pushing_ offers to consumers by opening substreams from maker->taker
	- _polling_ offers from the maker by opening a substream from taker->maker

Design proposal for one-shot push-based protocol here: https://github.com/itchysats/itchysats/issues/1768

---

- Design a protocol for taking an offer. Likely, this will directly lead over to the contract-setup messages by reusing the same substream. Otherwise, we would have to keep external state and work out, who opens the substream for doing the contract-setup. That is likely very clunky at no immediate benefit.

Design proposal for placing an order here: https://github.com/itchysats/itchysats/issues/1770

---

- Design a protocol for triggering a rollover. Need to evaluate whether it is worth to tackle https://github.com/itchysats/architecture/issues/17 first. https://github.com/itchysats/architecture/issues/17 would remove the "waiting for the decision" state from the rollover actors which - I think - will allow us to design an overall simpler protocol that can be executed as a single future (e.g. "receive rollover request -> make decision -> do rollover -> emit event" could all be a single future). This would essentially be an alternative solution to what is outlined in https://github.com/itchysats/itchysats/issues/1313 by getting rid of these actors altogether.

Design proposal here: https://github.com/itchysats/itchysats/issues/1775

---

- Design a protocol for collab. settlement. Basically the same as for rollover applies. Additionally, collab. settlement is not symmetric which is something we considered changing for a while. See https://github.com/itchysats/itchysats/issues/320.

Design proposal here: https://github.com/itchysats/itchysats/issues/320#issuecomment-1088344881

---

- Evaluate what happens to the heartbeats. A single substream (i.e. the one for a hypothetical heartbeat protocol) dying does not mean that the entire connection is dead. We have to carefully evaluate, if we still need a heartbeat and how it interacts with the rest of the application. Could consider implementing something like libp2p's ping protocol.

Proposal to switch to `libp2p-ping` here: https://github.com/itchysats/itchysats/issues/1767

---

- `Hello` and the network version are very likely gonna go away.

Design proposal for `/itchysats/identify` here: https://github.com/itchysats/itchysats/issues/1769

---

- We recently introduced a prometheus counter for logging all messages. That is no longer as easy with multiplexing. Need to evaluate how to deal with this, i.e. do we need to retain this functionality or is it f.e. good enough to only have a counter for specific protocols (like sent offers) and each protocol has to reimplement this metric if they want it.

Last but not least:

- Figure out a way of doing all of the above in an iterative fashion and not as a big bang. It may be worth opening two network connections for a while and porting protocols over piece by piece.

## Annoyance counter

- 01/04/2022: Closed https://github.com/itchysats/itchysats/issues/1361 in favor of this one.

**Comment by luckysori** [comment]
This one we definitely did!
