### ISSUE TITLE
Rethink naming and logic of `Short Price` vs `Long Price`

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1596]
I find our current naming and logic around `Short Price` and `Long Price` throughout the code base confusing. 
This needs to be improved.

## Annoyance counter

- 10/03/2022: Reviewing the PR #1594 and thinking through the behavior is not easy
- 22/03/2022: Spent 1.5 days on discussing this terminology

**Comment by klochowicz** [comment]
To kickstart the discussion, let my original reasoning how I came about with the names:

When creating parameters of offers, you specify:
- at what price I am willing to go short (`Short Price`)
- at what price I am willing to go long (`Long Price`)

Note: the same problem concerns the two funding rates.

**Comment by thomaseizinger** [comment]
For the prices, "bid' and "ask" might be more appropriate?

**Comment by thomaseizinger** [comment]
> * 22/03/2022: Spent 1.5 days on discussing this terminology

@bonomat You need to also increment the custom field if you add an entry, otherwise it is hard to filter in the project view. Done it for you now :)

**Comment by bonomat** [comment]
Closing in favor of https://github.com/itchysats/itchysats/issues/2786
