### ISSUE TITLE
Red colour for "short" is problematic

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#1598]
Every time I'm trying to go short I pause and reconsider my options because of the red colour of the button (which can be understood as "wrong").

I would strongly suggest using something different:

1. Use the same colour
2. Use a different shade of green or blue (neutral)
3. Pick two different colours (green is also used as "profit" in our app). Two different shades of blue could do the trick nicely.

_Originally posted by @klochowicz in https://github.com/itchysats/itchysats/discussions/1597_

**Comment by thomaseizinger** [comment]
Closing in favor of the discussion.
