### ISSUE TITLE
Deprecate `GET /api/takers` in favor of prometheus metric `p2p_connections_total`

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1609]
This issue documents that we are deprecating the `GET /api/takers` endpoint.

There is no replacement for fetching all connected takers but there is a prometheus metric `p2p_connections_total` exposed under the `GET /api/metrics` endpoint for fetching the total connection count.

We are documenting this here so we have a canonical source to point to for deprecation notices.

**Comment by luckysori** [comment]
@klochowicz: This was removed, right? I can't find the endpoint in the codebase.
