### ISSUE TITLE
Combined position

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1615]
Detailed explanation to be filled in.

## Annoyance counter

- 11/03/2022: Not having a combined position requires us to maintain and extend the collaborative settlement protocol (https://github.com/itchysats/itchysats/issues/1608#issuecomment-1065045565). A protocol which would not exist with a combined position because "closing" is simply a special case where you end up omitting the DLC output and pay out all coins in the previous DLC.

**Comment by bonomat** [comment]
This project is unmaintained
