### ISSUE TITLE
Deal with rust-secp256k1-zkp 

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1616]
There is a pending PR which currently does not build: https://github.com/ElementsProject/rust-secp256k1-zkp/pull/43

We will need it in the near future because bdk will update to the latest version

**Comment by thomaseizinger** [comment]
There is progress on this in https://github.com/ElementsProject/rust-secp256k1-zkp/pull/46.

**Comment by thomaseizinger** [comment]
There is a new release now: https://crates.io/crates/secp256k1-zkp/versions

Next steps:

- Update `maia`: https://github.com/comit-network/maia/pull/26
- Use new `maia` in `itchysats`

**Comment by klochowicz** [comment]
we are still blocked on bdk with this (until they release v0.19)

**Comment by bonomat** [comment]
I think this was dealt with already
