### ISSUE TITLE
Make `ProposeRollover` more explicit

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1622]
When rolling over both parties need to know from where they are rollingover from and to when/what they are rollingover to. If one of the values is different, the rollover might fail at a very late step e.g. when verifying the signatures. 

Right now, these values are assumed, i.e. both parties think they will rollover for another 24h, from the "last successful" rollover, handle their own feeAccount and subtract the feeAmounts, etc. 

We should make the `ProposeRollover` message more explicit in regards to where do we rollover from and until do we rollover to. That way we can ensure that both parties are talking about the same thing before starting with the actual protocol. 

Differently said, we (either party) should tell the other party the params they are going to use for the rollover. 

More discussion on this topic: https://github.com/itchysats/itchysats/discussions/1726

## Annoyance counter

- 01/04/2022: Rollover not being explicit leads to several rollover failures which leads to unintended publication of old states which triggers unimplemented revoke behaviour. This came up in https://github.com/itchysats/itchysats/pull/1715.
- 01/04/2022: Closed https://github.com/itchysats/itchysats/issues/1039 in favor of this one.
- 01/04/2022: Closed https://github.com/itchysats/itchysats/issues/1617 in favor of this one.

**Comment by thomaseizinger** [comment]
This sounds like a good idea overall but it also highlights, how little design and thought went into the current rollover protocol. It would be good to push https://github.com/itchysats/architecture/pull/8 forward and fix these problems in a more structured way.
