### ISSUE TITLE
Re-design CLI interfaces to be more docker friendly

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1630]
Currently, the CLI assumes that it is safe to rely on the filesystem for permanent storage of secret material.

This motivated the use of a seed file as the single source for secret material like identity keys or authentication passwords.

With docker being the primary deployment platform, this choice is sub-optimal because the filesystem within docker is transient by default. Additionally, the seed file being the single source for secret material has other issues as pointed out by @bonomat in https://github.com/itchysats/itchysats/issues/1161#issuecomment-1018347324.

The task of this issue is to re-design the CLI interface to be more docker friendly and allow for individual control over the various secrets. Evaluate the relevance of design guidelines like https://smallstep.com/blog/command-line-secrets/.

**Comment by bonomat** [comment]
Closing this for now as it's not on our near term roadmap
