### ISSUE TITLE
Actor has been processing message for x seconds

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1635]
We keep seeing this warning in the logs: 

```
Actor daemon::oracle::Actor has been processing message daemon::oracle::NewAttestationFetched for 10 seconds
```

ranging from 10 to 50 seconds

**Comment by thomaseizinger** [comment]
Note: https://github.com/itchysats/itchysats/pull/1607 is still waiting for reviews which would give as better data on this.

**Comment by thomaseizinger** [comment]
As long as the handler finishes eventually, it is not a massive problem though.

**Comment by thomaseizinger** [comment]
Closing because these logs have been replaced with prometheus metrics.
