### ISSUE TITLE
Scenario where the taker gets stuck reconnecting

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1669]
We had trouble with that in the past. 
This is a scenario where the taker `0.4.7` of the testnet setup was unable to reconnect to the maker. 
(Initially the maker was not compatible, but eventually it was - the taker had been trying to reconnect for days)

These logs kept being printed repeatedly:

```
{"timestamp":"2022-03-23T02:19:37.367759023Z","level":"WARN","fields":{"message":"Failed to establish connection: Failed to connect to 172.19.0.7:9999: Connection refused (os error 111)","address":"172.19.0.7:9999"},"target":"daemon::connection"}
{"timestamp":"2022-03-23T02:19:37.36784234Z","level":"WARN","fields":{"message":"Tried connecting to 1 addresses without success, retrying in 39 seconds"},"target":"daemon::connection"}

```

I would not give this bug priority, but we should be aware that in some scenarios the taker still gets stuck when reconnecting and that could also be a problem on master.

**Comment by thomaseizinger** [comment]
I am investigating this at the moment. A restart of the taker seems to have fixed it for now, monitoring now.

**Comment by bonomat** [comment]
Closing this for now . We know that our connection is suboptimal. Leaving https://github.com/itchysats/itchysats/issues/2354 as a replacement for it.
