### ISSUE TITLE
Funding rate might confuse people

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1692]
The way how funding rate is depicted at the moment might be confusing. 
I know that a positive funding rate means, long pays short but this is not really visible nor described anywhere. 
Right now, it looks like that both, longs and shorts will need to pay this rate: 

![image](https://user-images.githubusercontent.com/224613/160261374-e674a076-a49a-485a-a049-e149e22c0993.png)

![image](https://user-images.githubusercontent.com/224613/160261378-f118b0a8-89fc-4d11-be90-f19b85368a6a.png)

**Comment by klochowicz** [comment]
isn't this the case in the above pictures that both long and short need to pay, ie. it's not a negative funding rate? (just double-checking as the rates are quite different in long and short tab)

**Comment by bonomat** [comment]
> isn't this the case in the above pictures that both long and short need to pay, ie. it's not a negative funding rate? (just double-checking as the rates are quite different in long and short tab)

mhm... good that it even confuses us 😅 Imho it means: positive means long pay, negative means short pay. So in this case, when shorting, and it says 0.00026, it means that the shorts would receive this amount.

**Comment by thomaseizinger** [comment]
It appears to me that we should fix this in the daemon and return fields like:

```json
{
	"you_pay_hourly": "0.000026%"
}
```
and

```json
{
	"you_receive_hourly": "0.000026%"
}
```

Actual names subject to bike-shedding. The main point being: The daemon knows, which role it is in and thus, could map this directly to an unambiguous representation. I would suggest to have a think about what we want to display in the UI and then make the API resemble this as closely as possible.
