### ISSUE TITLE
Warning: Failed to fetch attestation

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1696]
Not an error but a warning in our logs: 

```
Failed to fetch attestation: Failed to deserialize as Attestation: error decoding response body: attestation missing: attestation missing
```

Not sure if this is a red flag for something.

**Comment by thomaseizinger** [comment]
This means we tried to fetch an attestation that does not exist yet. Can be a transient error of the oracle. We should probably extend the logs with the event ID.

**Comment by bonomat** [comment]
closing this in favor of https://github.com/itchysats/itchysats/issues/1966
