### ISSUE TITLE
Improve startup logs

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#1728]
we are currently not communicating what are we doing at startup. This makes it harder for potential users to notice what's wrong.
For example, we don't write that we're trying to connect to electrum server - which can take a long time if electrum server is not synced or never successfully finish in case of trying to connect to testnet electrum with mainnet flag on Itchysats. 

Adding more feedback would allow user to find out about such situations and potentially mitigate them.

**Comment by bonomat** [comment]
This project is unmaintained
