### ISSUE TITLE
Make it easier to switch between maker and testnet makers

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#1736]
It was somewhat arbitrary that we have tied maker's noise PK to its wallet seed. As one of these consequences, each maker supporting both testnet and mainnet will have to provide 2 different keys, which have to be changed by the user.
This is an inconvenience that could be dealt away with.

Counterpoint: different noise PKs make it somewhat less likely that the taker will connect to a maker on a wrong network.

**Comment by klochowicz** [comment]
as a quickfix for the time being, we could also hardcode the maker ids of the currently running makers and look it up based on the type of network / domain.

**Comment by klochowicz** [comment]
Somewhat related: going away from seed files could also give us the flexibility of reusing the same noise credentials if we'd like to: #1630

**Comment by bonomat** [comment]
I'd say it is a security feature to have a different ID for maker on mainnet and for the maker on testnet. That way it is harder to accidentally connect to the wrong one

**Comment by bonomat** [comment]
I'm closing this for now due to https://github.com/itchysats/itchysats/issues/1736#issuecomment-1235022946. I think it is good practice to not have the same setup for testnet and mainnet as otherwise it is hard to detect if you accidently connect to the wrong one.
