### ISSUE TITLE
Fail early if Bitcoin network does not match upon establishing a connection

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1737]
At the moment there is no check for the Bitcoin network (`mainnet`, `testnet`) when connecting a taker to maker.
A testnet taker can connect to a mainnet maker and receive offers (and vice versa). 

This is not super critical.
Setting up a contract will fail (latest upon transaction publication because the chosen UTXOs will not exist), but we should catch this earlier and report back to the user.

Workaround could be #1736 until we deal with multiple makers.

**Comment by klochowicz** [comment]
One way this could be dealt with could be stating Bitcoin network as part of the `Hello` message or its future equivalent

**Comment by bonomat** [comment]
This project is unmaintained
