### ISSUE TITLE
Feature: Design collaborative liquidation protocol

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#1738]
Inspired by our introduction of collaborative settlement, collaborative liquidation is a protocol idea that would allow both parties to collaborate to liquidate the _taker_'s position, if the conditions to do so are met (i.e. both parties agree that the liquidation price has been reached). We only consider the taker's position being liquidated because it's overwhelmingly more likely due to their higher leverage.

This feature is more important as soon as we allow higher leverages, because the likelihood of a position reaching its liquidation price increases.

### The maker can get liquidated too

In my testing I found that the maker, despite always using a leverage of 1, can actually get liquidated if they go _long_. It still requires a considerable price movement, but it is possible.

We therefore have to consider if collaborative liquidation should be a protocol that can be initiated by both maker and taker. I am leaning towards only allowing the maker to do it, to reduce complexity. It's much less likely that the taker encounters a situation where the maker should be liquidated (given the maker's low leverage), and they can still rely on the non-collaborative settlement and liquidation intervals. And we could even design the protocol so that the maker triggers it even if it only benefits the taker.

**Comment by bonomat** [comment]
This project is unmaintained
