### ISSUE TITLE
Properly solve prioritisation of CET over refund

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1744]
Summarizing the problem what we try to solve: 

If the system was down for some time, it might happen that when we start again that so much time has passed that refund is possible. In this case, we want to check first, if the oracle actually did attest to the price and if so, we want to prioritize publishing the CET over publishing the refund transaction. 

Imho this sounds like a rare edge case, because it actually requires both parties to be down for the same time. 

A big problem here is that loading CFDs takes so much time, if this would be much faster, the problem could be solved with a timeout. 
The introduced timeout of #1470 was not the right solution to this problem as it did not give us proper guarantees: we don't know if fetching the attestations, decrypting and checking for suitable CETs is done by that. 

The timeout was removed in https://github.com/itchysats/itchysats/pull/1858 as it was deemed as not useful. 
Instead, we should look into other solutions. 

<details>
  <summary>Click to read old ticket description</summary>
The original issue is https://github.com/itchysats/itchysats/issues/1230 and it was "solved" in https://github.com/itchysats/itchysats/pull/1470.

However, we just discovered that the sleep was added _in_ the loop instead of before: https://github.com/itchysats/itchysats/blob/5c1ad930f2771112ccc509b13266ed85447b032d/daemon/src/monitor.rs#L620-L628

Unfortunately, moving this sleep might now actually have side-effects we don't want. Starting the daemon currently may take a couple of minutes, depending on the size of the database and thus, waiting 30 seconds is not enough.

This issue is about solving this problem in a more resilient way.
</details>

**Comment by bonomat** [comment]
https://github.com/itchysats/itchysats/pull/1858 touches this code and removes the sleep because it was deemed to not be useful. Loading CFDs from the DB takes more than 30 seconds and hence, the oracle actor did not have enough time to fetch and decrypt the attestations. We need to look for a better solution. 

Removing this sleep should not do any harm for us because this is an edge case where we have been offline for too long and CET and Refund are possible when starting up .

**Comment by bonomat** [comment]
This project is unmaintained
