### ISSUE TITLE
Initial integration with libp2p-xtra

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1766]
1. Use libp2p's tokio TCP transport
2. Create a ed25519 identity from our current network identity
3. Create a compatible listen multiaddress from our current listen address on the maker
4. Transform `maker` domain / ip + port to multiaddress for dialling on the taker
--5. Create a `KeepConnectionAlive` actor for the taker that - on an interval - queries the `ConnectionStats` on the taker side and reinitates a dial in case we are not connected to the maker.--
6. Introduce a `libp2p_connections_total` metric that tracks the number of connections

**Comment by thomaseizinger** [comment]
So we found out that 

> Create a ed25519 identity from our current network identity

is not possible because the keys are incompatible. We have two options here:

1. Require users to also specify the `PeerId`. This could be annoying for users outside of umbrel.
2. Introduce a message in our network layer where we send over the new `PeerId` and connect to it from there.

**Comment by klochowicz** [comment]
Out of the two options, option 1. seems easier for now - especially that we don't want to concurrently run both for long time and that our default setup will use default arguments for the time being as well.
