### ISSUE TITLE
Design proposal for `/itchysats/offer` protocol

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1768]
Tracking issue for libp2p-based network layer: https://github.com/itchysats/itchysats/issues/1595

With the capabilities of multiplexing, we have several choices in how we can send offers from the maker to a taker:

- Push vs pull (i.e. maker pushes by opening a substream vs taker pulls by opening a substream)
- one-shot substream vs streaming multiple offers (one substream per protocol vs reusing the same substream to send another message)

All four combinations are technically possible. The design we are proposing here is the _one-shot push_ combination. In other words: The maker opens a substream to the taker _per offer_ they want to send. We prefer this combination because

- The maker knows when the offer changes, pushing the latest offer is more efficient.
- Opening a new substream per offer is more resilient because there is less state management. If we fail to open a substream to a taker, we can mostly ignore that problem. On the next offer update, we will naturally try again.

At the moment, we send an (optional) short and an (optional) long offer to the taker. We can keep these data structures as is for this migration.

## Optional scope extension

There is an optional scope extension that we may want to contemplate. We have been talking about re-modelling our usage of orders and offers for a while. In particular, we could leave the data structure almost as is but only remove the `OrderId` from it, thus not invalidating an offer just because it is taken by a taker. With https://github.com/itchysats/itchysats/pull/1455, we are re-sending another offer once the current one is taking. This suggests that an offer should not actually get invalidated, the offered price is still valid for the next taker!

Many parts of our system currently rely on the concept of a unique `OrderId` per offer/order. We can still maintain that by designing a compatible `/itchysats/order` protocol that allows peers to place an order with another peer. An order to be placed would come with a unique ID and thus, the invariant of one unique ID per offer/order is still maintained.

**Comment by luckysori** [comment]
Design looks good!

- I agree on pushing the latest offer. That way messages are sent when the offer actually changes.
- Are there any disadvantages related to using a one-shot substream?

Regarding the optional scope:

- I'm for the suggestion of moving the `OrderId` to the `Order` and away from the `Offer`.
- Could this be an opportunity to decouple the `offer` from the `funding_rate`? I've been thinking that the `funding_rate` is a value that theoretically changes much less frequently than the `offer`. Interestingly, I think the offer information is only useful when the UI is open and when the taker tries to take an offer. I wonder if we're sending a lot more data around than we need to.

**Comment by klochowicz** [comment]
> Design looks good!
> 
> * I agree on pushing the latest offer. That way messages are sent when the offer actually changes.
> * Are there any disadvantages related to using a one-shot substream?
> 
> Regarding the optional scope:
> 
> * I'm for the suggestion of moving the `OrderId` to the `Order` and away from the `Offer`.
> * Could this be an opportunity to decouple the `offer` from the `funding_rate`? I've been thinking that the `funding_rate` is a value that theoretically changes much less frequently than the `offer`. Interestingly, I think the offer information is only useful when the UI is open and when the taker tries to take an offer. I wonder if we're sending a lot more data around than we need to.

are you postulating that we have a separate protocol `/itchysats/funding_rate`?

**Comment by thomaseizinger** [comment]
> * Could this be an opportunity to decouple the `offer` from the `funding_rate`? I've been thinking that the `funding_rate` is a value that theoretically changes much less frequently than the `offer`. Interestingly, I think the offer information is only useful when the UI is open and when the taker tries to take an offer. I wonder if we're sending a lot more data around than we need to.

Interesting idea. We still want to include it in the offer for display purposes right? However, which exact funding rate to use for a rollover should perhaps be part of the rollover protocol. I'll take that into account when I continue on the rollover protocol tomorrow.

**Comment by thomaseizinger** [comment]
> Are there any disadvantages related to using a one-shot substream?

One that comes to mind is higher (have not measured!) bandwidth usage due to the message framing that needs to happen. However, before we optimise that, I'd first look into more efficient serialization formats for our messages overall. JSON is extremely inefficient.

I am not a fan of protobuf's schema language because it composes very badly but cap'n proto looks fairly rich: https://capnproto.org/language.html

**Comment by luckysori** [comment]
> are you postulating that we have a separate protocol `/itchysats/funding_rate`?

Yeah, we could. The maker could then push out updates to the funding rate generally every 8 hours (like BitMEX does for example).

> We still want to include it in the offer for display purposes right?

Do we have to? The funding rate(s) usually outlasts the current offer: it doesn't necessarily change after an offer is taken. They can appear together for display purposes, but they could originate from different protocols.

I think it would be a nice composition if we have `/itchysats/offer` and `/itchysats/funding_rate` protocols which enable the taker to initiate an `/itchysats/order` protocol.

**Comment by thomaseizinger** [comment]
> I think it would be a nice composition if we have `/itchysats/offer` and `/itchysats/funding_rate` protocols which enable the taker to initiate an `/itchysats/order` protocol.

Possibly! Even though they might change at different rates, making protocols more fine granular also comes with trade offs and overhead. I think having a separate `funding_rate` protocol might be worth it but I am not entirely sure.

For example, in the proposal for the rollover protocol, I am including the funding-rate in the `Accept` message to allow the protocol to be idempotent. Thus, the `funding_rate` sent via this protocol would only be used for display purposes so I am not sure if it is worth separating.

**Comment by luckysori** [comment]
> Possibly! Even though they might change at different rates, making protocols more fine granular also comes with trade offs and overhead. I think having a separate funding_rate protocol might be worth it but I am not entirely sure.

I do agree that introducing a separate protocol for the `funding_rate` has tradeoffs.

> For example, in the proposal for the rollover protocol, I am including the funding-rate in the Accept message to allow the protocol to be idempotent. Thus, the funding_rate sent via this protocol would only be used for display purposes so I am not sure if it is worth separating.

I have yet to review the rollover protocol proposal in depth, so I can't say whether I agree with including the `funding_rate` in one of its messages yet. But if we go for that approach I agree that it would be much less useful to define a separate protocol to relay the funding rate.

**Comment by da-kami** [comment]
For the initial protocol I would vote for keeping the `funding_rate` as part of the offer. Otherwise the scope becomes a bit of a Pandora's box. We can easily evolve the protocol once migrated.

**Comment by klochowicz** [comment]
It would be nice if the new protocol passed in lot size (we still have it hard-coded!): #1266
