### ISSUE TITLE
Design proposal for `/itchysats/identify` protocol

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1769]
The proposed design is loosely based on https://github.com/libp2p/specs/tree/master/identify.

Core design choices:

- Only support _pulling_ identify information: Identify information is primarily useful for the peer that receives it. We don't want to push information to peers unless we know they are interested in it.
- Identify information should include:
	- agent-version
	- list of supported protocols
- Use JSON for encoding messages. We can switch a binary format in a different version.

The agent-version is useful for monitoring purposes.

Retrieving the list of supported protocol will allow us to make a runtime decision on which protocols to use to communicate with a peer. For example, a peer can signal that they want to have offers pushed (see https://github.com/itchysats/itchysats/issues/1768) by advertising the `/itchysats/offer` protocol.

Currently, `libp2p-xtra` has a static configuration of which protocols are supported by an `Endpoint`. However, one can imagine making this list dynamic and thus, advertising different protocols to different peers. This will allow for a form of A/B testing where we can offer a specific protocol to a few select peers and/or to a subset (i.e. 10%).

For example, a maker could advertise that it supports a new rollover protocol to select peers, thus allowing for a way of safely testing things in production without rolling them out to all takers at once.

## Open questions

- Use protocol specified in https://github.com/libp2p/specs/tree/master/identify instead? It will require the use of protobuf for the message encoding.

**Comment by luckysori** [comment]
> Use protocol specified in https://github.com/libp2p/specs/tree/master/identify instead? It will require the use of protobuf for the message encoding.

Unless this would speed us up considerably, I wouldn't bother. Is the main advantage compatibility? I don't think we need to worry about it for a long time.

> Only support pulling identify information: Identify information is primarily useful for the peer that receives it. We don't want to push information to peers unless we know they are interested in it.

Does this mean that peers should periodically poll each other for this information? It seems acceptable for a taker to periodically poll the single maker they're connected to. But a maker could be connected to many takers. How do you see this working?

**Comment by thomaseizinger** [comment]
> > Use protocol specified in [https://github.com/libp2p/specs/tree/master/identify](https://github.com/libp2p/specs/tree/master/identify?rgh-link-date=2022-04-07T00%3A47%3A08Z) instead? It will require the use of protobuf for the message encoding.
> 
> Unless this would speed us up considerably, I wouldn't bother. Is the main advantage compatibility? I don't think we need to worry about it for a long time.

I don't think it will because we would have to code it from scratch or modify `libp2p-identify` to some degree so we can reuse at least the messages.

> > Only support pulling identify information: Identify information is primarily useful for the peer that receives it. We don't want to push information to peers unless we know they are interested in it.
> 
> Does this mean that peers should periodically poll each other for this information? It seems acceptable for a taker to periodically poll the single maker they're connected to. But a maker could be connected to many takers. How do you see this working?

I think initially, we can assume that the list of supported protocols is static and thus, fetching it once should be enough. If we ever build a node that dynamically supports certain protocols, we may need to refresh this information and act according to what is available.

**Comment by thomaseizinger** [comment]
Here is how I imagine this to actually look in code:

- Have an actor that polls the `Endpoint` continuously for all connections, similar to how the `ping` actor works (see https://github.com/itchysats/itchysats/pull/1784).
- For each connection, fetch `identify` information from them and caches it locally. Whether or not to "refresh" already present identify information can be a configuration parameter.
- Define a message that other actors can send to get the identify information about a particular peer.
- Define metrics on the information gathered by the identify protocol:
	  - `IntGaugeVec` to count supported protocols, segregated by protocol. This allows us to say things like: 30% of all connected peers support protocol X.
	  - `IntGaugeVec` to count connections per `agentVersion`
	  - Perhaps even an `IntGauge` to count how many peers don't support identify
- To satisfy incoming identify protocols, we will need to add a message to `Endpoint` to get the list of currently supported protocols
- Sending and receiving the message on a substream should be a separate module, just as in https://github.com/itchysats/itchysats/pull/1784. This separation will make it easier to potentially change all of the above policies if we need to split the actor up for different usecases for example.

**Comment by da-kami** [comment]
Is the `agent-version` the `daemon-version`?
Additionally will also have to add the `environment` the user runs the application.

**Comment by da-kami** [comment]
I think we can encode the `Environment` (i.e. umbrel / raspiblitz, ...) into the identify protocol's `agentVersion` field. 
That field is a string that can be freely chosen.
Recommended is `program-name/semantic-version`, but I see no problem in extending it to: `program-name/environment/semantic-version`

That way we don't have to add additional fields and stay within the specification of identify without too much overhead.

**Comment by da-kami** [comment]
Note on `identify` only about querying information from a peer rather then sending it:
If a `taker` connects to a `maker` to query for the identify message, the `maker` queries back, i.e. upon connection establishing both parties query for identify.
