### ISSUE TITLE
Design proposal for `/itchysats/order`

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1770]
This proposal is dependent on the scope extension mentioned in https://github.com/itchysats/itchysats/issues/1768.

Placing an order is a core abstraction in the financial industry. Placing an order in a system can result in it being filled at which point the positions of both contract partners are adjusted accordingly. Orders can also remain unfilled. In a marketplace, unfilled orders are gathered in an orderbook. They are the foundation for how the mid-market price is defined for example.

We can move one step closer to such a model through the following design:

- Peers can open a substream with the `/itchysats/order` protocol
- The dialing peer sends an `Order` structure to the listening peer. An `Order` struct contains (at least) the peer's intention (buy/sell), the asset, price, quantity and leverage.
- Because we are placing an order directly with a peer and for improved user experience, the listening peer SHOULD decide straight away whether the are willing to fill this order or not and communicate their response back to the dialer through an `Accept` or `Reject` message.

```mermaid
sequenceDiagram
    Taker->>Maker: Open substream `/itchysats/order`, send `Order` struct
    Maker->>Taker: Accept
```

## Interim solution

As an interm solution, we propose to directly attach the creation of a new position to the `/itchysats/order` protocol. We can change these semantics in a later version of the protocol.

```mermaid
sequenceDiagram
    Taker->>Maker: Open substream `/itchysats/order`, send `Order` struct
    Maker->>Taker: Accept
	Taker->>Taker: Transition to contract-setup
	Maker->>Maker: Transition to contract-setup
	Taker->>Maker: Msg1
	Maker->>Taker: Msg1
	Note over Taker,Maker: More messages ...
```

## Appendix: With combined position

At the moment, itchysats does not have a "combined position". Eventually, it would make sense to track a peer's position and adjust it based on the orders they are placing. Doing so would allow the `/itchysats/order` protocol to _end_ at this point and be followed by a separate protocol that - based on the new balance of each peer's account - aligns the blockchain state with the account state. This look something like this:

```mermaid
sequenceDiagram
	Note over Taker,Maker: Assume the taker is 500 contracts long
    Taker->>Maker: Open substream `/itchysats/order`, buy 200 contracts @ $54000 with x3 leverage
    Maker->>Taker: Accept
	Taker->>Taker: Adjust local position: +200 contracts
	Maker->>Maker: Adjust local position: +200 contracts
	Note over Taker,Maker: +200 contracts, requires adding more margin for maker and taker
	Taker->>Maker: Open substream `/itchysats/channel-update`
	Note over Taker,Maker: Exchange required messages for channel update
```

Decoupling the channel update from placing orders allows for more flexibility. It can for example be used to also adjust the leverage of the position without placing an order.

However, introducing these abstractions now is deemed to be too much of a fundamental change to how the software works.

**Comment by luckysori** [comment]
- Why do you consider the protocol which includes contract setup an "interim" solution?
- Thank you for adding the `Appendix` and considering how the protocol could be evolved when we add combined positions. I agree that it is not worth introducing this complexity yet, particularly since we should be able to introduce changes by adding new protocols and deprecating old ones.
- Having looked at https://github.com/itchysats/itchysats/issues/1768, it would really make sense to attach the `OrderId` to this protocol if possible. I like how the `/itchysats/order` protocol doesn't depend on any other protocols: in theory the taker could come up with their own order parameters.

**Comment by thomaseizinger** [comment]
> Why do you consider the protocol which includes contract setup an "interim" solution?

Interim in the sense of "until we have a combined position".

> Having looked at https://github.com/itchysats/itchysats/issues/1768, it would really make sense to attach the OrderId to this protocol if possible. I like how the /itchysats/order protocol doesn't depend on any other protocols: in theory the taker could come up with their own order parameters.

Yep, that is the thinking. For example, closing a position is equivalent to placing an order that nullifies what you have. i.e. 500 contracts long can be closed by selling 500 contracts. We don't need to reference an offer for that and the outcome of "closing" the position is the result of ending up with a position of 0 contracts after the local book-keeping.
