### ISSUE TITLE
Maker stops sending heartbeat and orders

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1774]
The maker stopped sending orders and heartbeat. 
It looks like he dropped connections to takers which are constantly being reestablished but we don't send any heartbeats or orders

Last message was sent at `"timestamp":"2022-04-05T19:49:36.316154252Z`

<img width="1627" alt="image" src="https://user-images.githubusercontent.com/224613/161841138-6eea4baf-c4d8-420a-b3ae-ae2259956bec.png">

**Comment by thomaseizinger** [comment]
I've looked into this but we don't have any other logs here unfortunately. I am closing this as unactionable :/
