### ISSUE TITLE
Optimise DB queries after introduction of `close_cfds` table

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#1807]
Relevant after #1779 is merged.

🙃 I think it could be more efficient to use `join`s to load all the relevant data in one query, not sure it's worth it though. We could run some performance tests to see how much of a difference it makes.

_Originally posted by @da-kami in https://github.com/itchysats/itchysats/pull/1779#discussion_r847982902_

**Comment by bonomat** [comment]
This project is unmaintained
