### ISSUE TITLE
Replace `model::Usd` with `model::Contracts`

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#1808]
It appears to be more correct to model the number of contracts for a position using a `u64` rather than a `Decimal`. In our application each contract unit corresponds to 1 USD so there is no need to support fractions.

With https://github.com/itchysats/itchysats/pull/1779, we introduced a `model::Contracts` which we should use instead of `model::Usd`. Changes to the data inside the `cfds` and `events` tables is still blocked on settling on a strategy to introduce breaking changes there.

_Originally posted by @da-kami in https://github.com/itchysats/itchysats/pull/1779#discussion_r847998778_

**Comment by klochowicz** [comment]
I don't think "Contracts" are better option that "Quantity". Also, `Usd` gives the description of the asset pair - if we change it a generic one, we should really encode as a field in the type?

**Comment by klochowicz** [comment]
perhaps relevant discussion: #1458

**Comment by luckysori** [comment]
I think now that we are introducing ETHUSD it might be a good time to move in this direction cc @da-kami.

**Comment by bonomat** [comment]
There is no more `model::Usd`
