### ISSUE TITLE
Testnet taker does not pick up balance after restart (`0` balance forever)

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1814]
This is likely the same problem of scanning addresses that we encountered in the past. My guess is that we run into this now because the taker is trading periodically and we blew through the amount of addresses to be scanned when initializing the wallet.

Recommendation to start working on this ticket: 
* Can we upgrade BDK? Why is this not fixed yet? 
* Transition back to a managed wallet and not just in memory (not sure if that will help, needs more analysis)

Related old tickets:
https://github.com/itchysats/itchysats/issues/1510
https://github.com/itchysats/itchysats/issues/1538

**Comment by luckysori** [comment]
> Can we upgrade BDK? Why is this not fixed yet?

It was upgraded with https://github.com/itchysats/itchysats/pull/1655/. We no longer have 1000 look-ahead addresses hard-coded.

**Comment by da-kami** [comment]
> 

Oh, then there might be a different problem that causes our balance to b `0`. I don't think we withdrew from the taker?

**Comment by luckysori** [comment]
Appears to be fixed with #1817.
