### ISSUE TITLE
Update UI on first confirmation of final transactions

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#1815]
With https://github.com/itchysats/itchysats/pull/1779, we unintentionally (but knowingly) stopped considering CETs, refund transactions and collaborative settlement transactions as final in the UI with 1 confirmation. Instead, we now require 3 confirmations to transition from "pending" to "close".

We may want to undo this change of behaviour in the UI by introducing intermediate `XYZSeen` CFD events.

_Originally posted by @da-kami in https://github.com/itchysats/itchysats/pull/1779#discussion_r847986793_

**Comment by bonomat** [comment]
This project is unmaintained
