### ISSUE TITLE
Use Umbrel's mempool app as explorer

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1823]
For a more self-sovereign feeling allow users to use Umbrel's mempool app instead of mempool space for tx links.

(From user feedback)

**Comment by klochowicz** [comment]
This issue was also mentioned via a feedback form by another user. 

I guess we could pass in the mempool URL as a parameter (and default to the public ones). This way Umbrel / Raspiblitz / more privacy conscious users could use local mempool app.

**Comment by bonomat** [comment]
This is hard to achieve because mempool is an optional app. We'd need to build a heuristic checking if the service is available if we want it to be automated. 

I propose to introduce a settings screen where users can configure it themselves.

**Comment by bonomat** [comment]
This project is unmaintained
