### ISSUE TITLE
Handle loading errors if a CFD is no longer open (but the actor still thinks it is)

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1847]
Closing CFDs is a separate task can lead to moving a CFD while another actor thinks it is still open.

We have three actors that use `load_open_cfd_ids` and then delegate to other actors to load the CFD:

1. `monitor::Actor`
2. `oracle::Actor`
3. `auto_rollover::Actor`

Once we have the a list of `open` cfd `id`s we cannot be sure that the CFD can actually be loaded, because it might have been moved to `closed_cfds` after the list was loaded.
For e.g. the `oracle` actor it is likely to run into a loading problem, because we do somewhat long-running tasks (decrypt CET) after we load the CFD ids.

This is not an easy problem to solve. I think we don't want to go into a direction where we give some tasks priority over each other, that would bring another set of problems.
After a discussion with @luckysori  we came to the conclusion that the best way forward is for each actor that loads from the database to be resilient against loading errors. Additionally we might want to have a specific error for "CFD was moved to closed"  that is returned on `load_open_cfd`.
The way I imagine this is: If the CFD cannot be found in `cfds`, check if it can be found in `closed_cfds`, if so return a specific error that the caller can deal with / ignore.

**Comment by bonomat** [comment]
>  For e.g. the oracle actor it is likely to run into a loading problem, because we do somewhat long-running tasks (decrypt CET) after we load the CFD ids.

Can you describe the "loading problem" please?

**Comment by da-kami** [comment]
> > For e.g. the oracle actor it is likely to run into a loading problem, because we do somewhat long-running tasks (decrypt CET) after we load the CFD ids.
> 
> Can you describe the "loading problem" please?

This is the problem:

> Once we have the a list of open cfd ids we cannot be sure that the CFD can actually be loaded, because it might have been moved to closed_cfds after the list was loaded.
