### ISSUE TITLE
Make awaiting three confirmations to close a better user experience

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1886]
I, as a user, noticed that "suddenly" it takes way longer until my CFDs move from open to closed. So I kept clicking the link and then being like, "ah, it's because we changed it to three confirmations...". I think we should improve that experience, it might be a low hanging fruit. 

Currently we display `Pending Payout` as status once a spend transaction (i.e. collab settlement tx) make it on chain. With waiting for three we could add some kind of confirmation counter to make it clear what's going on. Might be worth evaluating if we can easily yield the current confirmation number.

**Comment by bonomat** [comment]
This project is unmaintained
