### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1891]
- Some simple "How to Docker"
- Some simple "How to Binary"

Contribution guidelines (...)
Could have a look at https://github.com/comit-network/xmr-btc-swap/ that readme is concise.

**Comment by klochowicz** [comment]
seems like the current readme is mostly for development, maybe we could move it to `development.md` or something like that and only reference it for the devs. I guess when it was created, there were no users 😁
