### ISSUE TITLE
Use libp2p DNS transport to perform name resolution

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#1896]
Instead of doing this, we should wrap the `TokioTcpConfig` in a DNS transport and let it do the name resolution. See https://docs.rs/libp2p-dns/0.32.1/libp2p_dns/.

_Originally posted by @thomaseizinger in https://github.com/itchysats/itchysats/pull/1876#discussion_r858163059_

**Comment by thomaseizinger** [comment]
I think we need to do this before we can see a successful connection on testnet.

**Comment by bonomat** [comment]
This project is unmaintained
