### ISSUE TITLE
Add on-boarding tour to taker-ui

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1897]
# On-boarding tour: 

An onboarding tour is a guided walkthrough through our application. It guides users step-by-step through what they can do and have to do to for the important actions: 
- deposit funds
- open a position
- close a position
- ... 

There are a few libraries which we could make use of: 

- intro-js: looks like the best rated one. Has a free mode for non-commercial and paid for commercial applications. Not so sure about react support: https://github.com/usablica/intro.js/
    - demo: https://introjs.com/  
- intro-js is a wrapper around intro-js: https://github.com/HiDeoo/intro.js-react 
    - demo: https://codesandbox.io/embed/o2A4gwXE3?hidenavigation=1  
- react-joyride: looks well rated according to github stars. https://github.com/gilbarbara/react-joyride
    - demo: https://react-joyride.com/ 
- react-sheperd: looks a bit stale: https://github.com/shipshapecode/react-shepherd
    - demo: https://shipshapecode.github.io/react-shepherd/

_Originally posted by @bonomat in https://github.com/itchysats/itchysats/discussions/1841#discussioncomment-2598628_

**Comment by da-kami** [comment]
The fact that https://github.com/usablica/intro.js/ is licensed under AGPL is somewhat annoying. ItchySats is licensed under MIT which is more permissive. To be 100% compliant we would have to license under AGPL in order to use it.
The intro.js page does state:

> Intro.js is free for open-source, personal and non-commercial sites. If your project is non-commercial, you can use Intro.js for free.

Not sure how strictly they  enforce the exact license. (Worst case we would have to buy a license for 9.99 once.)

React-Joyride is licensed under MIT so we could just use that without any restriction - we can use it as well, but in terms of features it has a bit less.

That said: I will use intro.js for now unless anybody has objections - @bonomat @klochowicz . I like that intro.js have steps and hints. That might come in handy at some point.
Note: https://github.com/HiDeoo/intro.js-react is licensed under MIT, I will use that wrapper because it's more convenient.

**Comment by klochowicz** [comment]
> The fact that https://github.com/usablica/intro.js/ is licensed under AGPL is somewhat annoying. ItchySats is licensed under MIT which is more permissive. To be 100% compliant we would have to license under AGPL in order to use it. The intro.js page does state:
> 
> > Intro.js is free for open-source, personal and non-commercial sites. If your project is non-commercial, you can use Intro.js for free.
> 
> Not sure how strictly they enforce the exact license. (Worst case we would have to buy a license for 9.99 once.)
> 
> React-Joyride is licensed under MIT so we could just use that without any restriction - we can use it as well, but in terms of features it has a bit less.
> 
> That said: I will use intro.js for now unless anybody has objections - @bonomat @klochowicz . I like that intro.js have steps and hints. That might come in handy at some point. Note: https://github.com/HiDeoo/intro.js-react is licensed under MIT, I will use that wrapper because it's more convenient.

if it's 9.99 one-time payment, then it's probably easiest to just pay for it 💰 more features inbuilt means probably less hassle for us to replicate the missing ones.

**Comment by da-kami** [comment]
After fighting with intro.js for a while to achieve "navgating" the user to the wallet as part of the tour I think it might actually be better to use react-joyride.

What is described in the ticket is more of a controlled tour, i.e. the user is supposed to do interactions (like open the menu, go to the wallet, ...) and not just showing where stuff is. The menu makes things a bit hard.

react-joyride has a `Controlled Tour` that showcases how such kind of tours can be achieved 

https://react-joyride.com/ (select `Controlled` at the bottom)
https://github.com/gilbarbara/react-joyride-demo/blob/master/src/Controlled/index.tsx

So far I was unable to easily achieve that with intro.js

**Comment by klochowicz** [comment]
> After fighting with intro.js for a while to achieve "navgating" the user to the wallet as part of the tour I think it might actually be better to use react-joyride.
> 
> What is described in the ticket is more of a controlled tour, i.e. the user is supposed to do interactions (like open the menu, go to the wallet, ...) and not just showing where stuff is. The menu makes things a bit hard.
> 
> react-joyride has a `Controlled Tour` that showcases how such kind of tours can be achieved
> 
> https://react-joyride.com/ (select `Controlled` at the bottom) https://github.com/gilbarbara/react-joyride-demo/blob/master/src/Controlled/index.tsx
> 
> So far I was unable to easily achieve that with intro.js

I would also look into changing that horrible hamburger menu on desktop (this makes only sense on mobile, it would be much better to have the actual tabs visible all the time on desktop IMHO).

**Comment by da-kami** [comment]
The issue description mentions

> deposit funds
> open a position
> close a position

do you imagine that the user does all that during the tour or should the tour just be a simple "this is where things are"? @bonomat 

Letting the user do tasks while the tour is ongoing is super hard. We might just want to use `Hints` then, but not a step-by-step tour. 

Generally, making a step-by-step tour that includes user interaction (as in there is a step where the user actively should do something in the interface and not just click "next") is hard. It's also hard to "navigate" within the tour. These tours seems to be designed for jumping around in one single page - it is possible to add interaction / navigation, but it's hard. 
If you look at the `controlled` react-joyride example there is quite a lot of code there to achieve this, and I am still not sure it is "good enough" for what the ticket describes. 

Note: The menu really does not help with making the tour easy, because it is hard to control it because I cannot easily trigger it to open automatically. I would have to tell the user to do that (similar to what the controlled tour does).

I will need some more time to get the hang of these libraries. It would help to have somebody to pair for this task 😅

**Comment by klochowicz** [comment]
We could always add "how to open a position" and "how to close a position" to the FAQ for now!
I imagined the tour as sort of explanation of the UI, before users dive into it themselves.

**Comment by da-kami** [comment]
> We could always add "how to open a position" and "how to close a position" to the FAQ for now! I imagined the tour as sort of explanation of the UI, before users dive into it themselves.

Yeah, I think that's what these stepping tours are designed for. They show you where things are. But you don't actually do stuff. You just step and see. But the menu is somewhat of a hurdle there. (I already have some creative ideas how to overcome that... but I'm not sure my solution will meet the expectation of the ticket)
I think it would be cool to let the user do things through. I could experiment with `hints` instead. Hints just blink in various locations and show you "here is a hint for you" in the ui.

**Comment by klochowicz** [comment]
> > We could always add "how to open a position" and "how to close a position" to the FAQ for now! I imagined the tour as sort of explanation of the UI, before users dive into it themselves.
> 
> Yeah, I think that's what these stepping tours are designed for. They show you where things are. But you don't actually do stuff. You just step and see. But the menu is somewhat of a hurdle there. I think it would be cool to let the user do things through. I could experiment with `hints` instead. Hints just blink in various locations and show you "here is a hint for you" in the ui.

you almost describe "tutorial" stage. I'm not sure whether this is worth the hassle? I don't mind hints, as long as you can turn them off is a menu - which would require some Settings tab.
reasoning:
- a lot of people will miss them if they only pop up once
- a lot of people will get annoyed with things popping up, and would love to turn them off.

**Comment by da-kami** [comment]
> > > We could always add "how to open a position" and "how to close a position" to the FAQ for now! I imagined the tour as sort of explanation of the UI, before users dive into it themselves.
> > 
> > 
> > Yeah, I think that's what these stepping tours are designed for. They show you where things are. But you don't actually do stuff. You just step and see. But the menu is somewhat of a hurdle there. I think it would be cool to let the user do things through. I could experiment with `hints` instead. Hints just blink in various locations and show you "here is a hint for you" in the ui.
> 
> you almost describe "tutorial" stage. I'm not sure whether this is worth the hassle? I don't mind hints, as long as you can turn them off is a menu - which would require some Settings tab. reasoning:
> 
>     * a lot of people will miss them if they only pop up once
> 
>     * a lot of people will get annoyed with things popping up, and would love to turn them off.

Turning them (all) on and off is easy. They only pop up if you click on a blinking badge. But yeah, It might still be annoying. We would have to be smart with turning them on only initially (...).

**Comment by da-kami** [comment]
> I would also look into changing that horrible hamburger menu on desktop (this makes only sense on mobile, it would be much better to have the actual tabs visible all the time on desktop IMHO).

A note on that: We can change this, but I am not sure how tabs would fit in given that we have quite a lot of information in the top bar. In ambrosia we had a side-bar with icons. 

I think we agree that the wallet should be a separate view (i.e. separate route)...? 
If so, we would have to define how to make it better accessible from `home`.

**Comment by bonomat** [comment]
> do you imagine that the user does all that during the tour or should the tour just be a simple "this is where things are"? @bonomat

sorry for the late response, I was off on Friday. 

This ticket came from: 
> Our UI is not obvious to use and hence needs some explanation

In an ideal world, an additional explanation is not necessary, but unfortunately our interface is at times hard to use and we might lose users because they don't know how to use this tool.
 
So the idea was, to instead of sprinkling tooltips all over the place, to have a guided tour through our application which explains most bits and pieces.

**Comment by thomaseizinger** [comment]
Idea mentioned in the alignment meeting:

We could "enable" the button even without a wallet balance and either replace or add an additional text that says "You need to deposit money into the wallet first."

**Comment by klochowicz** [comment]
> Idea mentioned in the alignment meeting:
> 
> We could "enable" the button even without a wallet balance and either replace or add an additional text that says "You need to deposit money into the wallet first."

not sure whether this would actually be helpful. makes it harder to intuitively grasp the mental model of the application....

**Comment by klochowicz** [comment]
one thing that I realised we could do to make it easier to implement simple tour:
- before user opens anything, we could display a "dummy Cfd" - just to show the fields etc, and show how it would be closed (via "closed" button of course). We could clearly state that in the tour that it's dummy (maybe even header?), and it would disappear when user opens their first Cfd.
note that could also reduce the TTP as there's a reason to start a real one - for the dummy to go away 😁

**Comment by bonomat** [comment]
I like the idea of the dummy CFD 👍 Needs to be clearly labeled though but can indeed help users to understand what's happening/will be happening.

**Comment by da-kami** [comment]
I think the "dummy CFD" idea is nice, but it goes a bit beyond the scope of this ticket and some details to it that might not be completely straight forward to solve.
I added a new ticket: https://github.com/itchysats/itchysats/issues/1971
The ticket includes an "open questions" section, feel free to comment :)

**Comment by da-kami** [comment]
https://github.com/itchysats/itchysats/pull/1961
