### ISSUE TITLE
Add FAQ section to website and add link to taker-ui

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1898]
# FAQ

- a blog entry explaining most confusing parts of the system
- link in the corner of the app, so it's easy to spot for newcomers
- can get updated "as we go", when users are asking us a question that would be obvious to us, but not to a first-time user
- can also point to some popular knowledge bases where people can learn about CFDs etc.

Example:
Q: Can I use my existing wallet / umbrel wallet?
A: Not yet. We've got it on our roadmap, for the time being the app has its own inbuilt wallet into which you can transfer funds. It is available in the "Wallet" tab.

_Originally posted by @klochowicz in https://github.com/itchysats/itchysats/discussions/1841#discussioncomment-2598915_

**Comment by klochowicz** [comment]
First cut of the FAQ (so far in the itchysats repo): #1908

**Comment by bonomat** [comment]
Closing this given the PR #1908 was merged

**Comment by bonomat** [comment]
Re-opening because parts are missing 😬🙈

**Comment by klochowicz** [comment]
> Re-opening because parts are missing 😬🙈

yes, that's why I didn't mark the PR as 'closing' the issue. will finish them off today!
