### ISSUE TITLE
"Long BTC" and "Short BTC" buttons in taker-frontend reload the entire page

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#1904]
I believe this must be some bug in the UI code. We have client-side routing and thus should not need to reload the entire page.

**Comment by bonomat** [comment]
Was this on master? I can't reproduce this on 0.4.12

**Comment by thomaseizinger** [comment]
I'll try to reproduce this!

**Comment by bonomat** [comment]
Not reproducible
