### ISSUE TITLE
Add feature-flag to enable metrics for taker

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1946]
#1921 adds position metrics to the daemon which are updated in the `ProcessManager`. This has the effect that the taker could also make use of metrics. 
Right now, the metrics are collected but are ending in Nirvana and listen to smells like teen spirit till the end of their days. 

It'd be nicer to also have an endpoint for the taker which can be enabled (or disabled) using a feature flag. (Note: At this point I'm leaning to enabling it using a feature flag)

This can come handy for our testnet setup. 

_Originally posted by @thomaseizinger in https://github.com/itchysats/itchysats/issues/1921#issuecomment-1114497345_

**Comment by thomaseizinger** [comment]
Note: I was originally thinking of a _compile-time_ feature flag so enabling that would require a code change and re-deployment.

**Comment by bonomat** [comment]
Metrics are enabled for the taker by default. Accessing them requires authentication hence we opted for no featureflag
