### ISSUE TITLE
`latest` container tag that always points to the `latest` released container (at least for taker)

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1959]
This is just useful when writing any kind of documentation. 
It can also be useful for users that e.g. want to test the application on testnet. 
At the moment we always have to describe how to get the latest container.

For releases we have https://github.com/itchysats/itchysats/releases/latest but for containers we don't have a `latest` tag.

**Comment by klochowicz** [comment]
Thank you for raising this. I really feel we should have this in order to allow easy update process for our Docker users.

**Comment by bonomat** [comment]
This project is unmaintained
