### ISSUE TITLE
Don't fetch attestations on the hour

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1966]
There is a timing issue when fetching attestations from the oracle: 

```
 {"timestamp":"2022-05-05T05:00:00.407204071Z","level":"DEBUG","fields":{"message":"Fetching attestation for /x/BitMEX/BXBT/2022-05-05T05:00:00.price?n=20"},"target":"daemon::oracle"}
...

{"timestamp":"2022-05-05T05:00:01.082597076Z","level":"DEBUG","fields":{"message":"Failed to fetch attestation: Failed to deserialize as Attestation: error decoding response body: attestation missing: attestation missing"},"target":"daemon::oracle"}
```

If you check the explorer the attestation was provided a few seconds later: 

https://h00.ooo/x/BitMEX/BXBT/2022-05-05T05:00:00.price?n=20

```
"time":"2022-05-05T05:00:08"
```

**Comment by luckysori** [comment]
I don't think this is a bug. It's completely acceptable to fail to get the attestation at the exact time IMO. We retry every 5 seconds anyway.

**Comment by bonomat** [comment]
Oh, you are right. That's not a bug. 
Thanks for pointing it out.

Maybe we can get rid of this warning by making a sanity check on the response body?
