### ISSUE TITLE
Change the width of the tour steps

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1968]
This is a follow up ticket to https://github.com/itchysats/itchysats/pull/1961 

On large screens the restricted width of the tour steps feels a bit awkward.
We should be able to set the width by modifying the `intro.js` CSS classes.

**Comment by bonomat** [comment]
There is no more tour in ItchySats :)

**Comment by holzeis** [comment]
> There is no more tour in ItchySats :)

why not? 😅 I think something like that would have helped me with my initial questions on the taker ui 🙈

**Comment by bonomat** [comment]
I doubt it 🙈 the library we used was too annoying to use and quite buggy.
