### ISSUE TITLE
Add metrics for `Tasks` to monitor tasks running

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1969]
This should help to monitor why memory consumptions sometimes goes up over time.
Similar to https://github.com/comit-network/xtra/pull/5 it would be great to get histogram data for the tasks running.

We should investigate how histograms deal with a timer being started but never ended (i.e. for tasks that are running forever such as the intervals).

**Comment by thomaseizinger** [comment]
Perhaps we can utilise the `backtrace` crate to automatically generate a label consisting of the file + line number of the caller and use that to label the tasks.

Alternatively, we will need to manually pass a label at every call site.

The downside of the backtrace-based labels are that they will change with every refactoring so perhaps not the best idea for stable metrics _across_ different versions.

**Comment by bonomat** [comment]
Closing this for now because we learned a few things about Tasks, e.g. see #2051

**Comment by klochowicz** [comment]
additionally, this will also be covered by tokio-metrics, when we'll start using it.
