### ISSUE TITLE
Dummy CFD to help onboarding

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1971]
This idea was first mentioned in https://github.com/itchysats/itchysats/issues/1897 and can be seen as a follow-up.

Display a dummy CFD:

1. The dummy is visible from the very start of the application (not added during the tour, it is just there).
2. The tour should include describing the dummy.
3. Once the user opens an actual CFD the dummy is automatically removed.
4. The dummy CFD is clearly marked as "dummy"
5. The state of the dummy CFD is "open" 
6. The dummy CFD points to a lock transaction (maybe the first Bitcoin transaction?)

---

Open questions around the values of the dummy CFD - might need addressing before starting to work on this ticket:

Should this feature be (1) purely visual, so the user see what the values of the tile will be, or (2) should the tile also reflect proper values so the user can validate / understand how the values behave?

(1) is easy, but I question how much it will help - it might be confusing without the values being updated - at least in relation to the current price. (The funding events and rate add another level of complexity)
(2) is harder and we will have to take multiple decisions; see more related questions below.

* Should the dummy CFD purely live in the UI or is the dummy requested from the daemon? 
* Do we use a fixed initial price? 
    * It would be cool to use the index price at the time when the user opened the UI, but that has the disadvantage that we would actually have to calculate the other values. (this is related to the question, if the dummy should be purely living in the UI).
    * If we use a fixed price the dummy might be big in the minus or the plus depending on the current price. Do we care?
    * Even if all values are static and only in the UI (fixed based on production values), we might have to update the dummy in case calculations in the daemon change. The calculations should not change much, but I want to point that out.
* The funding rate and current price fluctuate - do we care in the dummy? 
     * Similar to the decision on the initial price we will have to decide if the dummy should react to e.g. price changes. Should all values always be fixed, or should the dummy adapt to the current price and funding rate? The user won't see changes (and cannot actually do a calc to reproduce the values) if we don't react to the current price (i.e. update the payout and P/L). Then again - should the UI calculate or the daemon?

**Comment by da-kami** [comment]
I think one major question to answer is: 

Should this feature be (1) purely visual, so the user see what the values of the tile will be, or (2) should the tile also reflect proper values so the user can validate / understand how the values behave?

(1) is easy, but I question how much it will help - it might be confusing without the values making sense - at least in relation to the current price. (The funding events and rate add another level of complexity)
(2) is harder and we will have to take multiple decisions (see questions above)

**Comment by bonomat** [comment]
This project is unmaintained
