### ISSUE TITLE
Transaction information in the UIs

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#198]
Both maker and taker should see all relevant transaction ids in the UI. Note the transaction IDs can just taken from the transactions in the dlc (no db extension needed). 
We can decide what IDs to show based on the state - or just display all for now (which might be a bit confusing for users)

In addition to the `txid` it would also be great if we could have the amount(s), at least for the payout tx that is very relevant.

**Comment by da-kami** [comment]
Idea for plan of attack:

1. Outline / Mock what we want to display in the UI
2. Let the daemon construct the information the UI needs based on state (...)
3. Send over something like `CfdDetails` that the UI can just display

**Comment by thomaseizinger** [comment]
Is this done @da-kami ?

**Comment by da-kami** [comment]
#272
