### ISSUE TITLE
Fundingfee/interest block pro-active, charge retro-active

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1982]
Our current approach of charging funding fee/interest rate is wrong: 

- funding interval is every 1h and renewed every hour on the hour, e.g. 00:00, 01:00, 2:00, ...
- funding rate is fixed for those intervals e.g. 
  - 00:00-00:59: 10%
  - 1:00-1:59: 5%
  - 2:00-2:59: -5%

Our current approach is to charge 24h in advance with a 1h interval using the _current_ rate:

E.g. 
- a position opened at 09.05.2022 at 00:00 gets a funding rate locked in of `10%` for 24, i.e. until 10.05.2022 00:00
- we _rollover_ every hour and keep charging `10%` until 10.05.2022 07:00.
- on 09.05.2022 at 01:00 we get a new rate and charge for the next 1h added after 24h, i.e. we charge `5%` for the hour 09.05.2022 01:00-09.05.2022 01:00 at `5%`
- we keep doing this ... 
- on 09.05.2022 2:00 we get the next rate and charge for the next 1h in 24h at `-5%`, i.e. 09.05.2022 02:00-09:05.2022 03:00 at `-5%`
- ... and so on.

I assume that it is already visible how this is flawed :)

Instead, we should _block_ the rate pro-actively in case the position does not get rolled over, but _charge_ retro-actively. 

Meaning we should do: 
- a position opened at 09.05.2022 at 00:00 gets a funding rate locked in of 10% for 24, i.e. until 10.05.2022 00:00
- for the first 1h, we _rollover_ and keep charging 10%. 
- on 09.05.2022 at 01:00 we get a new rate and charge for the next `24h` 5%, i.e. 9.05.2022 01:00-09.05.2022 02:00 at `5%`
- we keep doing this ... 
- on 09.05.2022 2:00 we get the next rate and charge for the next 1h in 24h at `-5%`, i.e. 09.05.2022 02:00-09:05.2022 03:00 at `-5%`
- ... and so on.

additionally, if a position is not rolled over every hour, e.g. the taker was offline for 15h, we should retro-active charge the rate

- a position opened at 09.05.2022 at 00:00 gets a funding rate locked in of 10% for 24, i.e. until 10.05.2022 00:00
- taker goes offline for 15h
- on 09.05.2022 at 15:00 we get a new rate and charge 
   - 09.05.2022 at 00:00 - 09.05.2022 at 01:00, `10%`
   - 09.05.2022 at 01:00 - 09.05.2022 at 2:00, `5%
   - and pro-active for the remaining 24h:    until - 10.05.2022 at 15:00, `5%

That way we are a bit closed to charging the correct rate. 

We still have the problem of positions which stop being rolled over, e.g. a taker disappears. Their position will have the wrong funding rate for the remaining hours. 

Imho there is nothing else we can do besides _reducing_ the rollover interval to the funding interval.

<details>
  <summary>Click to expand for old ticket description!</summary>
Our current approach of charging funding fee/interest rate is wrong: 

- funding interval is every 8h, e.g. 00:00, 08:00, 16:00
- funding rate is fixed for those intervals e.g. 
  - 00:00-7:59: 10%
  - 8:00-15:59: 5%
  - 16:00-23:59: -5%

Our current approach is to charge 24h in advance with a 1h interval using the _current_ rate:

E.g. 
- a position opened at 09.05.2022 at 00:00 gets a funding rate locked in of `10%` for 24, i.e. until 10.05.2022 00:00
- for the first 7h, we _rollover_ every hour and keep charging `10%` until 10.05.2022 07:00.
- on 09.05.2022 at 08:00 we get a new rate and charge for the next 1h `5%`, i.e. 10.05.2022 08:00-10.05.2022 08:00 at `5%`
- we keep doing this for the next 7h
- on 09.05.2022 16:00 we get the next rate and charge for the next 1h at `-5%`, i.e. 10.05.2022 16:00-10.05.2022 17:00 at `-5%`
- ... and so on.

I assume that it is already visible how this is flawed :)

Instead, we should _block_ the rate pro-actively in case the position does not get rolled over, but _charge_ retro-actively. 

Meaning we should do: 
- a position opened at 09.05.2022 at 00:00 gets a funding rate locked in of 10% for 24, i.e. until 10.05.2022 00:00
- for the first 7h, we _rollover_ every hour and keep charging 10%. 10.05.2022 07:00.
- on 09.05.2022 at 08:00 we get a new rate and charge for the next `24h` 5%, i.e. 9.05.2022 08:00-10.05.2022 08:00 at `5%`
- we keep doing this for the next 7h
- on 09.05.2022 16:00 we get the next rate and charge for the next 1h at -5%, i.e. 9.05.2022 16:00-10.05.2022 17:00 at -`5%`
- ... and so on.

additionally, if a position is not rolled over every hour, e.g. the taker was offline for 15h, we should retro-active charge the rate

- a position opened at 09.05.2022 at 00:00 gets a funding rate locked in of 10% for 24, i.e. until 10.05.2022 00:00
- taker goes offline for 15h
- on 09.05.2022 at 15:00 we get a new rate and charge 
   - 09.05.2022 at 00:00 - 09.05.2022 at 08:00, `10%`
   - 09.05.2022 at 08:00 - 09.05.2022 at 15:00, `5%
   - and pro-active for the remaining 24h:    until - 10.05.2022 at 15:00, `5%

That way we are a bit closed to charging the correct rate. 

We still have the problem of positions which stop being rolled over, e.g. a taker disapears. Their position will have the wrong funding rate for the remaining hours. 

Imho there is nothing else we can do besides _reducing_ the rollover interval to the funding interval.
</details>

**Comment by da-kami** [comment]
> Our current approach of charging funding fee/interest rate is wrong:
>
> * funding interval is every 8h, e.g. 00:00, 08:00, 16:00

Can you elaborate? Our funding interval is not 8 hours, but 1 hour.

**Comment by da-kami** [comment]
I do get the point that the initial charge of `24h` based on the *current* rate is "wrong" because the current rate is not what the rate may be during the next 24h. This is due to the fact that this feature was originally designed to charge up front. 
The 24h were chosen because that is the oracle-timestamp expiration interval we currently use - i.e. after 24h without a rollover the position will be force-closed. We *can* reduce this to e.g. 8 hours but I am not sure that is what you want to express in your description.

I think we can charge retro-actively, but that means that we might not collect fees if the user decides to go offline. 

When charging retro-actively I think the correct approach is for the maker to keep books on the rate and fees over time, and tell the taker what is to be paid when the taker wants to roll-over. If the taker missed rollovers the maker could still have all the fees collected over time. The only way to "back out" for the taker would be to stay offline.

If you charge an initial fee for whatever period when opening the position that is not retro-active charging. You always have to come up with something.
We could later adapt the initial fees charged based on the actual rates that happened. - Is that what you are proposing?

**Comment by bonomat** [comment]
> > Our current approach of charging funding fee/interest rate is wrong:
> > 
> > * funding interval is every 8h, e.g. 00:00, 08:00, 16:00
> 
> Can you elaborate? Our funding interval is not 8 hours, but 1 hour.

🙈 You are right. Our `funding interval` is 1h and not 8 hours, but I see you get the point. 

//EDIT//I've updated the description.

**Comment by bonomat** [comment]
> We could later adapt the initial fees charged based on the actual rates that happened. - Is that what you are proposing?

@da-kami : yes, this is what I propose: 

- when ever rollover (or opening a position) we charge the funding rate for the next 24h 
- when the rate changes, we need to retro-actively change the fees so that the taker paid the correct amount. 

I tried to draw it here: 

this is how it is at the moment:

![image](https://user-images.githubusercontent.com/224613/167338839-d20e4fbd-f8bf-41a4-b8fe-e7f3f991ed4e.png)



this is how it is supposed to look: 

![image](https://user-images.githubusercontent.com/224613/167338712-8b7d4e99-1e79-4c3a-9d65-66bc9af589d3.png)

**Comment by da-kami** [comment]
So, effectively this would mean:

* The fee is currently at `10%`
* Open CFD: `fee_account_balance = initial_fee = fee_for_one_hour at 10% * 24` based on current funding rate of `10%`
* The fee changes to `5%` in first hour (i.e. before rollover 1)
* Rollover 1: `fee_account_balance = fee_for_on_hour at 10% + fee_for_one_hour at 5% * 24`
* The fee changes to `-5%` in second hour (i.e. before rollover 2)
* Rollover 2: `fee_account_balance = fee_for_on_hour at 10% + fee_for_one_hour at 5% + fee_for_one_hour at -5% * 24`

(...)

Correct?

**Comment by bonomat** [comment]
Yes, this is what I mean. 👍
If we do this, then the chance of maker and taker coming up with a fee account is lower than it is at the moment.

**Comment by bonomat** [comment]
This project is unmaintained
