### ISSUE TITLE
Dynamic computation of `initial_funding_fee`, `margin`, `liquidation_price`

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#1983]
At the moment the project assumes that we always have a leverage of 2 for the taker and 1 for the maker. 
This will change once we have selectable leverages.
At the moment, the projection uses the fixed known leverage to compute
- `initial_funding_fee`, 
- `margin`, 
- `liquidation_price`

If the taker can select a leverage in the UI, then these values will need to be calculated dynamically from the UI (or via an additional HTTP endpoint).

**Comment by da-kami** [comment]
If we want to keep the calculations in the UI simple I think it should still be possible to pre-calculate the base value for `x1` and then only multiply by selected leverage in the UI (instead of doing more complex calcs). Not sure this is the best way forward though.

**Comment by bonomat** [comment]
Related to: https://github.com/itchysats/itchysats/issues/1739
