### ISSUE TITLE
Position that is closed does not display `P/L` 

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1986]
A closed position should have a spend TX and should always have a fixed PL.
However, this position in the closed testnet taker positions does not show P/L:

![image](https://user-images.githubusercontent.com/5557790/167380317-8c3e629e-472e-4d8f-9fb0-3a74ca441257.png)

I think this might just be a ui-bug, but there might be more to it.

**Comment by bonomat** [comment]
Looks good now. You might have caught it at a moment where the daemon did not have a price: 

![image](https://user-images.githubusercontent.com/224613/167513872-a5bca9fa-9a87-4ba8-aa38-baf6d948f628.png)

**Comment by da-kami** [comment]
It appears that this is related to CFDs that were *recently* closed - I don't have a clear pattern yet, but as @bonomat stated the CFD above is now fine. However, this recently closed one has this problem:

![image](https://user-images.githubusercontent.com/5557790/167515090-76929559-4406-478a-8ed5-c351ccbed282.png)

Might be that P/L is not set correctly while the payout TX is still pending or similar

**Comment by luckysori** [comment]
How do we proceed with this, @da-kami? Can we close this?

**Comment by da-kami** [comment]
Have not experienced it recently, I think it was fixed.
