### ISSUE TITLE
Making UI cfd actions more understandable

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#199]
At the moment actions that can be taken on a cfd are somewhat hard to understand for users.
Especially the difference between `settle` (non-collaborative close) and `close` (collaboratively close) are hard to understand.

Proposed changes: 

* Tooltips (or other form of textual description that can be triggered) for all actions that describe what an action does.
* Pop-up for `settle` (non-collaborative close action) that asks the user if the user is sure that they want to go on chain, and potentially display

**Comment by klochowicz** [comment]
IMHO these should be text buttons - relying on iconography for such a fundamental thing puts unnecessary burden on the user.

**Comment by klochowicz** [comment]
also @da-kami : are you sure that `settle` is the term non-collaborative settlement? 

Last Friday, when you rolled out actions on the taker side, you connected it to my collaborative one....
https://github.com/comit-network/hermes/blob/master/daemon/src/routes_taker.rs#L120

**Comment by bonomat** [comment]
Closing this for now as the taker UI will be deprecated soon and there will be more ui improvements needed for the new UI
