### ISSUE TITLE
Store counterparty peer id into the DB

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#1993]
We will need to store this information to be able to successfully finish some protocols, such as collab settlement or rollover.

in case a peer id was not stored, we can fall back to the mainnet/testnet/dev-maker/dev-taker peer id with a simple lookup by counterparty network identity (ie. the old id).

**Comment by da-kami** [comment]
Relevant for the design of this ticket: https://github.com/itchysats/itchysats/discussions/1998
