### ISSUE TITLE
Cleanup CFDs without events when handling failed CFDs

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#1997]
This is a solution for https://github.com/itchysats/itchysats/issues/1987

Loading and moving CFDs into `failed_cfds` should additionally handle CFDs that that fullfil:

* CFD has no events AND CFD is older than 1h

This is, unfortunately not trivial to fix because of the time constraint, because we don't save a creation timestamp in the `cfds` table but rely on `events` only.

Here are some ideas to tackle the issue of not knowing when a CFD (without events) was created:

1. Add a `created` timestamp to `cfds` - we can easily do that. We can also write a migration that fills in e.g. the first event's timestamp for existing CFDs - or if no events are found just default to some timestamp in the past.
     * This has the advantage that we cleanup "no event" CFDs as described above because we will have a timestamp that we can rely on.
2. Add a new `Created` event that is put into the database when `intert`ing a CFD (in a db-transaction, so we make sure we have it...)
    * This does not solve moving no-event CFDs periodically - but we could still check on startup and later rely on this event.

I'd be for finally adding a timestamp to the `cfds` table - it has been annoying *not* to have this timestamp numerous times. Do we have any good reason not to do so besides "not needing it"?

**Comment by luckysori** [comment]
We could just hide it in projection if a CFD has no events?

**Comment by da-kami** [comment]
Closing until https://github.com/itchysats/itchysats/discussions/2128 has a conclusion. 
@luckysori I am not sure if you already invested time into a solution, if so it would be great if you could add to the discussion!
