### ISSUE TITLE
Remove the legacy networking port in favour of libp2p-based port

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#2009]
Right now, we're in transitory time where we maintain 2 connections:
- one for legacy networking (currently 10000)
- one for libp2p-based connections (currently 10001). Note that the second one is not configurable independently, but it's just the next port after the legacy networking.

When we decide to fully drop the legacy networking, we should use the CLI argument to point to the lip2p socket.

Note that this port should be a new one as we don't want old takers try to connect to an libp2p endpoint.

**Comment by bonomat** [comment]
This project is unmaintained
