### ISSUE TITLE
Reintroduce full control over oracle in `cfd_protocol/tests`

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#202]
After #201, we no longer control the oracle in the protocol tests and instead use a hard-coded response from `olivia`. It is good to test directly against a system which we use, but we lose the ability to construct and check all CETs, since a single price attestation from the oracle can only unlock one out of all the CETs.

**Comment by thomaseizinger** [comment]
This code now lives in `maia` so closing this.
