### ISSUE TITLE
Make the "setup" part of the `Hello` message

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2040]
This will help us to know how users use ItchySats. 
We can add this to / in addition to the version information we send over when the taker connects

It would be great if we can distinguish:

- Umbrel - we can use the presence of the app-seed parameter to know
- Docker - we can set an envvar when we build the container to know
- Binary - if it's none of the other then binary

Not in scope of this ticket:
With libp2p the `Hello` messages will go away, so if we move forward with libp2p we should plan how to migrate these metrics.
See https://github.com/itchysats/itchysats/issues/1769 for this task.

**Comment by klochowicz** [comment]
I really like the idea, but would prefer calling this field "platform" or something similar - setup actually can be confused with an action to setup something during `Hello`

**Comment by bonomat** [comment]
> Umbrel - we can use the presence of the app-seed parameter to know

The `app-seed` arg might also be used by people who want to provide their own seed to ItchySats so instead of depending on this logic I propose to set an ENV in the docker-compose file in Umbrel.

**Comment by 1010Tom** [comment]
@da-kami : did you start with this already? 
Would be good to know so that we can add it also to the Raspiblitz draft branch: https://github.com/rootzoll/raspiblitz/blob/f8f7e51a536ed5517d37321b742d54e3e071e3bc/home.admin/config.scripts/bonus.itchysats.sh#L171

**Comment by da-kami** [comment]
Closed with #2096
