### ISSUE TITLE
CETs dropped out of mempool

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#2047]
After a recent restart we re-published 10 CETs without a problem, i.e. the transactions were not rejected by the mempool. 
Looking up the transaction IDs in our logs we can see that they have been published before. 
This indicates that the pending CETs have been dropped from the mempool due to low fees. 

This can be a problem. 
We should monitor if a transaction was published but fell out of the mempool before it was included in a block.

Related to #491

**Comment by bonomat** [comment]
This is not marked as a bug because it looks like that we republished the transactions on a restart. If we don't restart though, this can be a problem.

**Comment by bonomat** [comment]
This is actually a problem... if the CET is not included in time refund becomes valid and either party could lose money. Meaning we need to make sure that it is included in time!

**Comment by da-kami** [comment]
We should tackle this with https://github.com/itchysats/itchysats/issues/2465

**Comment by Restioson** [comment]
These should also be flagged by check-positions

**Comment by bonomat** [comment]
I'll remove the critical label. It's so old and wasn't in focus at all that this is clearly not critical 🙈

**Comment by da-kami** [comment]
Closing this in favor of https://github.com/itchysats/itchysats/issues/3099
