### ISSUE TITLE
`Tasks` contains an ever growing vec of `RemoteHandle`

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2051]
When we `add` (or `add_fallible`) a task the `RemoteHandle` remains in the internal `Vec` forever, it will never be removed. 
Given that `RemoteHandle` is just a pointer this should not be expensive, but we should investigate how fast this *can* grow.

In both the legacy connection actor(s) and the libp2p impl  we add tasks upon connection handling. 
I.e. for ping we add a task for each peer every 5 seconds. This can multiply up quite fast over time.

**Comment by bonomat** [comment]
# Analysis

My limited analysis says that the size of a handle is `16 bytes`. I used `size_of` and `size_of_val`:
```
std::mem::size_of::<RemoteHandle<()>>(); --> 16
std::mem::size_of_val(&handle); --> 16
```

The amount of values in the internal vector of `Tasks` is indeed increasing and never emptied. 

To analyze which tasks are the most common one, I added an addition field to the functions `add` and `add_failable`. 
It looks like that these two here are the only one being constantly added, adding roughly 1 new entry every ~2-3 seconds (which is to be expected given our current ping protocol): 

https://github.com/itchysats/itchysats/blob/8699ca0e20f22c75f491d1da36d61e1bbcc65268/xtra-libp2p-ping/src/lib.rs#L118

and 

https://github.com/itchysats/itchysats/blob/8699ca0e20f22c75f491d1da36d61e1bbcc65268/xtra-libp2p-ping/src/lib.rs#L148-L150

This seems to be the same for taker and maker. 

The branch can be found here: https://github.com/itchysats/itchysats/pull/new/task-names

# Conclusion

This is indeed a memory leak, but if my number is correct then this is not main problem of our huge memory consumption.
