### ISSUE TITLE
Closed CFDs should use static data

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#210]
Right now, the `Unrealized P/L` is dynamically calculated but for closed CFDs the P/L it is already know. 
Instead, the "closed" CFDs should use static data.

**Comment by scratchscratchscratchy** [comment]
outdated

**Comment by bonomat** [comment]
Reopen and updated description

**Comment by bonomat** [comment]
Afaik this has been resolved already @da-kami ?

**Comment by 1010Tom** [comment]
Please reopen if it is not done @da-kami
