### ISSUE TITLE
Taker-frontend: Dom error 

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#2106]
I noticed that the browser console is throwing an error: 

>React does not recognize the `data-feedback-fish-customerId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `data-feedback-fish-customerid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by bonomat** [comment]
@klochowicz : any reason why this is called `data-feedback-fish-customerId` and not `data-feedback-fish-customerid` ?

**Comment by klochowicz** [comment]
> @klochowicz : any reason why this is called `data-feedback-fish-customerId` and not `data-feedback-fish-customerid` ?

I have just followed the suggestions from their page to append custom metadata: https://feedback.fish/help/metadata

More than happy to change it, let's see if it will still work. needs rebasing to pass peerId anyway, so might as well see if it will work with lower case!
