### ISSUE TITLE
Reintroduce collab settlement unit test failing due to `maia` close transaction txfee bug

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2112]
A long time ago we added a test that ensures that if we get liquidated by "too many rollovers" the party that got liquidated ends up with a `0` amount:

https://github.com/itchysats/itchysats/blob/6699ca22011fc63f6a23549314d4f7aa5778bb45/model/src/cfd.rs#L3045-L3074

I just tried to run the test but it is still failing. This means that the payout calc is not complete yet, we should be able to handle this edge case.

**Comment by luckysori** [comment]
Assigning @klochowicz because he is fixing this as part of working on https://github.com/itchysats/itchysats/issues/320.
