### ISSUE TITLE
Improve tests in `model/cfd`

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2116]
This is a follow up of https://github.com/itchysats/itchysats/pull/2111 where we use a loop and "common time boundaries" to test rollover hour calc. 

We should not use loops in tests. Cleanup by splitting the tests in multiple, or potentially use proptest.

As part of this it would be great to think about possibilities to split up`model/cfd` into different sub-modules so we can move some of the tests. 

---

Related to https://github.com/itchysats/itchysats/issues/1430.

**Comment by klochowicz** [comment]
Please wait until I get the new collab close in, because I had to fix quite a few tests there! #320 
edit: it's in :)

**Comment by bonomat** [comment]
This project is unmaintained
