### ISSUE TITLE
Avoid exiting the application if we fail to lookup the maker address

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2119]
This is the result of an investigation where the testnet taker was was not running for significant time because the application had just exited upon startup leading the container to stop.

```
2022-05-23 14:48:58	
{"timestamp":"2022-05-23T04:48:58.950821203Z","level":"TRACE","fields":{"message":"measuring heartbeat pulse"},"target":"wire"}
	
2022-05-23 14:49:01	
{"timestamp":"2022-05-23T04:49:01.243552118Z","level":"INFO","fields":{"message":"Initialized logger"},"target":"shared_bin::logger"}
	
2022-05-23 14:49:01	
{"timestamp":"2022-05-23T04:49:01.2436744Z","level":"INFO","fields":{"message":"Running version: 0.1.0"},"target":"taker"}
	
2022-05-23 14:49:01	
{"timestamp":"2022-05-23T04:49:01.243707847Z","level":"INFO","fields":{"message":"CFDs created with this release will settle after 24 hours"},"target":"taker"}
	
2022-05-23 14:49:01	
{"timestamp":"2022-05-23T04:49:01.355320375Z","level":"INFO","fields":{"message":"Opened database at /data/testnet/taker.sqlite"},"target":"daemon::db"}
	
2022-05-23 14:49:01	
Error: failed to lookup address information: Name or service not known
```

The error comes from std::net likely from the cvt_gai call in this tryfrom impl<'a> TryFrom<(&'a str, u16)> for LookupHost - but that does not really help. I'm surprised we don't see a panic if the application crashed

This is likely triggered by:

https://github.com/itchysats/itchysats/blob/eeefe8eefa818b94551bd9e54e41da0963ed8e35/taker/src/main.rs#L329

which does a `tokio::net::lookup_host` :

https://github.com/itchysats/itchysats/blob/eeefe8eefa818b94551bd9e54e41da0963ed8e35/taker/src/main.rs#L417-L428

Note that I am not entirely sure if tokio::net::lookup_host actually uses the code in std::net - but I'd say this is a likely candidate (also because the last message before is the db connection message, and that fits the code execution)

I think we fail there and just exit main.

We can add a retry mechanism there, but essentially its questionable if we can start with such an error. It might be a valid solution to let the container restart.

**Comment by bonomat** [comment]
I think it's fine to let the application terminate if it is not able to connect to the maker because of a lookup_failure.
