### ISSUE TITLE
Introduce a timeout on Endpoint for protocol execution

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#2155]
Allow closing a substream if a protocol hasn't been completed within the specified time.

**Comment by klochowicz** [comment]
#2189 solves most pressing issue (collab settlement not being able to time out) - as such, this issue is no longer blocking the release.

**Comment by klochowicz** [comment]
yesterday after conversation with @da-kami we reached a conclusion that even if this is possible to implement a single timeout on Endpoint for the whole protocol execution, we still need the timeouts for decision. Since libp2p rollover already had this capability, I have rolled it out in #2189 for collab settlement as well.

**Comment by bonomat** [comment]
This project is unmaintained
