### ISSUE TITLE
Upgrade to latest BDK and remove patched version dependencies

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2187]
Make sure we don't depend on patches anymore:

#2153 
https://github.com/itchysats/itchysats/pull/2174

**Comment by klochowicz** [comment]
Blocked on BDK v0.19 release, I presume? Or do we intend to upgrade to master as soon as convenient for the time being?

**Comment by klochowicz** [comment]
new version of BDK will be released soon: https://github.com/bitcoindevkit/bdk/pull/629

**Comment by klochowicz** [comment]
We recently reverted the patch, and the new bdk update got merged as well: #2312
