### ISSUE TITLE
User interface has trouble loading upon auto-opening UI in `Firefox`

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2208]
When running the binary the user interface is opened in the default browser at `localhost:8000`.

The UI does open up, but for Firefox the user interface is (most of the times) not fully loaded but looks like this:

![image](https://user-images.githubusercontent.com/5557790/172771570-2c59759c-5a93-4cb2-a76b-bb7edf9ba673.png)

The user interface actually shows up before turning completely white. But not the complete interface, only the outer parts without the trade and history components.

Upon refresh everything loads correctly.

With Chrome I never had this problem, only Firefox.

I checked the rocket triggers and `on_ignite` should be correct for our use-case. But somehow it seems the user-interface may not be fully served directly after the launch.

**Comment by klochowicz** [comment]
@da-kami does it still happening to you after #2273 got merged?

**Comment by bonomat** [comment]
This was fixed with https://github.com/itchysats/itchysats/pull/2273
