### ISSUE TITLE
Initial Tour steps not properly attached to correct components upon initial auto-start in `Chrome`

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2209]
With `Chrome` as default browser the UI loads upon autostart, and shows the initial tour upon first open.

However, the tour steps after the `Wallet` step are not correctly linked to the components of the `Trade` component. 
Somehow `intro.js` is unable to link the steps to the component, which could mean that the initial render has some trouble with the `Trade` and `Histroy` component, so that `intro.js` does not find the keys in the DOM.

On my MacOs machine this happens on every initial load (i.e. auto-triggered browser open when running the binary).
After a manual refresh the problem is resolved.

Might be related to https://github.com/itchysats/itchysats/issues/2208

**Comment by klochowicz** [comment]
@da-kami does it still happening to you after #2273 got merged?

**Comment by luckysori** [comment]
We removed the initial tour with https://github.com/itchysats/itchysats/pull/2356.
