### ISSUE TITLE
Poll latest version from github and display in UI

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#2233]
I was thinking of how can we tell a user that a new version is ready to be used: 

1. the maker it is connected to can tell 
2. the daemon could fetch it from GitHub

With our network protocol we implicitely tell the taker to upgrade if their version is not compatible with the maker. 
This works well assuming we do network version bumps. (Which we haven't for a while 😅)

This won't work anymore if we have multiple makers, because then we might have different version out there and a taker might never see a new version with yummy new features.

Instead, we could go for (2) and let the daemon poll github regularly to check if a new version is available.

**Comment by klochowicz** [comment]
I really like this idea, however I raises a few questions:
- wold a toast notification lingering around might be too spammy spammy, especially for umbrel users, who can't just upgrade if the new version is not on their app store yet?  (can be solved by selectively enabling the polling for certain environments)
- should we add "inbox" for notifications that can be read and then dismissed? I have mentioned the idea in the past, and IMHO it would help to find a balance between a notification that's spammy and in-your-face when you don't want to upgrade just yet and dismiss-and-forget situation .
- to minimise the amount of polls, we could potentially poll when we open the UI

I don't think the notes above are blocking though, I think this feature would be great addition right now (and the rough edges can be ironed out as-we-go)

**Comment by bonomat** [comment]
All good questions :) 

One side note: Umbrel added the new "app store" with their latest release which allows us to push updates to the user independently.
