### ISSUE TITLE
Stream ended abruptly whilst waiting for maker decision on rollover

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#2259]
The maker calculates a new settlement event ID which is the same as the current settlement event ID for the CFD, so it cannot proceed with rollover (because it would be a 0-hour rollover). We must investigate if this is working correctly, but the functionality is wanted.

Also, we should consider emitting a rejection rather than closing the stream abruptly on the maker side.

Grafana logs [here](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22taker-rollover-failed-decision%22,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bsetup%3D%5C%22testnet%5C%22,%20container%3D%5C%22taker_master%5C%22%7D%20%7C%3D%20%60End%20of%20stream%60%20%7C%20json%20%7C%20fields_message%3D%5C%22Rollover%20failed:%20End%20of%20stream%20while%20receiving%20rollover%20decision%20from%20maker%5C%22%20%7C%20level%3D%5C%22ERROR%5C%22%22,%22queryType%22:%22range%22,%22hide%22:false%7D,%7B%22refId%22:%22maker-rollover-failed-decision%22,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bsetup%3D%5C%22testnet%5C%22,%20container%3D%5C%22maker%5C%22%7D%20%7C%20json%20%7C%20level%3D%60ERROR%60%22,%22queryType%22:%22range%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221655423743855%22,%22to%22:%221655424003696%22%7D%7D).

**Comment by da-kami** [comment]
> The maker thinks the new settlement event ID should be the same as the current settlement event ID for the CFD, so it chooses not to rollover.

I am confused by this sentence: How is the settlement ID related to rollover?

**Comment by luckysori** [comment]
> > The maker thinks the new settlement event ID should be the same as the current settlement event ID for the CFD, so it chooses not to rollover.
> 
> I am confused by this sentence: How is the settlement ID related to rollover?

By settlement ID I am referring to the oracle event ID expected to be used for the settlement of a particular CFD. When we rollover we choose a new oracle event ID so that the time-to-live of the CFD is extended.

In this case the maker aborts the protocol because otherwise they would agree to perform a rollover that would not extend the time-to-live of the CFD at all.

---

I've edited the body of the issue to clarify (it was confusing D:).

**Comment by da-kami** [comment]
For the specific case of `61836dd6-e2b9-4b2d-b5e1-c9b7337e6bb1` I think this ticket is irrelevant, because that CFD was already in a broken state when the error reported in this ticket happened. See https://github.com/itchysats/itchysats/issues/2262#issuecomment-1159272347

I like the idea of focusing on this problem separate - maybe all of them are related to already being in a state where the parties don't agree on the rollover state.

**Comment by luckysori** [comment]
We're no longer experiencing this.
