### ISSUE TITLE
Introduce authentication and encryption for the network layer

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#229]
Eventually we will transition the network layer to libp2p so we have a more structured way of designing network communication.

Up until then, we still want proper identification of peers (our current `TakerId` is transient with every connection), authentication of each other's messages and encryption of the entire communication.

To make the transition to libp2p later on easier, we first will:

- Use [`snow`](https://docs.rs/snow/0.8.0/snow/index.html) for the heavy lifting of encrypting and authenticating the connection
- Use the libp2p multi-addresses specification to configure the connection details to the other party

Using snow will require that we know the public key of the party ahead of time. Using libp2p's multiaddress provides several benefits:

- Specify connection details + public key in a single argument
- Allows usage of domains as well as IP addresses (https://github.com/comit-network/hermes/issues/292)

**Comment by rishflab** [comment]
Blocker1: Our messages are larger than the max message size supported by the noise protocol (65535 bytes). 

We need some sort of chunking of these messages. We can do this in the codec by breaking up the large message into chunks, encrypting each chunk and then recombining the byte chunks into a large byte buffer and sending that. The maker and taker just need to agree on the chunk size which can be hardcoded.

Blocker2: The libp2p address (hash of pubkey) is not compatible with noise which wants a pubkey (on a different curve). 

This can be resolved by not bothering with multiaddr and allow the taker to specify the makers noise pubkey
