### ISSUE TITLE
Consider `no-password` mode for Umbrel

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#2314]
Initially posted by @nevets963 in https://github.com/getumbrel/umbrel-apps/pull/50

> Would you also consider removing the requirement for a password? In Umbrel v0.5 and onwards, we automatically password protect (including 2FA where applicable) all installed apps. If you remove the password requirement, we can improve the user experience as they then don't need a secondary password for ItchySats.

**Comment by klochowicz** [comment]
I'm all for no-password mode, as long as it's an opt-in feature on mainnet ;) 

it can be useful for testing and for playing around on testnet (reducing the friction to try out itchysats)!

**Comment by bonomat** [comment]
I start to disagree with this feature. The login function of ItchySats is a security feature and we should not rely on the platform we are running on doing this for us. Same as your personal computer: you still have passwords for various programs despite having a password on system level.

**Comment by holzeis** [comment]
Does umbrel support openID connect? in that case we could outsource the autentication, improve the ux without loosing security.

**Comment by bonomat** [comment]
With #2903 we went one step further away from this and added cookie-based authentication. The session is set to expire in 1 week, meaning, the user does not have to login that often.
