### ISSUE TITLE
Frontend shows `Daemon version:  unknown`

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#2318]
Version 0.4.21
Platforms: 
- raspiblitz
- umbrel

Both show daemon version unknown in UI

<img width="443" alt="image" src="https://user-images.githubusercontent.com/224613/176351072-975b0ebb-5536-40bd-90c0-5d22ddd1478f.png">

**Comment by klochowicz** [comment]
funnily enough, it works on Docker release 😕  @bonomat does the outdated version pop-up work on umbrel / raspiblitz?

**Comment by bonomat** [comment]
> @bonomat does the outdated version pop-up work on umbrel / raspiblitz?

hard to test because we don't have a new version yet 😅

**Comment by bonomat** [comment]
It looks like the problem comes from loading too fast: when starting the frontend first it will show you `unknown` then when you hit refresh it will show the correct version. 

I'll see to provide a workaround.

**Comment by bonomat** [comment]
Ah, now I understand. The problem is that `fetch` requires the `credentials` but the user has not yet authenticated. 
I think we need a different login mechanism for this to work properly. 
I'll provide a temporary fix.

**Comment by klochowicz** [comment]
maybe we can bypass authentication for this request? It's nothing sensitive.

**Comment by bonomat** [comment]
> maybe we can bypass authentication for this request? It's nothing sensitive.

This could be a temporary fix as versions are sensible information: e.g. if I know you are running version X with an vulnerability I could attack you. Imho the proper fix is to ensure that we are logged in before we start all the logic in `App.tsx`. 

I was thinking of creating an additional login screen...
