### ISSUE TITLE
Taker to go short

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#232]
At the moment, the taker can only go long. We want them to be able to take short positions as well. This issue can used to track all ideas / problems we need to deal with for making this happen.

**Comment by DeliciousHair** [comment]
This shouldn't actually require much effort to implement I would think; the payout curve doesn't care which party is which, and the oracle can be used identically in either case as the payout curve is symmetric. Only the DB structure (may) require a bit of an adjustment, but I have not actually looked to see.

**Comment by thomaseizinger** [comment]
To be replaced with actionable issues.
