### ISSUE TITLE
Consider cleaning up old monitoring

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#236]
Under a few conditions it might be worth cleaning up our monitoring: 

- when we rolled over, we shouldn't care about any old monitoring for this contract as new monitoring will be started. 
- we have 24h rolling windows, which means we can cleanup monitoring for events which are in the past
- when we close/settle, we don't care about them neither

**Comment by luckysori** [comment]
I think this is related to #276.

**Comment by thomaseizinger** [comment]
Closing in favor of #276.
