### ISSUE TITLE
Opentelemetry goes berserker mode

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#2380]
I had the taker and maker running locally locally over night. Now I get spammed with these errors. 

```
OpenTelemetry trace error occurred. cannot send span to the batch span processor because the channel is full
OpenTelemetry trace error occurred. cannot send span to the batch span processor because the channel is full
OpenTelemetry trace error occurred. cannot send span to the batch span processor because the channel is full
OpenTelemetry trace error occurred. cannot send span to the batch span processor because the channel is full
OpenTelemetry trace error occurred. cannot send span to the batch span processor because the channel is full
OpenTelemetry trace error occurred. cannot send span to the batch span processor because the channel is full
OpenTelemetry trace error occurred. cannot send span to the batch span processor because the channel is full
OpenTelemetry trace error occurred. cannot send span to the batch span processor because the channel is full
OpenTelemetry trace error occurred. cannot send span to the batch span processor because the channel is full
OpenTelemetry trace error occurred. cannot send span to the batch span processor because the channel is full
OpenTelemetry trace error occurred. cannot send span to the batch span processor because the channel is full
OpenTelemetry trace error occurred. cannot send span to the batch span processor because the channel is full

```
2 questions
- What does this mean?
- Can we use our tracing library to log those errors? Since they are not json we won't be able to parse our logs to json anymore.

**Comment by bonomat** [comment]
cc @klochowicz / @Restioson

**Comment by Restioson** [comment]
This is interesting. How long do the logs continue and does it ever stop? This error seems to be that the number of batches is piling up in the queue. Maybe this is just a case of adding an exporter timeout or making the queue bigger, but then again maybe not...

**Comment by Restioson** [comment]
> Can we use our tracing library to log those errors? Since they are not json we won't be able to parse our logs to json anymore.

We can change [`set_error_handler`](https://docs.rs/opentelemetry/latest/opentelemetry/global/fn.set_error_handler.html) to make them print as JSON. I think that using `tracing` to log it could cause a circle of error -> log error -> error from logging error -> error -> ...

**Comment by klochowicz** [comment]
as for the error circle - wouldn't this be outside of any tracing span? I thought mere usage of `tracing` for logging doesn't automatically export data to the collector?

**Comment by Restioson** [comment]
> wouldn't this be outside of any tracing span

Perhaps, but I don't know if we can rely on knowing from where `handle_error` is called exactly.

> I thought mere usage of tracing for logging doesn't automatically export data to the collector?

I think it will given that the collector is part of the tracing subscriber

**Comment by klochowicz** [comment]
Indeed, there's no other way currently other than overriding the error handler: https://github.com/open-telemetry/opentelemetry-rust/issues/549

**Comment by klochowicz** [comment]
> > wouldn't this be outside of any tracing span
> 
> Perhaps, but I don't know if we can rely on knowing from where `handle_error` is called exactly.
> 
> > I thought mere usage of tracing for logging doesn't automatically export data to the collector?
> 
> I think it will given that the collector is part of the tracing subscriber

fair enough. let's just ensure the timestamps are encoded in the same way as when we're export other logs.

**Comment by klochowicz** [comment]
> > wouldn't this be outside of any tracing span
> 
> Perhaps, but I don't know if we can rely on knowing from where `handle_error` is called exactly.
> 
> > I thought mere usage of tracing for logging doesn't automatically export data to the collector?
> 
> I think it will given that the collector is part of the tracing subscriber

I have tested this hypothesis locally; even when the collector channel is closed (during the shutdown), tracing logs from such a custom error handler still work as expected. I'll throw a PR in a sec.

**Comment by bonomat** [comment]
I'm seeing these errors again on testnet.

**Comment by bonomat** [comment]
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/224613/179640802-a1587ca7-4bf1-453f-97fd-4ad71bbe7206.png">

**Comment by bonomat** [comment]
The reason for this is that the agent is not able to keep up with the logs

```
ts=2022-07-19T00:50:58Z level=info caller=exporterhelper/queued_retry.go:218 msg="Exporting failed. Will retry the request after interval." component=traces traces_config=default kind=exporter name=otlp/0 error="rpc error: code = ResourceExhausted desc = RATE_LIMITED: ingestion rate limit (166666 bytes) exceeded while adding 2114523 bytes" interval=8.688087835s
ts=2022-07-19T00:51:02Z level=error caller=exporterhelper/queued_retry_inmemory.go:109 msg="Exporting failed. No more retries left. Dropping data." component=traces traces_config=default kind=exporter name=otlp/0 error="max elapsed time expired rpc error: code = ResourceExhausted desc = RATE_LIMITED: ingestion rate limit (166666 bytes) exceeded while adding 2084234 bytes" dropped_items=512
ts=2022-07-19T00:51:09Z level=info caller=exporterhelper/queued_retry.go:218 msg="Exporting failed. Will retry the request after interval." component=traces traces_config=default kind=exporter name=otlp/0 error="rpc error: code = ResourceExhausted desc = RATE_LIMITED: ingestion rate limit (166666 bytes) exceeded while adding 2081270 bytes" interval=14.829523867s
ts=2022-07-19T00:51:13Z level=error caller=exporterhelper/queued_retry_inmemory.go:109 msg="Exporting failed. No more retries left. Dropping data." component=traces traces_config=default kind=exporter name=otlp/0 error="max elapsed time expired rpc error: code = ResourceExhausted desc = RATE_LIMITED: ingestion rate limit (166666 bytes) exceeded while adding 2114808 bytes" dropped_items=512
ts=2022-07-19T00:51:20Z level=info caller=exporterhelper/queued_retry.go:218 msg="Exporting failed. Will retry the request after interval." component=traces traces_config=default kind=exporter name=otlp/0 error="rpc error: code = ResourceExhausted desc = RATE_LIMITED: ingestion rate limit (166666 bytes) exceeded while adding 2558012 bytes" interval=13.571884121s
ts=2022-07-19T00:51:24Z level=error caller=exporterhelper/queued_retry_inmemory.go:109 msg="Exporting failed. No more retries left. Dropping data." component=traces traces_config=default kind=exporter name=otlp/0 error="max elapsed time expired rpc error: code = ResourceExhausted desc = RATE_LIMITED: ingestion rate limit (166666 bytes) exceeded while adding 2081270 bytes" dropped_items=512
ts=2022-07-19T00:51:32Z level=info caller=exporterhelper/queued_retry.go:218 msg="Exporting failed. Will retry the request after interval." component=traces traces_config=default kind=exporter name=otlp/0 error="rpc error: code = ResourceExhausted desc = RATE_LIMITED: ingestion rate limit (166666 bytes) exceeded while adding 3624990 bytes" interval=16.302738013s
ts=2022-07-19T00:51:49Z level=error caller=exporterhelper/queued_retry_inmemory.go:109 msg="Exporting failed. No more retries left. Dropping data." component=traces traces_config=default kind=exporter name=otlp/0 error="max elapsed time expired rpc error: code = ResourceExhausted desc = RATE_LIMITED: ingestion rate limit (166666 bytes) exceeded while adding 3624990 bytes" dropped_items=506
```

**Comment by bonomat** [comment]
Can we change opentelementry to a polling mode which automatically drops un-polled spans after a few seconds?

**Comment by bonomat** [comment]
Note: this is not a blocker for 0.5.0. If we can't solve this we just don't enable instrumentation on mainnet.

**Comment by Restioson** [comment]
This is partially a symptom of another problem, which is that at some point logs get really spammy and we get ratelimited... I wonder what the underlying cause of that issue is?

**Comment by Restioson** [comment]
[The docs of `opentelemetry_otlp`](https://docs.rs/opentelemetry-otlp/latest/opentelemetry_otlp/) says that we can configure the timeout - maybe this could help?

**Comment by bonomat** [comment]
>[The docs of opentelemetry_otlp](https://docs.rs/opentelemetry-otlp/latest/opentelemetry_otlp/) says that we can configure the timeout - maybe this could help?

How would the application behave if it can't send the trace to the collector due to a timeout?

**Comment by Restioson** [comment]
I'm not sure - opentelemetry-otlp just notes that it is the ["timeout to the collector"](https://docs.rs/opentelemetry-otlp/latest/opentelemetry_otlp/trait.WithExportConfig.html#tymethod.with_timeout). I asked already on the opentelemetry-rust gitter room about this, so I'll add this question too

**Comment by bonomat** [comment]
I think we can close this.
