### ISSUE TITLE
Funding rate

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#244]
The maker has to be able to define interest on the CFD, i.e. a percentage of the taker's amount that will always go to the maker regardless of the price change.

**Comment by scratchscratchscratchy** [comment]
Besides the fact the this will require changes on the protocol, what would be the trigger for this in the current program flow?

How does collecting interest (i.e. deduct the interest from re-setting up the CFD) work together with auto-rollover #456 and automatic closing #483 the CFD?

Here's what's in my head:

* auto-rollover without amount changes every hour, until we reach the 23rd hour of rollover.
* once in the 23rd hour of rollover the roll-over proposal should take the interest into account
* Both taker and maker have to validate that the amounts exchanged make sense according to what kind of roll-over (without interest or with interest) is happening.

This requires that we distinguish between initial creation and roll-over in the database.

Trigger for auto-close would be: If no roll over happens until attestation then close.

Note: The 23rd hour more generally means: `settlement_interval - 1 hour`, since we use `24` h as settlement interval I used 23h here. 

@itchymax what do you think?

**Comment by 1010Tom** [comment]
In my head this is relatively straight forward. Think of the scenario like this: 

- Alice goes long and puts up 0.01 BTC
- Bob goes short and puts up 0.01 BTC

Alice should pay Bob in a bull market , i.e. long pays short.

when creating the set of CETs we need to include the interest rate already, let's be expansive and say it's 10%/day. 
We construct the CETs as follow: 

```
{
	alice_out: AMOUNT_ALICE,
	bob_out: AMOUNT_BOB
	bob_interest: INTEREST
}
```

So for the initial CETs with an expiry of 24h the payout would look like this: 

```
{
	alice_out: AMOUNT_ALICE_n,
	bob_out: AMOUNT_BOB
	bob_interest: 0.001
}
```

where `AMOUNT_ALICE_n = AMOUNT_ALICE-0.001`.

We can feed `AMOUNT_ALICE_n` and `AMOUNT_BOB` directly into our payout curve calculation as before. 
`AMOUNT_ALICE` and `AMOUNT_BOB` both depend on the payout curve.

After 1h we rollover and we should update the fee accordingly: 
i.e. the new CET 

```
{
	alice_out: AMOUNT_ALICE_n2,
	bob_out: AMOUNT_BOB
	bob_interest: 0.001+(AMOUNT_ALICE_n2-AMOUNT_BOB/10%/24)
}
```

where `AMOUNT_ALICE_n2 = AMOUNT_ALICE_n2-AMOUNT_BOB/10%/24`

So we put `AMOUNT_ALICE_n2` and `AMOUNT_BOB` into our payout curve calculator.

Note: Alice should always pay interest on the amount she _borrowed_ from Bob, i.e. `AMOUNT_BOB`. This never changes, i.e. she does not pay compound interest.

The ugly thing about this approach is that we have an additional output on each CET, but I think we can live with that :)

**Comment by thomaseizinger** [comment]
We already did do some research on this. I haven't thought through either solution in detail but we have a good-looking write-up here: https://github.com/coblox/coblox-research/blob/main/notebooks/payout_curve_with_interest.pdf

**Comment by da-kami** [comment]
I will take the following assumptions for the implementation:

1. The maker publishes parameters related to the funding fee (initial and recurring) as part of the offer. The taker UI displays a fee breakdown based on the parameters in the offer.
2. We won't necessarily have a spread anymore, i.e. the fees represent the costs that the long position has. We cannot just remove the maker's price from the offer, because the parties cannot easily "agree" on what the current price is, but we might be able to display it different. This means that our "maker price" on the long button could probably go away, but we will display the fee breakdown instead that includes the maker price in relation to the index price. Note: If we keep both the price and a fee structure we can also tune the maker strategy by the offer - it could have a spread and fees then.
3. The recurring fee is charged on every rollover (i.e. hourly), i.e. we will calculate the recurring fee based on the rollover interval.
4. The P/L calculation has to take all costs (= initial and already charged recurring funding fees) into account.

**Comment by bonomat** [comment]
I don't think the _spread_ and funding rate are related and relevant for implementing this ticket. 

> 2\. We won't necessarily have a spread anymore, i.e. the fees represent the costs that the long position has. We cannot just remove the maker's price from the offer, because the parties cannot easily "agree" on what the current price is, but we might be able to display it different. This means that our "maker price" on the long button could probably go away, but we will display the fee breakdown instead that includes the maker price in relation to the index price. Note: If we keep both the price and a fee structure we can also tune the maker strategy by the offer - it could have a spread and fees then.

Some thoughts on this point: 
 
- the index price (shown above the input field) is not equal to bids and asks and they will always differ. That being said, somewhere we will need to show the rate the maker offers/the taker will get. I'm fine with moving this into the confirmation popup. 
- Imho you can ignore the _spread_ for this ticket: a maker comes up with a rate. It just happens that the easiest way to do so is by taking the rate from somewhere else and adding a spread. We will need to show this rate to the taker somehow but from the taker's perspective it is not clear how the maker came up with this rate.
- realistically, a maker won't be able to have a high rate and high interest: no taker would take his offers. That being said, a _smart_ maker might add a small _spread_ come up with reasonable interest rates.

**Comment by thomaseizinger** [comment]
> The maker publishes parameters related to the funding fee (initial and recurring) as part of the offer. The taker UI displays a fee breakdown based on the parameters in the offer.

I think we can move that into one parameter that resembles a fee / hour and calculate initial and recurring fees from that!
