### ISSUE TITLE
Wallet might block contract setup

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#2453]
I have the suspicion that our wallet actor might be the source of blocked/delayed contract setup: 

The wallet actor syncs synchronously, meaning, it is blocked for the time it is syncing. This can be a significant amount of time (>40 seconds). In the meantime, the actor is not able to handle other messages. 
However, in the contract setup we need to ask this actor for information
- [BuildPartyParams](https://github.com/itchysats/itchysats/blob/5d87284fe3324ee82ca00ab7b30c9567f511230b/daemon/src/setup_contract.rs#L78)
- and [signing](https://github.com/itchysats/itchysats/blob/5d87284fe3324ee82ca00ab7b30c9567f511230b/daemon/src/setup_contract.rs#L255)

**Comment by bonomat** [comment]
This is related: https://github.com/itchysats/itchysats/issues/947

**Comment by bonomat** [comment]
I can confirm this: 
- manually hit wallet sync on maker
- open position on taker

see that nothing is happening until the maker sync is done.

**Comment by Restioson** [comment]
We are blocking the tokio from the Wallet actor, which I think is probably one of the issues

**Comment by bonomat** [comment]
let's hope that https://github.com/itchysats/itchysats/pull/2469 made it better
