### ISSUE TITLE
`No DLC available` when starting a rollover / collab close

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2471]
Observed in the `testnet` `maker` logs

Relevant log: `No DLC available when starting a rollover`

Relevant CFDs where this happened:

    - `a09335dc-9554-4b7f-9dc4-f866b97cc3d7` - on 17.07.2022 (24h UTC)
    - `83bb6d02-692f-4029-80bd-f6980c488c22` - on 18.07.2022 (24h UTC)

Behavior: 

Similar behavior for both relevant CFDs. 
At first the rollovers complete normally, eventually the `maker` runs into the problem that it reports `No DLC available when starting a rollover` when the taker triggers a rollover. For `83bb6d02-692f-4029-80bd-f6980c488c22` eventually the `maker` recovered, i.e. eventually a rollover succeeded again (!).

Further investigation needed, potentially related to recent changes:

- https://github.com/itchysats/itchysats/pull/2386
- https://github.com/itchysats/itchysats/pull/2140

**Comment by bonomat** [comment]
closing until they happen again

**Comment by da-kami** [comment]
Reopening this because it happened in production.
Originally this ticket was reported on the `testnet` setup. Additional information will be provided.

**Comment by da-kami** [comment]
After another thorough analysis with @Restioson we came to the conclusion that this was solved as a side effect of https://github.com/itchysats/itchysats/pull/2671

This problem only occurred for cases where we loaded the Cfd right after the `RolloverCompleted` event. Prior to https://github.com/itchysats/itchysats/pull/2671 the event was saved into the db, and only afterwards the rollover data was overwritten (i.e. updated to the new event that was saved) in a separate transaction. The system could be in a state where the event was available, but the data was not. Given that `load_open_cfd` bumps the version according to the events, the version was bumped, but the data was never loaded.
There is no indicator for the *last* `RolloverCompleted` event which should *expect* the data being available, we could add that for the current solution. Using a transaction to store event + data should be sufficient for now though, which is what was fixed in https://github.com/itchysats/itchysats/pull/2671

**Comment by da-kami** [comment]
Note that with implementing https://github.com/itchysats/itchysats/issues/2555 the `dlc` would be mandatory in `model::Cfd` which removes the problem of having an optional `Dlc` in the `Cfd`. The whole model would become more sound by that.

**Comment by Restioson** [comment]
Additionally, without #2555, the solution mentioned has the potential to be brittle from a code design/refactoring perspective, as it would be easy to accidentally miss loading the CFD and pass None instead, since without #2555 we cannot make the dlc non-optional.
