### ISSUE TITLE
Cannot roll over when CFD is already closed

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2474]
Observed in the `testnet` `maker` logs

Relevant log: `Cannot roll over when CFD is already closed` and `NOT NULL constraint failed`

Relevant CFDs where this happened (both on 18.07.2022):

- `9069c43c-b0c9-4fc6-bc9d-d85d828741d6` - `taker_id` = `064e561cc7d1bb5c80ba7e51a68e9c3e63a2704f6a18a770620e8e6586604031`
- `1db397b3-ebb8-432b-91b5-ff1252031354` - `taker_id` = `c92f72932f6d0aa07e51624e237da9b5980c433ffb44c525487516bd8b8a5520`

Behavior: 

The CFD gets collaboratively closed by the taker. The collaborative close succeeds on the maker side. 
The taker keeps triggering rollovers, indicating that *somehow* the collaborative close failed after sending the signature to the maker.

The CFDs were opened from the same IP-address by different takers during a load test run of multiple takers using the same wallet extprvkey.

**Comment by bonomat** [comment]
closing until it happens again
