### ISSUE TITLE
Counterparty sent invalid revocation sk

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2475]
Observed in the `testnet` `maker` logs

Relevant log: `Counterparty sent invalid revocation sk`

Relevant CFDs where this happened:

 - `97a4920c-4848-4f63-a58a-1f2918ff46dc` - `taker_id` = `25d1efa9fd521d5b8f1908ed105dec7fe158f3d913204bc91e7fff276a53b221` - `peer_id` = `12D3KooWFZYotR8yFLdP28QX3MqD117bbvgJ4uC6m5iJ258Pq3Zx`
  - `a07e8148-80df-400b-aea9-696603818432` - `taker_id` = `a82cfcf840677c43a955127a4579f14c52056c0ec1b917f5e415a9fbbd5b4034` - `peer_id` = `12D3KooWFkkdjJY5aijC9QJUeyHocekErd45YuhWavoU9MoDYLvk`
  - `d8ceb1b8-5566-44b4-a519-2533a616d562` = `taker_id` = `7d3a0d444d63ce4f160ab542c41baeecdd1f54ff2e40c44346bc481d96cb4f38` - `peer_id` = `12D3KooWGy1XddxM5JsnkNma9zfNRedqUBcrnWUK62MPi2QCwATC`
  - `e0a45941-3a66-42fa-9f9d-936de64c14fe` = `taker_id` = `7d3a0d444d63ce4f160ab542c41baeecdd1f54ff2e40c44346bc481d96cb4f38` - `peer_id` = `12D3KooWGy1XddxM5JsnkNma9zfNRedqUBcrnWUK62MPi2QCwATC`

Behavior:

Analysis for `97a4920c-4848-4f63-a58a-1f2918ff46dc`: 

- Last successful rollover was at `2022-07-19 00:01:29`.
- After that the `taker` tried `Starting rollover from previous commit-txid`, namely commit-txid `8519f8ff8acb71fbd4922a2b654478d8bc84076cf39818745a261ebadf5a7f57`. 
- It appears that the maker and taker somehow disagree on the state for rolling over from `commit-txid``8519f8ff8acb71fbd4922a2b654478d8bc84076cf39818745a261ebadf5a7f57` because we always run into `Counterparty sent invalid revocation sk` on the `maker`.
- This likely points to a problem when rolling over from a previous `commit-txid`, because the parties disagree on the state

**Comment by da-kami** [comment]
Even without the taker db available I was able to investigate further on the maker. I assigned the ticket to myself and will see to track down if this is a bug in the new protocol design. I might not get to the bottom of this without the taker db, will stop then and keep this ticket around until we have a case where we have the data from both sides.

**Comment by da-kami** [comment]
This is very weird... the list of the `maker`s revocation keys for `97a4920c-4848-4f63-a58a-1f2918ff46dc` *does* include the relevant txid `8519f8ff8acb71fbd4922a2b654478d8bc84076cf39818745a261ebadf5a7f57`, associated with event-id `/x/BitMEX/BXBT/2022-07-19T09:00:00.price?n=20`, but...

According to the maker's db this was the first entry, i.e. the taker is trying to rollover from the contract setup `commit-txid` (!):

```
id      cfd_id  commit_txid                                                         oracle-event-id
15556,  1409,   8519f8ff8acb71fbd4922a2b654478d8bc84076cf39818745a261ebadf5a7f57,   /x/BitMEX/BXBT/2022-07-19T09:00:00.price?n=20
15557,  1409,   8225c4a50ce39bbf4eba284b4957b6fe0b6d890e515e87608ace16e24f517cd8,   /x/BitMEX/BXBT/2022-07-19T11:00:00.price?n=20
15558,  1409,   65bd567b6ff188ee31f7761084a121f81af27c2431cfdb6697cc5aa475fee0f1,   /x/BitMEX/BXBT/2022-07-19T13:00:00.price?n=20
15559,  1409,   b09e47f54e3ba2347a61b31637270659eec0c2d84073ccf3ecf182ddd66ef2ef,   /x/BitMEX/BXBT/2022-07-19T15:00:00.price?n=20
15560,  1409,   21b3fdd7543e2ba9800005c35f00513c8777064913e41e2c462037f1342db0de,   /x/BitMEX/BXBT/2022-07-19T17:00:00.price?n=20
15561,  1409,   43c47e3c7b9f76483724c343154750094f129287d9d23a921b51db505e3b0c78,   /x/BitMEX/BXBT/2022-07-19T19:00:00.price?n=20
15562,  1409,   84503f898956fdca949575fbbedc9a2ef5e7ab90768adeab2c612628ed0d5d79,   /x/BitMEX/BXBT/2022-07-19T21:00:00.price?n=20
15563,  1409,   f3c3f8f0918050dc044897a7b30fdbd0269ef3c665b73c94314538db6d310354,   /x/BitMEX/BXBT/2022-07-19T23:00:00.price?n=20
```

This does not explain why the parties don't agree on the state - it should be possible to rollover from that `commit-txid` in theory.

But, even more worrying: Why would the taker trigger a rollover from that `commit-txid` when there were 8 successful rollovers (+7 revoke commits + the current active rollover on the maker) after that first record already?
This would mean that the latest rollover on the `taker` side was associated with that commit - the logic is quite stupid on the taker side, it simply proposes the current dlc's `commit-txid` to the maker [1]. How is this possible?

I am stopping here, because without the taker's database I cannot really investigate this further. I don't want to fall back to too much guesswork.

---

[1] Taker chooses `commit-txid` for rollover:

https://github.com/itchysats/itchysats/blob/7a3ac85ffb17bd5f93a6286ad128497213ec9e5a/model/src/cfd.rs#L760-L775

**Comment by luckysori** [comment]
@da-kami and I have found a bug (several, really) in the maker's rollover code after we enabled the [new feature](https://github.com/itchysats/itchysats/pull/2272) which allows takers to rollover from an old DLC state.

Basically, even though the maker agrees to roll over based on the commit TXID proposed by the taker (which identifies the DLC "epoch"), they stubbornly use the data that corresponds to the _latest_ DLC when rolling over.

The way this causes the error `Counterparty sent invalid revocation sk` is because:

- Maker and taker try to roll over: maker succeeds and is on epoch X+1; taker fails and is on epoch X.
- Taker tries to rollover from epoch X, identified by the corresponding commit TX.
- Maker agrees to roll over from epoch X, since it can find the commit TX the taker sent in their own `Vec<RevokedCommit>` records.
- [Some rollover protocol things happen].
- Taker reveals their `revocation_sk` corresponding to epoch X in what we call `Msg2`.
- Maker compares the taker's revealed `revocation_sk` from epoch X against the taker's agreed `revocation_pk` from epoch X+1!

This is the symptom, but overall the maker code when performing the rollover protocol just assumes that they are always rolling over from the very last DLC epoch, which is wrong since https://github.com/itchysats/itchysats/pull/2272 merged.

**Comment by da-kami** [comment]
One note on why the test was unable to detect this - and will probably never be able to test this in our current setup.

The taker does not actually "fall behind", the only thing that the taker does is trigger rollover with a previous `commit_txid`, the latest DLC is still the one that was agree upon in the rollover.
So, the tests passed, because the taker is actually *not* behind. Since both parties access the latest rollover DLC when comparing the keys it passes.

We cannot easily set up the scenario where the taker is *actually* behind by one rollover, we would have to actively remove the rollover from the taker database, because we cannot just "make it fail" in the test.

**Comment by da-kami** [comment]
> We cannot easily set up the scenario where the taker is actually behind by one rollover, we would have to actively remove the rollover from the taker database, because we cannot just "make it fail" in the test.

Or just `append` the old data ;) 
https://github.com/itchysats/itchysats/pull/2494
