### ISSUE TITLE
Log/Span load reduction

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2484]
Evaluate what causes a lot of load; e.g. `verify encsig` creates a lot of load on the taker, and see to disable the instrumentation to specific code parts.

[This](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-traces%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22queryType%22:%22nativeSearch%22,%22limit%22:1000,%22search%22:%22%22,%22serviceName%22:%22maker_testnet%22%7D%5D,%22range%22:%7B%22from%22:%221658297351000%22,%22to%22:%221658297668000%22%7D%7D) query may help to evaluate what is creating load.

**Comment by klochowicz** [comment]
I'd be for removing (or adding a target that's disabled by default) everything from this file:

https://github.com/itchysats/itchysats/blob/master/daemon/src/shared_protocol.rs#L20

**Comment by Restioson** [comment]
Three initial targets:
- ~~verify_cet_encsig~~ EDIT: functions from shared_protocol.rs such as `verify_cet_encsig`
- successful pings
- successful taker offers

**Comment by klochowicz** [comment]
> Three initial targets:
> 
> * verify_cet_encsig
> * successful pings
> * successful taker offers

as per your first point, see my comment above - all of the instrumented futures from there are not of interest for us (can be either disabled by target or completely :) )

**Comment by Restioson** [comment]
I think this might be fixed with #2519, but it's worth keeping an eye on in Grafana

**Comment by Restioson** [comment]
I would tentatively say that this is fixed, as long as we disable `--verbose-spans`. I would propose we test this on mainnet next update/restart, as the current projected usage will be 110GB, but earlier it was 80GB only. I suspect a lot of this is the ping peer spans which would be disabled with `--verbose-spans` off.
