### ISSUE TITLE
Test the rollover protocol in isolation to capture more edge cases

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2497]
Follow up of https://github.com/itchysats/itchysats/pull/2494

There are several edge cases that should be tested in isolation rather than spinning up the complete actor system.
Testing in isolation requires a setup where we start from an initialized database (i.e. CFD in db) and then add rollovers.

We also need to make the protocol generic over some doeendencies we pass in: oracle and executor to name a couple. In #2378 we had to do all this because the protocol was moved out of `daemon`. Therefore that work is covered if/when we merge those changes.

**Comment by bonomat** [comment]
This project is unmaintained
