### ISSUE TITLE
Export tokio metrics to prometheus

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#2499]
It would be useful to see the state of the runtime in production (as stated elsewhere, we would have likely noticed the wallet sync not yielding back to the runtime earlier 

Enabling metrics in trivial (adding the `tokio-metrics` crate) , the only question is whether we really need all the metrics (and how often we'd like to send them over.

Below in a print of all the metrics that we can enable 

```
RuntimeMetrics { workers_count: 8, total_park_count: 3, max_park_count: 3, min_park_count: 0, total_noop_count: 1, max_noop_count: 1, min_noop_count: 0, total_steal_count: 0, max_steal_count: 0, min_steal_count: 0, num_remote_schedules: 0, total_local_schedule_count: 2, max_local_schedule_count: 2, min_local_schedule_count: 0, total_overflow_count: 0, max_overflow_count: 0, min_overflow_count: 0, total_polls_count: 2, max_polls_count: 2, min_polls_count: 0, total_busy_duration: 455.521µs, max_busy_duration: 455.521µs, min_busy_duration: 0ns, injection_queue_depth: 0, total_local_queue_depth: 0, max_local_queue_depth: 0, min_local_queue_depth: 0, elapsed: 502.308891ms }
```

**Comment by bonomat** [comment]
I wouldn't know what any of these metrics means 😅
Is there an explanation to it?

**Comment by klochowicz** [comment]
you can see more info: https://docs.rs/tokio-metrics/0.1.0/tokio_metrics/struct.RuntimeMetrics.html#structfield.injection_queue_depth

I'll create a PR that exports them all, with descriptions taken from config (and with a link to the docs), and then we can pick them apart if we decide we don't need some of them.

**Comment by bonomat** [comment]
> Enabling metrics in trivial (adding the tokio-metrics crate) , the only question is whether we really need all the metrics (and how often we'd like to send them over.

Note: you can't configure how often they are being pulled by prometheus as they will all be bundled under the same endpoint under `api/metrics`

> I'll create a PR that exports them all, with descriptions taken from config (and with a link to the docs), and then we can pick them apart if we decide we don't need some of them.

Can I propose a different approach: instead of enabling them and then looking into the metrics, look into the metrics first and decide which we need and then enable them? 
This would save us some time in the case we don't need _any_ ;)

**Comment by bonomat** [comment]
This project is unmaintained
