### ISSUE TITLE
Funding fee information should not live inside `Dlc`

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#2502]
From a modelling perspective, it doesn't make sense to have the `Dlc` struct know about the concept of a `CompleteFee`. A `Dlc` is just a cryptographic vehicle for the financial instrument of a CFD. The complete fee makes sense in the context of our CFDs, but not when talking about DLCs. As such we should try to separate the `Dlc` and `CompleteFee` concepts.

We added the `complete_fee` field to the `RevokedCommit` type with f53125427baa96280bd6fa4d0afe04ba716779e2 in order to be able to keep track of the total fees accrued until a certain point. We probably still want to keep track of this, but it should be on the `Cfd` level.

**Comment by bonomat** [comment]
This project is unmaintained
