### ISSUE TITLE
Develop proc-macro for declaring message handlers on actors

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#251]
Declaring message handlers on actors is quite verbose at the moment.

If we define a few conventions in how we use messages, we can define a proc-macro that takes care of most boilerplate. In particular we want a macro that transforms:

```rust
#[xtra_productivity] // note the name pun
impl Actor {
	async fn update_state(&mut self, msg: Sync) -> Result<()> {
		todo!()
	}
}
```

into this:

```rust
impl Actor {
	async fn update_state(&mut self, msg: Sync) -> Result<()> {
		todo!()
	}
}

// 1. generate an `xtra::Message` impl for the 2nd argument of each function inside the impl block
impl xtra::Message for Sync {
	type Result = (); // by convention, all messages return unit
}

// 2. generate a handler implementation for each function
#[async_trait]
impl xtra::Handler<Sync> for Actor {
    async fn handle(&mut self, msg: Sync, _: &mut xtra::Context<Self>) {
        let result = self.update_state(msg).await; // need to auto-detect whether or not we need to await based on `asyncness` of function

		// in case function returns a `Result`, log the error
		if let Err(e) = result {
			tracing::warn!("");
		}
    }
}
```

Positive test-cases:

1. `async` handler function
2. non-`async` handler function
3. handler function with return value `Result<(), E>`
4. handler function with `xtra::Context`

Negative test-cases:

1. Handler function returning something else other than `Result<(), E>` or `()`

Use https://github.com/dtolnay/trybuild for writing macro tests.

## Trade-offs

To make the macro simpler, we establish some conventions (like disallowing certain return values). This should serve as an 80% solution of our boilerplate. Rather than making the macro more complex to allow for different behaviors, we should just write the `Handler` implementation manually in those situations.

**Comment by thomaseizinger** [comment]
I am having second thoughts on this "log errors within handlers" idea. I think the way forward is to complete what I started in https://github.com/comit-network/hermes/pull/296 and write the proc macro in a way such that the return type of the handler function is the return type of the message.

**Comment by klochowicz** [comment]
@thomaseizinger shall we investigate whether `spaad` would give us enough boilerplate removal as a part of this ticket?

**Comment by thomaseizinger** [comment]
> @thomaseizinger shall we investigate whether `spaad` would give us enough boilerplate removal as a part of this ticket?

Yes, if we can apply it selectively to just handle the `Handler` boilerplate, that would be good enough! I think it doesn't do the `impl Message for XYZ {}` for you based on the handler function's return value so I am not sure if it quite works.

In any case, we can start our macro by forking `spaad`.

**Comment by da-kami** [comment]
#407 and the follow up work in #420 and #415 resolve this ticket. Closing.
