### ISSUE TITLE
Failure to bind to socket on libp2p connection triggers reconnects

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#2514]
If address is already in use, return an error and exit the application instead of letting the supervisor restart the listening actor.
There is no point in trying to restart the actor - user should change the listening port or close app that took it.

Note: this sometimes shows up in tests, when we're trying to bind to the same socket.
on legacy connections, such test would fail early, on libp2p connections a test looks like it failed in different place (ie. it's not obvious the Endpoint could not be correctly established at all).

**Comment by bonomat** [comment]
This project is unmaintained
