### ISSUE TITLE
Add `instrumentation` feature flag to daemon-tests

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#2524]
otel-tests crate requiring grpc-sys greatly increased our build times on CI (where we don't even use it!)

it can even be enabled by default in itchysats for devs convenience (we use incremental compile there, so it shouldn't matter), as long as we override and not compile stuff we don't use in the CI runs and release builds.

**Comment by klochowicz** [comment]
screenshot of `cargo build --timings` result:

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/8319440/180446323-54c3db8c-b0dc-4cbc-8581-d275890614b3.png">

**Comment by Restioson** [comment]
Just to check, are tests still run with `--all-features`? This would lead to a new `instrumentation` feature still being enabled

**Comment by klochowicz** [comment]
> Just to check, are tests still run with `--all-features`? This would lead to a new `instrumentation` feature still being enabled

they don't; they run with default features right now.
