### ISSUE TITLE
Configurable `peer_id` blacklist for the maker

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2527]
We see one peer-id spamming the maker, which is annoying. 

There are some solutions to deal with that that are less restrictive than a blacklist (i.e. find out what peer it is, change log levels, ...), but in the long run a feature to ignore certain peer-ids might actually come in handy for the maker. 

It would be good if we could store this information in the database and create an endpoint to add/delete blacklisted peers.

**Comment by klochowicz** [comment]
would you do this instead or in addition to an IP blacklist? 

I would love to be able to just create a plaintext file that contains blacklist, using DB for that might be an overkill ;p

**Comment by da-kami** [comment]
I think both `peer_id` and `IP address` could be useful, but I think the `peer_id` would be sufficient for now.
I think the IP address is more likely to change than the peer id.

**Comment by Restioson** [comment]
Is there any view as to where (in the filesystem) this block list should be stored?

**Comment by bonomat** [comment]
> Is there any view as to where (in the filesystem) this block list should be stored?

we have a `data_dir` variable. In there anywhere should be fine.
