### ISSUE TITLE
Restricting rollover retry to the latest punishable `commit-txid` of the maker

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2541]
Currently the maker does not restrict rollovers by `commit-txid` which can lead to problems as described in #2282 

Given the new protocol the taker cannot fallback more than one rollover (unless data is deleted from the db which is not considered), because if the taker fails but the maker succeeds the taker is always exactly one rollover behind. If both fail they agree. (A scenario where the maker fails but the taker succeeds is not considered and should never happen because the maker sends last as fire-and-forget.)

The maker restricting rollover from `commit-txid` to the latest punishable `commit-txid` (i.e. current rollover - 1) makes retry safer for the maker.

**Comment by bonomat** [comment]
This project is unmaintained
