### ISSUE TITLE
Allow starting maker and taker in headless mode (ie. without GUI)

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#2544]
[...]
I agree with @bonomat that this behavior can be annoying and I think a flag to disable automatically opening the UI would be useful for test setups for maker and taker.
[...]

_Originally posted by @da-kami in https://github.com/itchysats/itchysats/pull/2495#pullrequestreview-1049803667_

**Comment by bonomat** [comment]
ping @klochowicz : you've been assigned to this since a while. What's the status of this please?
