### ISSUE TITLE
Ping protocol failed

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#2549]
We see plenty of 
`outbound ping protocol failed: Timeout in protocol negotiation`
warnings on mainnet.

Use this loki query to show warnings per peer per 5 minute

```
sum by (fields_peer) (count_over_time({container="maker",setup="mainnet"} |~"ping protocol failed" | json [5m]))
```

**Comment by luckysori** [comment]
Duplicate of #2602.
