### ISSUE TITLE
Environment version always `docker`?

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#2553]
This looks a bit fishy: 

<img width="299" alt="image" src="https://user-images.githubusercontent.com/224613/180943788-518b6600-3eee-4816-9851-425c529228eb.png">

Every 0.5.0 taker connects via docker and we have 0 on umbrel ? 

```
{container="maker",setup="mainnet"} |~"Docker"   | json
```

**Comment by bonomat** [comment]
assigning @da-kami: I think you are about to fix this on umbrel.

**Comment by bonomat** [comment]
ping @da-kami : was this resolved?

**Comment by bonomat** [comment]
ping @da-kami : was this resolved?

**Comment by luckysori** [comment]
@da-kami Did we fix this?

**Comment by bonomat** [comment]
ping @da-kami : has this been resolved?

**Comment by da-kami** [comment]
Sorry for missing the pings, must have accidentally clicked this away in the notifications.
Yes this was fixed with https://github.com/getumbrel/umbrel-apps/pull/85
