### ISSUE TITLE
[Epic] Introduce `order` abstraction and re-design the `cfd` lifecycle

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2555]
With #2292 with introduce the abstraction of an order, but the `Cfd` lifecycle within the daemon is still odd, because we mix order and the `Cfd` together.

I opted to keep this weirdness for now and create this ticket to action a proper `order` abstraction.
Part of this model was already discussed in https://github.com/itchysats/itchysats/issues/1770.

The motivation of this ticket is to design a better model for the lifecycle of a `Cfd`. This will help with creating better boundaries for the APIs, the application flow, the data and the eventually the user experience.

## Recap, `Offer` and `Order` as introduced in #2292

An offer is created by the maker and sent to all connected takers.
An offer has a dedicated id, the `OfferId`.
One offer can be taken be taken multiple times by one/multiple takers.

In order to taker an offer a taker creates an `order`. 
The order is identified by a unique id, the `OrderId`.
The taker proposes the `OrderId` when sending the order to the maker.

## Vision for `Order` and `Cfd`:

As long as the order is not filled, we should treat the order as order.
The order is filled once "contract setup is done", only then we should create the `Cfd`. As "contract setup is done" is not clearly defined, I would opt for defining it as: Once we have a `Dlc` we create the `Cfd` and attach the `Dlc`.

This means, that the `Cfd` lifecylce starts with the negotiated `Dlc`, not with the state on the blockchain. We could also opt for starting the `Cfd` lifecycle once the transaction is in mempool, because only then we can trigger actions to close the position.
The challenge here is where to store the data and how to present it to the user.

Both maker and taker should store orders in their daemon database.
The accept / reject logic should be for the order, not the `Cfd`.
The rollover tables are already separate. 
When rolling over we could opt for creating an `order` as well, that is then filled (i.e. new Dlc upding the Cfd) or not. We can also opt for doing that in a separate iteration.
If we do so, the `Cfd` is either `open` or `closed`, there is not other state.

The user interface *should* display orders and open positions separately. In an intermediary step we can opt for keeping the current display and map the `order`  model to the `projection::Cfd` model. This might be messy though.

**Comment by bonomat** [comment]
> An offer is created by the maker and sent to all connected takers.
> An offer has a dedicated id, the `OfferId`.
> One offer can be taken be taken multiple times by one/multiple takers.

One note on this: 
I think an `order` should _consume_ an `offer`. If the `offer` had a range from `100`-`1000` and someone creates and `order` of amount `300` which gets accepted, the remaining amount in the `offer` should be reduced by said amount, i.e. the `offer` is updated with `100`-`700`.

**Comment by da-kami** [comment]
> > An offer is created by the maker and sent to all connected takers.
> > An offer has a dedicated id, the `OfferId`.
> > One offer can be taken be taken multiple times by one/multiple takers.
> 
> One note on this: I think an `order` should _consume_ an `offer`. If the `offer` had a range from `100`-`1000` and someone creates and `order` of amount `300` which gets accepted, the remaining amount in the `offer` should be reduced by said amount, i.e. the `offer` is updated with `100`-`700`.

After discussion with @bonomat here are some notes for completion:

When we merged https://github.com/itchysats/itchysats/pull/1455 we automatically replicated the `offer` (previously called `order`) in the maker daemon upon a taker taking it. A new `offer`, with a new id, was automatically sent out to all takers without interaction of the automation.
What we call "offer" became more of a "maker terms" feed when this merged.
The automation was and is still able to change the terms, but only when the terms are being changed we send an update to the taker.

With https://github.com/itchysats/itchysats/pull/2292 we took this one step further. Instead of re-creating the terms upon taking an `offer` we just keep the offer with the same id in place and allow multiple takers to take it.

As @bonomat pointed out this is not a step towards an orderbook, because the offer of the maker should be matched with an order, and when filling the order the offer should be reduced of removed (removed if order gets completely filled). 
But the model for such a solution is quite different. At the moment we don't have an orderbook, and we have a better UX if the don't send updates from maker to taker after a taker placing an order. We have not decided yet how the maker interacts with the orderbook and how the orderbook handles order matching.

We agreed to keep the current changes in place and re-design this part once we introduce the orderbook. 

---

Independent of the discussion about `offer` and `order`, I still think we should create a clear boundary between `order` and `cfd`. With that change we can evolve the UI towards a solution based on an orderbook. An order history would also help users relate the product to other trading user interfaces.

**Comment by da-kami** [comment]
Note: Converted this into an `Epic` because I think it is too big to just action this. I think we have to define the boundaries of this more clearly. @Restioson since you invested some exploratory work into this ticket already maybe we can have a chat these days to chunk this up and then work on it together!

**Comment by Restioson** [comment]
Sure, sounds good!

**Comment by bonomat** [comment]
This project is unmaintained
