### ISSUE TITLE
Make `order` protocol more resilient against failing on one side

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2563]
The `order` protocol introduced in #2292 uses `setup_contract::new` for executing the protocol. In this function both parties first send and then wait to receive a message. 
We have seen behavior with the new protocol stack, where one party succeeds with rollover while the other one fails.
If this happens on the last message (the `ack` `Msg3`) of contract setup with can result in a situation where one party publishes lock, but the other party discards it. 
This will lead to a `force close` scenario where one party is not even aware that there is an active position.

For rollover we were working on overcoming disagreement:
We refactored rollover to ensure the message order in #2248.
Additionally we introduced rollover 2.0 with #2272 that ensures that the maker fires and forgets the last message.

A contract setup cannot be retried by the taker.
We could still opt for making the message order more deterministic as in #2248, but ultimately that does not solve the problem. 
As an in between solution we could opt for only letting the `taker` publish lock, i.e. remove publication on the `maker` side. I described this "feature" in https://github.com/itchysats/itchysats/issues/2564

I think the only proper way to overcome this, is by monitoring for `lock` on either side once we sent a signature. This was initially described in https://github.com/itchysats/itchysats/issues/364

This would require:

1. Storing the "unfinished" Dlc
2. Monitoring for lock
3. If lock was not published until a timeout is reached, then ensure to spend the UTXO otherwise. (to ensure we cannot be "held hostage")

**Comment by bonomat** [comment]
This project is unmaintained
