### ISSUE TITLE
Only the `taker` publishes `lock` to avoid bad UX

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2564]
As described in https://github.com/itchysats/itchysats/issues/2563 we can run into scenarios where one party publishes `lock`, but the other party discards the contract setup as failed.

Until we action the solution described in https://github.com/itchysats/itchysats/issues/2563 we could opt for removing `lock` publication on the `maker` side, and assume that the `taker` always publishes lock upon finishing contract setup.
This is to avoid scenarios where the taker is in a situation where the maker published `lock`, but the taker is not aware of it. This can also happen for the maker, which is a bad UX for the taker as well, because the position will get force closed.

To avoid this problem for now I propose:

1. Ensure the message order. The taker always sends first, the maker always receives first (except from the ack!)
2. The taker is the one publishing lock.
3. We keep the `ack`s in place, the maker sends first, the taker receives first.
    1. If the taker  receive the `ack` we publish `lock` and fire and forget the taker's `ack` as last message.
    2. If the maker receives the `ack` of the taker (the last message being sent) everything is good.
    3. If the maker does not receive the `ack` of the taker we still go on *but print a warning* to know that this position might not get published on chain
    4. If the taker does not receive the `ack` of the maker we fail the protocol on the taker side and don't publish `lock`. For the maker this will result in the *warning* mentioned above and a position that is `Open` even though it does not go on chain.

**Comment by bonomat** [comment]
There is one more thing to consider: the maker's wallet. 
Right now we block used [utxo's for some time](https://github.com/itchysats/itchysats/blob/0883ec4d188d26b1d83e98ba86c1f271d6f7d8a0/daemon/src/wallet.rs#L129). If a taker repeatably fails, this will maneuver the maker into a stale position for some time where all the utxo's seem to be locked. 

I believe this ticket does not add much more guarantees than we have before and might bring other problems. Hence, I propose to go for https://github.com/itchysats/itchysats/issues/2563 right away.

**Comment by da-kami** [comment]
> I believe this ticket does not add much more guarantees than we have before and might bring other problems. Hence, I propose to go for https://github.com/itchysats/itchysats/issues/2563 right away.

I like that, I'll see to push for getting https://github.com/itchysats/itchysats/issues/2563 into one of the next iterations!
@luckysori if you feel different feel free to re-open this ticket!

**Comment by luckysori** [comment]
> I like that, I'll see to push for getting #2563 into one of the next iterations! @luckysori if you feel different feel free to re-open this ticket!

I am in favour of going in the direction proposed in #2563, so I'm happy to close this.
