### ISSUE TITLE
Short liquidation events when maker goes short are unusable

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#2571]
### Context

A liquidation event that will only unlock a liquidation CET if the price the oracle attests to is _exactly_ `$XYZ` is not very useful. This is because it is incredibly unlikely that the oracle will attest to any one value. The point of liquidation CETs is that they can be activated _below or above_ a certain value.

### Problem

Unfortunately, the short liquidation events we generate when the maker goes short depend on a single price value. There are two reasons why this happens:

- We choose the liquidation price intervals based on the lowest and highest intervals returned by `payout_curve::calculate`:

https://github.com/itchysats/itchysats/blob/5f3d4978c80add3b54f04c4e0c540d7bdc9746af/model/src/payouts.rs#L99-L100

- The last interval returned by `payout_curve::calculate` when the maker goes short is actually just a single value.

### What to do?

I'm not exactly sure. We could consider:

- Using more than one payout interval (more CETs).
- Constructing the offending payout intervals manually.
- Fixing our payout curve so that this doesn't happen. I think this is an inherent limitation of our inverse payout curve that we have been ignoring and it has to do with the fact that we have an arbitrary limit on how high the payout curve can go.

**Comment by bonomat** [comment]
I think this is a bug and labeled it that way.

**Comment by bonomat** [comment]
> Fixing our payout curve so that this doesn't happen. I think this is an inherent limitation of our inverse payout curve that we have been ignoring and it has to do with the fact that we have an arbitrary limit on how high the payout curve can go.

I think this is the preferred approach. Do you have a plan how to approach this? 

Alternatively, this could be a possibly simple fix: 
> Constructing the offending payout intervals manually.

**Comment by luckysori** [comment]
> > Fixing our payout curve so that this doesn't happen. I think this is an inherent limitation of our inverse payout curve that we have been ignoring and it has to do with the fact that we have an arbitrary limit on how high the payout curve can go.
> 
> I think this is the preferred approach. Do you have a plan how to approach this?

I had a brief look and I find the code hard to modify, because I lack the expertise. Fortunately we have:

1. A test that will tell us if the bug is fixed.
2. A test that will tell us if we introduce a regression.

So we can at least take a stab at it.

> Alternatively, this could be a possibly simple fix:
> 
> > Constructing the offending payout intervals manually.

I wonder if we should generally do this even without this bug. I don't understand why the payout curves we generate don't go from zero to `olivia`'s maximum BTCUSD attestation price. It's highly unlikely that it matters, but why risk it?

Having to post-process the last interval won't be very elegant, but it would kill two birds with one stone and it should be simple enough.

**Comment by bonomat** [comment]
Am I correct with the assumption that we have to fix this for supporting quanto perpetual contracts? Because then we will have potential liquidation points on both sides.

**Comment by luckysori** [comment]
> Am I correct with the assumption that we have to fix this for supporting quanto perpetual contracts? Because then we will have potential liquidation points on both sides.

I agree that it's more important to not run into this bug for quanto CFDs. But we won't be using the same payout curve for them and I don't think we'll introduce the same bug when implementing the new payout curve module (I'll add a test).

**Comment by bonomat** [comment]
aahh... makes sense 👍

**Comment by luckysori** [comment]
Reopening because of https://github.com/itchysats/itchysats/pull/2814.
