### ISSUE TITLE
Failed to sync wallet

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#2577]
Recently we are seeing wallet sync errors on mainnet: 

```
{"timestamp":"2022-07-28T21:43:36.807562729Z","level":"WARN","fields":{"message":"Syncing failed: Failed to sync wallet: Electrum(AllAttemptsErrored([JSON(Error(\"EOF while parsing a value\", line: 1, column: 0))]))"},"target":"daemon::wallet","span":{"name":"Handle Sync"}}
```

**Comment by Restioson** [comment]
I've seen warnings reminiscent of this locally running `dev-taker` - possibly related?

**Comment by klochowicz** [comment]
Should we raise the priority of upgrading to bdk 0.20? They have fixed a few issues re: wallet sync there.

**Comment by bonomat** [comment]
> Should we raise the priority of upgrading to bdk 0.20? They have fixed a few issues re: wallet sync there.

Let's drop our old protocols first so that we don't have to maintain multiple versions of [maia](https://github.com/comit-network/maia/)

**Comment by bonomat** [comment]
This project is unmaintained
