### ISSUE TITLE
Payout curve is not always a function

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#2586]
With https://github.com/itchysats/itchysats/pull/2570/commits/f8c415d2462cec4853ee1627a32622682e6ccc7e we added a test that shows that our inverse payout curve implementation (the one used for the contract symbol `BTCUSD`) does not always discretise into price intervals that are [monotonically increasing](https://en.wiktionary.org/wiki/monotonic_increasing).

This is a bug, because if a price interval can decrease it means that it will overlap with the previous price interval generated. That would cause the activation of more than one CET if the oracle attests to a price that belongs to multiple intervals! That would create a race condition between the publication of all the active CETs, which our software doesn't and shouldn't account for. Furthermore, the payout curve is actually expected to be a _function_, in the sense that every price should be assigned _exactly one_ payout. This is important because otherwise we would need to decide between different CETs after an attestation, a complexity that is unnecessary and unwanted.

**Comment by bonomat** [comment]
This project is unmaintained
