### ISSUE TITLE
Investigate frequent protocols failures

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2602]
I noticed this in my taker's logs on Umbrel:

```
2022-08-01 12:11:31 DEBUG fallible task handle_error{err=The stream has terminated.}: xtra_libp2p_offer::taker: Failed to process maker offers: The stream has terminated. peer=12D3KooWP3BN6bq9jPy8cP7Grj1QyUBfr7U6BeQFgMwfTTu12wuY
2022-08-01 12:17:08 DEBUG fallible task handle_error{err=unexpected end of file}: xtra_libp2p_ping::pong: Inbound ping protocol failed: unexpected end of file peer=12D3KooWP3BN6bq9jPy8cP7Grj1QyUBfr7U6BeQFgMwfTTu12wuY
2022-08-01 12:17:46 DEBUG fallible task handle_error{err=The stream has terminated.}: xtra_libp2p_offer::taker: Failed to process maker offers: The stream has terminated. peer=12D3KooWP3BN6bq9jPy8cP7Grj1QyUBfr7U6BeQFgMwfTTu12wuY
2022-08-01 12:23:39 DEBUG fallible task handle_error{err=unexpected end of file}: xtra_libp2p_ping::pong: Inbound ping protocol failed: unexpected end of file peer=12D3KooWP3BN6bq9jPy8cP7Grj1QyUBfr7U6BeQFgMwfTTu12wuY
2022-08-01 12:25:39 DEBUG fallible task handle_error{err=The stream has terminated.}: xtra_libp2p_offer::taker: Failed to process maker offers: The stream has terminated. peer=12D3KooWP3BN6bq9jPy8cP7Grj1QyUBfr7U6BeQFgMwfTTu12wuY
2022-08-01 12:27:42 DEBUG fallible task handle_error{err=The stream has terminated.}: xtra_libp2p_offer::taker: Failed to process maker offers: The stream has terminated. peer=12D3KooWP3BN6bq9jPy8cP7Grj1QyUBfr7U6BeQFgMwfTTu12wuY
2022-08-01 12:29:42 DEBUG fallible task handle_error{err=The stream has terminated.}: xtra_libp2p_offer::taker: Failed to process maker offers: The stream has terminated. peer=12D3KooWP3BN6bq9jPy8cP7Grj1QyUBfr7U6BeQFgMwfTTu12wuY
2022-08-01 12:31:43 DEBUG fallible task handle_error{err=The stream has terminated.}: xtra_libp2p_offer::taker: Failed to process maker offers: The stream has terminated. peer=12D3KooWP3BN6bq9jPy8cP7Grj1QyUBfr7U6BeQFgMwfTTu12wuY
2022-08-01 12:37:01 DEBUG fallible task handle_error{err=The stream has terminated.}: xtra_libp2p_offer::taker: Failed to process maker offers: The stream has terminated. peer=12D3KooWP3BN6bq9jPy8cP7Grj1QyUBfr7U6BeQFgMwfTTu12wuY
```

This error keeps happening quite consistently every 2-3 hours. It usually resolves itself after some time, but given the timeframe my taker actually my have an outdated offer for some time until it succeeds again.

**Comment by da-kami** [comment]
For `ping` I was able to match the failures on the maker side:

```
	2022-08-01 12:23:37	
{"timestamp":"2022-08-01T12:23:37.563716817Z","level":"WARN","fields":{"message":"Outbound ping protocol failed: Timeout in protocol negotiation","peer":"12D3KooWCeU5dVvHQqy1Sy8hfSbxqNS6YMCyfGUc6btDQChdhq9x"},"target":"xtra_libp2p_ping::ping","span":{"err":"Timeout in protocol negotiation","name":"fallible task handle_error"}}
	
2022-08-01 12:23:37	
{"timestamp":"2022-08-01T12:23:37.563685516Z","level":"ERROR","fields":{"error":"Timeout in protocol negotiation"},"target":"xtra_libp2p::endpoint","span":{"peer":"PeerId(\"12D3KooWCeU5dVvHQqy1Sy8hfSbxqNS6YMCyfGUc6btDQChdhq9x\")","protocols":"[\"/ipfs/ping/1.0.0\"]","name":"open_substream"}}
	
2022-08-01 12:23:37	
{"timestamp":"2022-08-01T12:23:37.563639689Z","level":"ERROR","fields":{"message":"Future timed out","err":"deadline has elapsed"},"target":"tokio_extras::time","span":{"peer":"PeerId(\"12D3KooWCeU5dVvHQqy1Sy8hfSbxqNS6YMCyfGUc6btDQChdhq9x\")","protocols":"[\"/ipfs/ping/1.0.0\"]","name":"open_substream"}}
	
2022-08-01 12:17:08	
{"timestamp":"2022-08-01T12:17:08.014569812Z","level":"WARN","fields":{"message":"Outbound ping protocol failed: Timeout in protocol negotiation","peer":"12D3KooWCeU5dVvHQqy1Sy8hfSbxqNS6YMCyfGUc6btDQChdhq9x"},"target":"xtra_libp2p_ping::ping","span":{"err":"Timeout in protocol negotiation","name":"fallible task handle_error"}}Show context
	
2022-08-01 12:17:08	
{"timestamp":"2022-08-01T12:17:08.014536363Z","level":"ERROR","fields":{"error":"Timeout in protocol negotiation"},"target":"xtra_libp2p::endpoint","span":{"peer":"PeerId(\"12D3KooWCeU5dVvHQqy1Sy8hfSbxqNS6YMCyfGUc6btDQChdhq9x\")","protocols":"[\"/ipfs/ping/1.0.0\"]","name":"open_substream"}}
	
2022-08-01 12:17:08	
{"timestamp":"2022-08-01T12:17:08.014505503Z","level":"ERROR","fields":{"message":"Future timed out","err":"deadline has elapsed"},"target":"tokio_extras::time","span":{"peer":"PeerId(\"12D3KooWCeU5dVvHQqy1Sy8hfSbxqNS6YMCyfGUc6btDQChdhq9x\")","protocols":"[\"/ipfs/ping/1.0.0\"]","name":"open_substream"}}
	
2022-08-01 12:14:36	
{"timestamp":"2022-08-01T12:14:36.593100977Z","level":"WARN","fields":{"message":"Outbound ping protocol failed: unexpected end of file","peer":"12D3KooWCeU5dVvHQqy1Sy8hfSbxqNS6YMCyfGUc6btDQChdhq9x"},"target":"xtra_libp2p_ping::ping","span":{"err":"unexpected end of file","name":"fallible task handle_error"}}
```

It appears that when the protocol negotiation times out on the maker side we see `unexpected end of file` on the taker.
For `offers` we don't have enough information because failure to send offers on the maker is only printed on `debug`, which will be changed by https://github.com/itchysats/itchysats/pull/2585

**Comment by da-kami** [comment]
I'm adding the bug label, because for my taker this happens so frequently, that after taking an `offer` I am unable to trade, because I just don't get new ones.
Only after about 10 minutes I was able to trade again, because finally the protocol succeeded.

**Comment by bonomat** [comment]
Related to (somewhat duplicated of) https://github.com/itchysats/itchysats/issues/2549

**Comment by Restioson** [comment]
This is reflected on mainnet's side - almost every ping-all-peer span contains a timeout :grimacing: 

[Search for all ping peer spans in Tempo](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-traces%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22queryType%22:%22nativeSearch%22,%22serviceName%22:%22maker-mainnet%22,%22spanName%22:%22ping%20peer%22,%22minDuration%22:%22%22,%22maxDuration%22:%22%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D&right=%7B%22datasource%22:%22grafanacloud-itchysats-traces%22,%22queries%22:%5B%7B%22query%22:%226f116089782eef5595b524e1d9b0ed59%22,%22queryType%22:%22traceId%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%221659429050188%22,%22to%22:%221659432650188%22%7D%7D)

**Comment by da-kami** [comment]
This is likely *not* directly related, but we do also experience the `rollover` protocol failing over longer periods of time. I captured such an instance in #2669

**Comment by da-kami** [comment]
@holzeis here is a short summary of the knowledge I collected when looking into the issue of the connection "not being stable" before.

- We observe error more frequently when the `maker` opens a substream against all `taker`s. However, the frequency of protocols triggers where the maker opens a substream is likely related to the frequency of running into errors.
    - Protocols where the taker opens a substream and the maker listens: `order`, `rollover`, collab-settlement`
        - `rollover` is triggered every 5 minutes until it succeeds, then it is triggered after 2 hours again
             - We *do* sporadically run into errors with `rollover`, see e.g. https://github.com/itchysats/itchysats/issues/2669 
        - `order` is triggered only when the user triggers placing an order (no automatic, periodic trigger)
        - `collab-settlement` is triggered only when the user closes a cfd (no automatic, periodic trigger)
    - Protocols where the maker opens a substream and the taker listens: `ping`, `id`, `offers` 
        - `ping is triggered every 5 minutes
        - `id` is triggered once upon connection establishment
        - `offers` is triggered whenever the maker sends out a new `offer` and upon connection establishment

## Discussed in the past

### Message congestion in xtra 

In the past we were uncertain if the connection problems are actually related to the connection management, or are just because of how we set up the connection and protocol management using our actors.
There could be message congestion in the `xtra` actors handling connection related messages. 

The `Endpoint` may be a bottleneck on the `maker` because all connections are handled by this one `Actor`
When we triggered the `ping` protocol every `5` seconds we could prove that there was message congestion in the endpoint, because it happened that we triggered the next protocol iteration before the first one finished, resulting in more and more trigger messages piling up.  

The protocol actors may be a bottleneck on the `maker` because we handle multiple takers within one protocol actor

Message congestion problem were tackled by unblocking the message handlers by spawning a task for the work to be done by e.g. a protocol execution. The reasoning is that if the actor's handler is not blocked there should not be congestion.
Note that this results in quite a log of tasks to be executed in the `maker`. We did not evaluate if that would cause other trouble.
Additionally we started prioritizing messages recently (#2426 ) so that internal messages get processed before external ones

### `yamux` configuration 

Given the added load tests on the itchysats ( #2403 )  and the [`yamux` library tests](https://github.com/libp2p/rust-yamux/blob/master/tests/concurrent.rs) we don't suspect that yamux should be a problem, but we might not have it configured / used in the best way for our protocols. 

Examples:

When implementing the rollover protocol we changed the configuration because we had trouble with `rollovers` in the test, because the rollover messages are so big, see:

https://github.com/itchysats/itchysats/blob/master/xtra-libp2p/src/upgrade.rs#L59-L91

We never came around to change that back.

Additionally we noticed that the way we chose to open a substream might not be optimal given that we always pass in a `vec` of exactly one protocol here: 

https://github.com/itchysats/itchysats/blob/master/xtra-libp2p/src/upgrade.rs#L135-L155


---

Some more comments on what happened in the past: 

Initially connection related problems were driven by the `rollover` protocol failing, because that could lead to scenarios where the `taker` and the `maker` disagree on the rollover state, which results in consecutive rollovers failing and the cfd getting force-closed eventually. This was captured in https://github.com/itchysats/itchysats/issues/2263

We overcame that problem by making the rollover protocol more resilient ( #2272 ), but the underlying problem that the connection is not stable was not solved.

**Comment by Restioson** [comment]
> This is likely not directly related, but we do also experience the rollover protocol failing over longer periods of time. I captured such an instance in https://github.com/itchysats/itchysats/issues/2669

If this is the same issue, that would imply we should prioritise this a bit higher... if I remember, in the past we had discussed how this was an issue but not necessarily super high, priority, as then it didn't seem to be affecting rollovers at all... :sweat_smile:

**Comment by da-kami** [comment]
@holzeis and me did another session of debugging and here are the results:

## Endpoint is sometimes not notified about connection drops

We were able to reproduce a scenarios where the [`maker` endpoint does not record a `ConnectionDropped` event](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22maker%5C%22,setup%3D%5C%22testnet%5C%22%7D%20%20%7C%3D%5C%2212D3KooWPwBREmtChEbHczDxB8jpL4tJoN1eh7TWCbTti7jxkZXg%5C%22%20%7Cjson%22%7D%5D,%22range%22:%7B%22from%22:%221660206080972%22,%22to%22:%221660206772935%22%7D%7D), but we see `Connection established` in the logs without a drop in between. 

This problem was reproduced by non-gracefully killing the application process and could amount for a good amount of the `ERROR`s in the logs. By solving / removing this issue it will be easier to drill down on remaining problems to understand them in detail.

This is a specific, reproducible problem and was captured by adapting https://github.com/itchysats/itchysats/issues/2554

## Issues with Daniel's taker that cannot be explained yet

This *could* be related to the issue above, but we could not prove that deterministically. 

We found several instance in the [logs](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22maker%5C%22,setup%3D%5C%22mainnet%5C%22%7D%20%20%7C%3D%5C%2212D3KooWCeU5dVvHQqy1Sy8hfSbxqNS6YMCyfGUc6btDQChdhq9x%5C%22%20%7C~%5C%22Connection%20established%7CConnection%20dropped%7CWARN%7Ccompleted%7CERROR%5C%22%20!%3D%5C%22legacy_rollover::Actor%5C%22%20%7Cjson%22%7D%5D,%22range%22:%7B%22from%22:%221659608310941%22,%22to%22:%221660210347003%22%7D%7D), where my Umbrel `taker` connected without a recorded `Connection dropped` before. This could be related to upgrading ItchySats, but it is definitely not expected behavior. I don't think I non-gracefully exited the application during that timeframe (initially I though these could be cases where I unplugged the raspi, but they are not, it should have been running stable during that time). 

Further investigation needed before opening a specific issue.

The same query reveals that in a timeframe where we though to have a connection (i.e. after `Connection established` in the logs, no `Connection dropped`) the `maker` reported problems when opening substreams, but my `taker` succeeded rolling over periodically. This is somewhat odd, because if the connection was stale or otherwise broken we would expect to have trouble to open a substream on both sides. Even if a `Connection dropped` was not reported back to the `maker` endpoint it cannot be explained how the `taker` succeeded with rollovers.

## Other findings

Overall, it appears that certain peers have more problems than others:

![image](https://user-images.githubusercontent.com/5557790/184124059-852e8891-ae97-487b-a4a5-2db69db84586.png)

This was observed using [this query](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcontainer%3D%5C%22maker%5C%22,setup%3D%5C%22mainnet%5C%22%7D%20%7C~%5C%22Outbound%20ping%20protocol%20failed%7CConnection%20established%7CConnection%20dropped%5C%22%20%7Cjson%22%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D) and then checking the stats on `peer_id`; the query only captures `24h`.

**Comment by klochowicz** [comment]
We hope to get more information about protocol failures by addressing #2825 (we sometimes see rollover problems there).

**Comment by luckysori** [comment]
### What happens if a `taker` goes to sleep

If the computer running the `taker` goes to sleep[1], the `maker` does not immediately understand the connection should be dropped. That is because we simply time out every time to attempt to dial the sleeping `taker`.

Eventually we do get to drop the connection, because `yamux` emits the following error:

```
socket error: decode error: i/o error: No route to host (os error 113)
```

This leads to us seeing this on the `Endpoint`:

```
Connection failed: Substream listener closed
```

#### Proof

1. Grafana [shows](https://itchysats.grafana.net/goto/Kd-LvnS4z?orgId=1) that we got offer protocol timeouts on the `maker` for a particular `taker` that I was running locally, for around 15 minutes after 2022-10-11 01:05:37 AEDT.
2. My Windows event logs show that I sent the computer to sleep a few seconds earlier:

![image](https://user-images.githubusercontent.com/9418575/194991187-6664361c-81ff-4766-aa62-c73ab98477f8.png)

#### Possible solution

I did suggest in our internal team chat to perhaps drop the connection every time we run into protocol negotiation timeouts. But I have changed my mind now that I have realised that the connection is eventually dropped.

Furthermore, I don't believe our constant protocol negotiation timeouts on `mainnet` are caused by takers who are actually asleep. Protocol negotiation timeouts are intermingled with successful protocols e.g. [this taker](https://itchysats.grafana.net/goto/XmGxFnIVz?orgId=1).

[1]: This was tested on WSL, by sending the host to sleep.

**Comment by luckysori** [comment]
### Protocol timeouts mostly happen with remote peers

With our testnet VM we have the opportunity to compare how the `maker` behaves when connecting to local nodes (`taker_master`, `taker_release` and `taker_release_minus_one`) versus remote nodes (any `taker` we run in our development environments against the testnet `maker`). This is irrelevant in production, because peers will always be remote. But it is helpful for debugging problems such as the one described in this ticket.

Firstly, we [cannot see a single instance of a protocol negotiation timeout](https://itchysats.grafana.net/goto/Z7u3F7SVz?orgId=1) for any of the deployed takers on the testnet VM. We know that this is not the case for takers that we run outside of the VM (hard to provide proof, but this is generally accepted).

More importantly, ["remote" takers disproportionately dominate the number of protocol timeouts caused on the `maker`](https://itchysats.grafana.net/goto/7HHMh7S4k?orgId=1). Over the last 30 days:

- The `taker_master` container reports 0 protocol negotiation timeouts.
- The `taker_release` container reports 50 protocol negotiation timeouts.
- The `taker_release_minus_one` container reports 212 protocol negotiation timeouts.
- All other takers account for thousands[1] of protocol negotiation timeouts.

These observations are in line with what we see in production, where all the `taker`s are remote.

#### Theories

I have to confess that I still have not found an explanation for what we experience. But our observations seem to suggest that the problems are related to the actual connection:

- When established locally, it appears to be working correctly most of the time.
- When established over the internet, we very frequently timeout when negotiating substreams.

This suggests to me that the problem is not the `Endpoint`'s ability to dial/listen in a timely fashion. If that were the case, there shouldn't be any difference between the frequency of failed protocol negotiations for local and remote peers.

The `Endpoint` being the problem was my theory all along, but I no longer believe that.

[1]: Grafana only counts up to the last 1000 matches AFAIK.

**Comment by bonomat** [comment]
This project is unmaintained
