### ISSUE TITLE
Configure quanto payout curve using `settlement_payout_interval_size`

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#2632]
With #2618 we have introduced a `model::payouts::quanto` module which allows us to create payouts based on a quanto curve. For this we use the same parameters we use for `model::payouts::inverse` plus a `multiplier`.

We would like to replace the `n_payouts` parameter with `payout_interval_size` (aka `step`), to control the size of all the settlement payout intervals. The relationship between the two parameters is

```
settlement_payout_interval_size = (short_liquidation_threshold - long_liquidation_threshold) / (n_payouts - 2)
```

where the `2` accounts for the two liquidation payouts.

The use of `n_payouts` was allowing us to control the number of CETs produced per CFD (linear relationship), whereas the new parameter gives us direct control over the resolution of our discretisation. We will have to keep that in mind in order to not unknowingly create CFDs with too many CETs.

_Originally posted by @bonomat in https://github.com/itchysats/itchysats/pull/2618#discussion_r938344427_

**Comment by bonomat** [comment]
This project is unmaintained
