### ISSUE TITLE
Save `reason` and `error` for rejected/failed collab settlement in db

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2648]
At the moment the API for `model::Cfd::reject_collaborative_settlement` and `model::Cfd::fail_collaborative_settlement` is misleading, because we pass in a rejection `reason` and a failed `error`, but this information is *not* stored in the database.

We only use this information for logging.
I am not sure logging in the model is a good practice, but given that it simplifies and harmonizes the logs (otherwise we have to ensure that the caller always logs correctly) I would keep that.

However, we should not pass information that the model that is not state relevant. 
There is an old `TODO` to save the rejection `reason` and failed `error` into the db:

https://github.com/itchysats/itchysats/blob/b7d49fdf8cd68872a63e9e0cb913df122355c08f/model/src/cfd.rs#L423-L426

I think we should action this.

**Comment by bonomat** [comment]
This project is unmaintained
