### ISSUE TITLE
Fetch ETHUSD oracle data from Olivia

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#2659]
This includes announcements and attestations. Currently we assume that this data always corresponds to BTCUSD, so we might need to add a `ContractSymbol` to certain types.

Until Olivia actually starts supporting these events we won't be able to use/test these changes. For the time being we can assume that the event IDs will be of the form:

```
/x/BitMEX/BETH/2022-08-02T00:00:00.price?n=20
```

This would conform to BitMEX's symbol for this index: https://www.bitmex.com/app/index/.BETH.

**Comment by klochowicz** [comment]
Blocked, pending oracle update

**Comment by bonomat** [comment]
> Blocked, pending oracle update

We could implement everything and only update the url once we the oracle has been updated
