### ISSUE TITLE
`rollover` protocol fails for `90` minutes

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2669]
Just experienced a scenario where my Umbrel `taker` was unable to roll over with the maker for 90 minutes. 
To gather some more data I attached the `debug` logs for the time in question.

The logs are recorded from the last `RolloverCompleted` event recorded at `UTC 08:
18` until the next successful rollover at `UTC 11:34` In between the application recorded 18 failed attempts starting at `UTC 10:03` until a `RolloverCompleted` was recorded at `UTC 11:34`. 

[2022-08-09 08:18:53_taker_logs_no_rollover.txt](https://github.com/itchysats/itchysats/files/9290081/2022-08-09.08.18.53_taker_logs_no_rollover.txt)

**Comment by luckysori** [comment]
@da-kami: Is there anything that we can do with this ticket or should we just close it?

**Comment by da-kami** [comment]
I think it might just be related to the "bad connection" - given that we already have a ticket - #2602  - where we collect this information we can just close it.
