### ISSUE TITLE
Log spam

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#2720]
Sorry if this was reported before. It looks like a bit more than a week ago we started spamming the logs. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/224613/185538058-93c85205-efed-4dcb-9431-2ed71ee8ce4c.png">

It's still within the bounds but an increase from 53mb to 830mb is questionable. 

My gut feeling says we started logging our CFDs/DLCs somewhere.

**Comment by Restioson** [comment]
We discussed this a bit on matrix and it seems to coincide with disabling the verbose spans. My theory is that when a log is in a span, it gets counted toward trace usage, and when it's not, it gets counted toward log usage. Therefore, less spans means more log usage, perhaps. I'm not sure if this is the case but we could check with grafana how they could it.

Overall, I wouldn't expect any increase just from disabling verbose spans as all it does is disable a few spans, and it doesn't create any log events. It's possible that we misatrributed the increase to this, though.

**Comment by Restioson** [comment]
Actually, I am not 100% sure this is to do with verbose spans anymore. Compare these three graphs:

![image](https://user-images.githubusercontent.com/6688948/185576489-e48c9a13-452a-4033-b5f1-45513927bf5a.png)

![image](https://user-images.githubusercontent.com/6688948/185576525-dfe19399-fae8-4c9e-8e2e-1fd2f5fa2402.png)

![image](https://user-images.githubusercontent.com/6688948/185576685-a87280fd-e6ce-4371-9d8d-2e1ab6bdd8c7.png)

There is actually more than one relevant restart. Logs seem to only start going up in usage a couple hours after tracing goes down in usage. I am not sure if it could be related to deployments, though.

**Comment by da-kami** [comment]
🤔 Interesting.
I had a quick search through the logs but did not find logs that would log the `dlc` / `cets` so far.
Do I read this graph correctly, that we are having a quite constant high ingestion rate? i.e. there are just overall more logs?

**Comment by Restioson** [comment]
>  Do I read this graph correctly, that we are having a quite constant high ingestion rate? i.e. there are just overall more logs?

I think so, yea. I just realised that the restarts graph is only for testnet maker - maybe misleading? It does seem that trace usage drops coincides with the first restart dot, and the log increase coincides with the last (quite hard to see) cluster of restarts. Are we sure nothing else changed? Otherwise we could always try re-enabling `--verbose-spans` and see if that changes things or not.

**Comment by luckysori** [comment]
Fixed with https://github.com/itchysats/cloud-conf/pull/139.
