### ISSUE TITLE
Delete empty CFDs from the database

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#2724]
This is mostly harmless, but now that the taker logs an error every time it fails to auto-rollover a CFD because of a missing DLC, we [see these false positive errors constantly](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bsetup%3D%5C%22testnet%5C%22%7D%20%7C%3D%20%60Cannot%20auto-rollover%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%221660900863384%22,%22to%22:%221660907132154%22%7D%7D).

An empty CFD is one that has no events attached to it. This can happen if the taker tries to place an order and the maker never replies.

---

Alternatively we could somehow prevent the auto-rollover error from being logged if it is about an empty CFD.

**Comment by bonomat** [comment]
This project is unmaintained
