### ISSUE TITLE
Use dedicated serialisation of contract symbol in `position_metrics`

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#2753]
🔧 I know it's a bit annoying but it would be good to have a dedicated type (or simply some specific serialisation logic) in `position_metric` instead of this.

I can see my future self changing this and breaking the metrics by mistake.

_Originally posted by @luckysori in https://github.com/itchysats/itchysats/pull/2752#discussion_r955742901_

**Comment by bonomat** [comment]
This project is unmaintained
