### ISSUE TITLE
Fix displayed liquidation price for ETHUSD offer

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#2754]
Due to the way the liquidation price is calculated for quanto payout curves, after we merge #2742 we will display incorrect liquidation prices for ETHUSD offers.

Check the thread linked below for full context and proposed solutions.

_Originally posted by @luckysori in https://github.com/itchysats/itchysats/pull/2742#discussion_r953713156_

**Comment by bonomat** [comment]
I don't see a way how we can compute this in the backend and display it in the frontend without going back end forth. I'll compute the liquidation price in the frontend only.
