### ISSUE TITLE
Profit calc should be based on payouts

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#278]
At the moment we just use the current price, which is not "wrong" but not actually what the user will get, which is what the payout curve defines. We can call it an `estimate` for now and optimize to use the actual payout curve later.

We already lock the `profit` with the price that was used for the actual `payout` once we have an attestation or collaborative settlement. 

I would recommend to go one step further and do this: 

1. Change the payout to take the current price into account and always return a `payout` (no option, the `None` path would be based on the current price)
2. Calculate the `profit` based on the `payout` as `profit = payout - margin`

I think that should simplify things. The current profit calculation would partly move into the `None` path of the `payout`.

**Comment by thomaseizinger** [comment]
Moving this out of `MVP`.

**Comment by DeliciousHair** [comment]
As a note only, if we include the tx fees (estimates for ongoing contract, actual for closed) into the payout curve itself, this situation is handled almost fully without additional effort.

**Comment by thomaseizinger** [comment]
Done in https://github.com/itchysats/itchysats/pull/1182.
