### ISSUE TITLE
CFD has opening fee set?

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#2813]
Where is this coming from:

<img width="683" alt="image" src="https://user-images.githubusercontent.com/224613/187597895-ca1469d9-9d5c-4e97-b4b1-ec6ab0c870ee.png">

Symbol: `BtcUsd`

Tested locally.

**Comment by luckysori** [comment]
Can't find a single instance of _sending_ an offer with an opening fee set on [Grafana](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bsetup%3D%5C%22testnet%5C%22%7D%20%7C~%20%60opening_fee:%20%28%5B1-9%5D%29%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-20d%22,%22to%22:%22now%22%7D%7D) over the past 30 days.

**Comment by luckysori** [comment]
Not a bug, it's just hard-coded when going through the maker UI:

https://github.com/itchysats/itchysats/blob/23408a1e9d773909282cc9a663e34ab872d5070e/maker-frontend/src/MakerApp.tsx#L293
