### ISSUE TITLE
Remove retrying actor tests on CI and get to the bottom what fails

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2818]
Flaky tests are annoying, but just retrying them is a 🩹 that can be dangerous, because we might actually have bugs that only sometimes happen but get obfuscated by retries. 

We should create a more stable test framework and not rely on retries.

**Comment by da-kami** [comment]
Related to https://github.com/itchysats/itchysats/issues/2815

**Comment by klochowicz** [comment]
Related to #2825

**Comment by da-kami** [comment]
I duplicated this with https://github.com/itchysats/itchysats/issues/2916
😅
