### ISSUE TITLE
It can take significant time for an offer to arrive in the taker UI

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2820]
This might be relevant to congestion related issues.

Reproduction:

1. Start the system locally
2. Create offers manually in the maker UI 
3. Watch them arrive in the taker UI

Somehow it can take significant time (i.e. longer than 10 secs) for an offer that was created through the maker UI to arrive on the taker UI. During testing we did not encounter the offer not arriving at all, it always *eventually* arrived. In most of the cases it was almost instant.

Given that this only sometimes happens it could mean that there can be congestion issues somewhere on the way of the offer being processed in the maker/taker daemon.

Way forward:

1. See if this is reproducable on current master
2. If it is: Investigate further

---

Applies to `0.5.5` and current `master`.

**Comment by Restioson** [comment]
This could be a potential use case for taker-to-maker distributed traces that follow through some API flow (maybe from offer creation to delivery in taker)

**Comment by da-kami** [comment]
close in favor of https://github.com/itchysats/maker-automation-rs/issues/453
