### ISSUE TITLE
Extract otel-tests and otel-tests-macros into a separate repo

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#2822]
These crates have little to do with the project, and can be moved out of it. This will shave a bit of compilation time (rust-cache works only for external crates).

Incidentally, this is a blocker for partitioning our tests on CI: #2741 
(cargo nextest has problems with parsing tests from these crates).

**Comment by luckysori** [comment]
I'm not sure we can easily do this. These crates know about other crates in the workspace:

https://github.com/itchysats/itchysats/blob/9926f9d201dccc6a70dfeaf323dfd09842cdf7cd/otel-tests/src/lib.rs#L62-L75

**Comment by klochowicz** [comment]
> I'm not sure we can easily do this. These crates know about other crates in the workspace:
> 
> https://github.com/itchysats/itchysats/blob/9926f9d201dccc6a70dfeaf323dfd09842cdf7cd/otel-tests/src/lib.rs#L62-L75

whoops. indeed, that might be fragile to do so :(

**Comment by Restioson** [comment]
There might be some way to provide this info to the macro in a different way, but I'm not 100% sure what is best. It would depend if the goal is to just make it independent from the other crates, or configurable enough to be useful for other people.

**Comment by klochowicz** [comment]
> There might be some way to provide this info to the macro in a different way, but I'm not 100% sure what is best. It would depend if the goal is to just make it independent from the other crates, or configurable enough to be useful for other people.

I was thinking maybe a optional toml config file with `directives` list?

edit: I added #2854 as an attempt of dealing with this awkwardness.

**Comment by klochowicz** [comment]
this issue has been addressed by @Restioson.
