### ISSUE TITLE
Extract btsieve into a separate repo

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#2823]
These crate has little to do with the project, and can be moved out of it. This will shave a bit of compilation time (rust-cache works only for external crates).

Note: `btsieve` is generic enough that it can be moved into comit-network/btsieve.

We can also publish it on crates.io.

**Comment by bonomat** [comment]
> We can also publish it on crates.io.

I still don't get why we would want that.

**Comment by bonomat** [comment]
This project is unmaintained
