### ISSUE TITLE
Deal with panics in unsupervised parts of code

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#2824]
A panic can lend the system unusable until the app is restarted, with the most troubling part being the system *appearing* to work, with no indication that it's severely broken (other than a panic printed in the logs). 

As all our current platforms supervise the app itself (via docker/systemd), exiting the app would start the app anew and thus would be my preferred choice.

We could also make the user do this after showing some alert, but this would lead to worse UX.

@da-kami raised a good point that we should ensure that DB will not end up in corrupted state.

**Comment by klochowicz** [comment]
I have a changeset locally that just terminates the program, but that can lead to a corrupted state. I tried to achieve a graceful rocket shutdown, but failed to satisfy the borrow checker 😢 seems like this is not actionable at the moment.

**Comment by da-kami** [comment]
Closing because not actionable given the current framework constraints.
I feel keeping this open does not have any value if we can't action is 😅

**Comment by klochowicz** [comment]
@da-kami thank you for closing, I was meant to do the same. I'll just change it to "Not planned" instead of "Completed"
