### ISSUE TITLE
Move `NUM_LIBP2P_CONNECTIONS_GAUGE` to to the endpoint and create separate mertic for environment/version

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2843]
At the moment we always increment upon receiving an `identify` message.

We should move this gauge into the `endpoint`, it is weird that it is in the responsibility of `identify` to record this metric. But at the moment the metric depends on additional information (wire version, daemon version, environment) that is not known to the endpoint but only received in the identify message. We can create a separate metric for recording the environment/version.

**Comment by luckysori** [comment]
Why don't we just add a separate metric to the `Endpoint` already? Even if it doesn't have all the other information you mention it will be useful by itself.

**Comment by da-kami** [comment]
I think it would be a good idea to move it. I'll adapt the ticket and we can create a separate one independent of the work in #2845 

Originally I thought it would be better to bind the stats on connections and the stats on environment/version together so they don't diverge (which could be confusing). But I don't think that should be a problem, because the endpoint does not know more about connected/disconnected peers then identify does. 
From a concern in code perspective it would be cleaner to create separate metrics.

**Comment by Restioson** [comment]
Self-assigning to take a look at this

**Comment by Restioson** [comment]
> Why don't we just add a separate metric to the Endpoint already? Even if it doesn't have all the other information you mention it will be useful by itself.

Would we keep the existing `NUM_LIBP2P_CONNECTIONS_GAUGE` (maybe renamed) with all its current labels in identify, then, in order to record the connections per wire version, daemon version, and environment (should these maybe each be split into one int gauge vec per label)? Then, we could have a different metric in the endpoint just for total connections. I am still figuring out prometheus so let me know if this makes sense or doesn't.

**Comment by Restioson** [comment]
Currently blocked on #3001

**Comment by bonomat** [comment]
Temporary solution could be removing the authentication for the metrics endpoints.
