### ISSUE TITLE
Outdated version info feels a bit weird on Umbrel

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2853]
Our "outdated version" disclaimer is finally visiable, but it can feel a bit weird on Umbrel when a PR is still in the pipeline - like here for `0.6.0` on Umbrel with `0.6.1` PR still open:

![image](https://user-images.githubusercontent.com/5557790/187940892-5e9b26fc-ba3a-40fb-919e-d286dbdde6e8.png)

This will become more annoying if we create releases for the maker only. Users will always see this disclaimer then until we shoot out a new Umbrel release. This part could be overcome by #2385  but I'm not sure when it will be actioned.

For a better UX it might be worth to check update capability through the Umbrel app-store and use that as trigger for displaying the disclaimer when in an Umbrel environment.

**Comment by bonomat** [comment]
I don't think it's worth the complexity to have an extra check just for Umbrel. 

If this is too annoying then we should go for https://github.com/itchysats/itchysats/issues/2385

**Comment by bonomat** [comment]
Closing this for now as there is not much we can do to speed up the update progress. If it is an issue we should go for https://github.com/itchysats/itchysats/issues/2385
