### ISSUE TITLE
Integrate with MyNode

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#2864]
Website: https://mynodebtc.com/

**Comment by bonomat** [comment]
See how to here: https://mynodebtc.github.io/developer/add-app.html
Looks very similar to [RaspiBlitz](https://github.com/rootzoll/raspiblitz/blob/v1.8/home.admin/config.scripts/bonus.itchysats.sh)

**Comment by luckysori** [comment]
Waiting for further feedback on https://github.com/mynodebtc/mynode/pull/694.

**Comment by bonomat** [comment]
This project is unmaintained
