### ISSUE TITLE
Integrate with RunCitadel

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#2867]
https://github.com/runcitadel

This one was originally based on umbrel, so it should be a really easy one for us :)

**Comment by bonomat** [comment]
Looks like they have an apps repository: https://github.com/runcitadel/apps

**Comment by klochowicz** [comment]
ItchySats got into the `v4-dev` branch: https://github.com/runcitadel/apps/pull/44

For it to be available in the AppStore, it needs to get merged into `v4-stable`. I will close this issue when it happens (no action needed from us anymore).

**Comment by klochowicz** [comment]
We are merged into v4-stable, closing this ticket.

**Comment by bonomat** [comment]
> We are merged into v4-stable, closing this ticket.

Can you tweet about it please?
