### ISSUE TITLE
Integrate with RoninDojo

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#2868]
website: https://ronindojo.io

**Comment by bonomat** [comment]
Does not look like they have community driven apps nor could I find a how-to. I propose to reach out to them first and see if they are even interested in it.

**Comment by klochowicz** [comment]
> Does not look like they have community driven apps nor could I find a how-to. I propose to reach out to them first and see if they are even interested in it.

fair enough! I'll reach out to them and see what they say. It's hard to tell whether it's because of lightning support that most integrations are impossible or whether the aim is to keep it really basic.

**Comment by bonomat** [comment]
This project is unmaintained
