### ISSUE TITLE
Newcomer impressions on the itchysats user experience

### ISSUE THREAD

**Issue by holzeis** [itchysats/itchysats#2872]
### General Impressions on the UI

The following list just highlights the parts which were confusing to me when I first used itchysats taker 😄 (there are also good parts, which I am skipping here). I do not have any financial background - so I might not be a target user.

 - What is long / short btc? Why not be more declarative? Will the price go up or down?
 - Price is jumping in the middle - its not a very smooth animation. appears unprofessional.
 - What does Contracts mean above the number?
 - "How much do you want to buy or sell?" doesn't have any relation to the long or short btc tab.
 - Probably a help button would be valuable - to read into how itchysats resp. the CFD trading works. 
 - The UI does not explain why I have to start with 100? Contracts? of what? unit!
 - I can type a smaller quantity than 100, but its not accepted.
 - Quantity is not in increments of 100! Increment is 100? what? why? also the error message is somewhere and does not directly point me to the input that was incorrectly set.
 - It's very confusing that some amounts are in dollar and others in bitcoin.
 - What is the required margin? (whos margin? of what?)
 - What are perpetual cost why hourly, % of what?
 - The short button is red - indicating that this is dangerous, while the long button is green indicating that this valid. I guess that's not the intention.

### Opening a position

 - Contract setup ( new card nothing else, could be missed on some displays (phone)), a success message of some sort would be nice. e.g. congratulating me on opening a position and telling me what happens next.
 - CFD just jumped to open at some point - don't know why (meaning no explicit push notification).
 - Opening a long position right after the another one ends up in the setup failed. https://github.com/itchysats/itchysats/issues/2870
 - Contract setup takes a long time.. about 1-2 minutes
 - idea: a graphical presentation (e.g. chart) of how the position develops would be nice (also showing liquidation boundaries.)
 - idea: demo account to ease the entry?

**Comment by bonomat** [comment]
Thanks for the feedback. 
Most of your points go towards the complexity of CFD trading. This is fine and it's been discussed before that we can simplify our UI to move away from this terminology. 
Some inline comments: 

 
>     * Price is jumping in the middle - its not a very smooth animation. appears unprofessional.
Can you elaborate on that please: what is jumping?

>     * The short button is red - indicating that this is dangerous, while the long button is green indicating that this valid. I guess that's not the intention.
> 

Red-short and Green-long was indeed intentional. @da-kami pointed this out in the past. I was in favor of keeping it as it seems to be common on other platforms. 


>     * idea: demo account to ease the entry?

I'm keen to hear what you have in mind here. This came up in the past :)

**Comment by klochowicz** [comment]
Thank you for this invaluable feedback @holzeis !

A lot of pointed out issues are indeed the result of the inherent complexity of CFD trading; perhaps there is a room for improvement where we could at least make it clearer in the UI that this is the case; or recommend some me guides before using the product... 

as for red colour in the UI - I actually raised a discussion for that ages ago too: https://github.com/itchysats/itchysats/discussions/1597

IMHO adding push notifications would be a game changer; I have brought it in the past but we never created a ticket. I'll create one now, thanks for the push (pun intended 😆).

Going even further, I think it would be good to have "message inbox" where you could investigate events that happened when you were away - it's conceivable, especially on umbrel, that you don't have your UI open for a long time.
