### ISSUE TITLE
Configure time-to-live of rollover parameter from the outside

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#2887]
With https://github.com/itchysats/itchysats/pull/2859, rollovers cannot go ahead if rollover parameters are 5 minutes old. This only makes sense because we _know_ that the `maker` will constantly get updated offer parameters (which include the rollover parameters) every few seconds.

It's not a good idea to set a constant based on the knowledge that a different tool will call our application with a certain frequency, because all that can change (especially if someone else wants to run the `maker`). 

With that in mind, we want to let the caller of the HTTP API configure the time-to-live of these rollover parameters. We could probably already do it by adding something like a `funding_fees_ttl` field to `CfdNewOfferParamsRequest`, but that seems bad. 

Therefore, I would like to get some resolution on https://github.com/itchysats/itchysats/discussions/2886 before tackling this.

_Originally posted by @bonomat in https://github.com/itchysats/itchysats/pull/2859#discussion_r962144457_

**Comment by bonomat** [comment]
This project is unmaintained
