### ISSUE TITLE
Add push notifications support in the UI

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#2888]
Without push notifications, the user can miss significant events, such as:
- CFD got opened,
- CFD setup got rejected,
- CFD got force-closed.

IMHO push notifications on roll-over would be too annoying, leading to people ignoring the notifications altogether or turning them off. 

Any considered implementation should also take into account that we'd like to wrap the UI into electron/tauri.

**Comment by da-kami** [comment]
Would be great if we had this for #3097 or other potential error scenarios. I think it is most relevant for the user to get notified about problems that require an action.

**Comment by bonomat** [comment]
This project is unmaintained
