### ISSUE TITLE
Github action upload release asset is unmaintaned

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#289]
We use `https://github.com/actions/upload-release-asset` atm which is unmaintained.
The alternative to use is this: https://github.com/softprops/action-gh-release

**Comment by thomaseizinger** [comment]
I always liked the unix-y aspect of the official actions in that they do one job only.

But if it makes things easier I am happy to switch! The official GH actions haven't been maintained particularly well in the past ...

**Comment by thomaseizinger** [comment]
You could use the github CLI instead: https://cli.github.com/manual/gh_release_upload

**Comment by thomaseizinger** [comment]
Will be obsolete with #735.
