### ISSUE TITLE
Evaluate using Tauri instead of Electron for wrapping into desktop application

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#2890]
Tauri has recently hit [stable release](https://tauri.app/blog/2022/06/19/tauri-1-0/) making it a viable option for our desktop needs.  It has many advantages over electron (size, security, speed), and it is Rust after all. Right now they are also working on mobile support (still some time away though).

There are also plenty of open-source apps already using it - see [here](https://github.com/tauri-apps/awesome-tauri#open-source)

This is only for a time-boxed exploratory work that can help us with evaluation (and as a backup in case we run into issues with wrapping electron in #2889 ).

**Comment by bonomat** [comment]
The idea of _cheap_ desktop was to get a fast working solution without changing anything in our codebase at all. If we plan to do _proper_ desktop we can evaluate Tauri. 

The advantage of electron should be that we do not have to maintain 2 different code bases / logics for the frontend. 

I'm closing this for now.

**Comment by klochowicz** [comment]
just to clarify: this was meant as back-up in case the electron integration will turn out to be harder than we think and was not schedule in any iteration.
