### ISSUE TITLE
Frequent rollovers from previous `commit_txid`

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2893]
Recently we see `Building base DLC params for rollover from previous commit TX` in the logs quite often which could point to a problem with the rollover protocol. 

This message is displayed when the `taker` falls behind with rollover because it does not receive the last message from the maker.

This is not critical because of how the current rollover protocol is designed, which allows rolling over from a previous `commit_txid`, but the fact that this frequently happens points to connection related issues.

**Comment by luckysori** [comment]
Are you referring to mainnet? On mainnet we have [15 instances over the last 2 weeks or so](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bsetup%3D%5C%22mainnet%5C%22%7D%20%7C%3D%20%60Building%20base%20DLC%20params%20for%20rollover%20from%20previous%20commit%20TX%60%20%7C%20json%22,%22queryType%22:%22range%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221660937775615%22,%22to%22:%221662455043908%22%7D%7D), which doesn't seem worrying. Couldn't this be explained by #2602? Especially since we don't see rollovers systematically failing for the same CFD consecutively.

**Comment by bonomat** [comment]
@da-kami : please re-open if this was on mainnet or if still happening on testnet.

**Comment by da-kami** [comment]
The question is what do we consider as frequent. this was on `mainnet`, and we do still see this on `mainnet`.

In the last 7 days we had three instances where we see this:

```
2022-09-14 08:09:46 
{"timestamp":"2022-09-14T08:09:46.941254008Z","level":"INFO","fields":{"message":"Building base DLC params for rollover from previous commit TX","commit_txid":"f77fe7f52df3326a84e6e393e6c4fdaa0982de7f7aa97f0df04a5e1a97c740d9"},"target":"model::rollover","span":{"order_id":"7d346ced-b26c-4d65-9740-7a3296595e29","name":""}}
    
2022-09-14 08:09:44 
{"timestamp":"2022-09-14T08:09:44.327277935Z","level":"INFO","fields":{"message":"Building base DLC params for rollover from previous commit TX","commit_txid":"43bc61d01d66b35d45093bc3c1fd4b97a9fb574068eb289ee23577ac1084a771"},"target":"model::rollover","span":{"order_id":"005d15e2-55db-47ad-a418-3a2229fa04cf","name":""}}Show context
    
2022-09-08 02:06:14 
{"timestamp":"2022-09-08T02:06:14.429466489Z","level":"INFO","fields":{"message":"Building base DLC params for rollover from previous commit TX","commit_txid":"89f459f1d3063482529b7da20e701b42cd3f877ec7a7db9e07daac1a48db5636"},"target":"model::rollover","span":{"order_id":"28ecda7b-1fcf-411b-89f1-639c5f845bd1","name":""}}
```

Two of these instances were around the same time for different cfds of the same taker, peer-id = `12D3KooWRG3cBytxhAiHBZYeXCb8nDRWLLfDdy9Yn31MDr9WVdeR` (this peer has quite some positions going).

| Couldn't this be explained by https://github.com/itchysats/itchysats/issues/2602? 

Maybe, but for the cases above not from the maker's perspective. I took the time to run a [query](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22expr%22:%22%7Bcontainer%3D%5C%22maker%5C%22,setup%3D%5C%22mainnet%5C%22%7D%20%7C~%5C%22005d15e2-55db-47ad-a418-3a2229fa04cf%7CERROR%7C12D3KooWRG3cBytxhAiHBZYeXCb8nDRWLLfDdy9Yn31MDr9WVdeR%5C%22%20%21%3D%5C%22Future%20timed%20out%5C%22%20%21%3D%5C%22Revoked%20logic%20not%20implemented%5C%22%20%21%3D%5C%22xtra_libp2p_ping::ping%5C%22%20%21%3D%5C%22xtra_libp2p_offer%5C%22%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D) to see if I can match this to connection failures on the maker and there was no connection related issue in context of rollovers (ping and offers fail quite often nonetheless, it's too noisy to narrow these down) after the completed rollover. 
The taker must have not received the last message, but the maker fires and forgets and no error was reporting upon sending.

That said: We can blame it on https://github.com/itchysats/itchysats/issues/2602
The frequency is relatively low - if we see the frequency go up this could be worrying.
