### ISSUE TITLE
`715963df-e11f-4e90-ab69-399528916b2d`: Taker does not trigger rollover?

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2894]
`order_id`: `715963df-e11f-4e90-ab69-399528916b2d`

All times in UTC.

Last successful rollover:

```
2022-08-30 04:01:09	
{"timestamp":"2022-08-30T04:01:09.821033861Z","level":"INFO","fields":{"message":"Appended event to database","event":"RolloverCompleted","order_id":"715963df-e11f-4e90-ab69-399528916b2d"},"target":"sqlite_db","span":{"name":"Handle Event"}}
```

The manual commit:

```
2022-08-31 05:00:04	
{"timestamp":"2022-08-31T05:00:04.495321256Z","level":"INFO","fields":{"message":"Appended event to database","event":"ManualCommit","order_id":"715963df-e11f-4e90-ab69-399528916b2d"},"target":"sqlite_db","span":{"name":"Handle Event"}}
```

The taker is running on Umbrel. `identify` messages we see of the time interval in question:

The taker [did re-connect, but it appears no rollover was triggered](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22expr%22:%22%7Bcontainer%3D%5C%22maker%5C%22,setup%3D%5C%22mainnet%5C%22%7D%20%7C%3D%5C%22715963df-e11f-4e90-ab69-399528916b2d%5C%22%22,%22queryType%22:%22range%22,%22hide%22:false%7D,%7B%22refId%22:%22B%22,%22editorMode%22:%22code%22,%22expr%22:%22%7Bcontainer%3D%5C%22maker%5C%22,setup%3D%5C%22mainnet%5C%22%7D%20%7C%3D%5C%2212D3KooWGdX8oGBcVnUmhtxS7qW4tp3iH8LVHrCxwXRhr6viBo7x%5C%22%20%7C%3D%5C%22environment%5C%22%22,%22queryType%22:%22range%22,%22hide%22:false%7D,%7B%22refId%22:%22C%22,%22editorMode%22:%22code%22,%22expr%22:%22%7Bcontainer%3D%5C%22maker%5C%22,setup%3D%5C%22mainnet%5C%22%7D%20%7C%3D%5C%22not%20implemented%5C%22%22,%22queryType%22:%22range%22,%22hide%22:true%7D%5D,%22range%22:%7B%22from%22:%221661762658823%22,%22to%22:%221661966463088%22%7D%7D), which is strange.

But I think the taker only connected after some time after the restart of the maker which is also somewhat strange.

At that point in time the taker was on `0.5.4`. 
The taker later upgraded to `0.6.0` and `0.6.1`.

**Comment by luckysori** [comment]
In the logs you linked you can see that the taker was running that CFD over the legacy connection. For example:

```
2022-08-30 02:04:39 | {"timestamp":"2022-08-30T02:04:39.196124488Z","level":"WARN","fields":{"message":"Rollover failed: maker::legacy_rollover::Actor","order_id":"715963df-e11f-4e90-ab69-399528916b2d","peer_id":"Some(12D3KooWGdX8oGBcVnUmhtxS7qW4tp3iH8LVHrCxwXRhr6viBo7x)"},"target":"model::cfd","span":{"name":"Handle AcceptRollover"}}
```

We dropped support for the legacy connection with `0.6.0`, which is why this CFD couldn't be rolled over.
