### ISSUE TITLE
Set `Contracts` into better relation to the margin. 

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2897]
This is a ticket that resulted out of a usage interview with @holzeis 

When opening a position the `required margin` in BTC is quite hard to understand. It would be great to see a better breakdown of how this margin is calculated. 

This could be done by displaying the dollar value of the margin as well, so one can see that the 100 contracts at the current price are represented by the margin. This would make it easier to understand the relationship between these values for less experienced users.

Note: In the past we went away from displaying USD in the UI, because it does not make sense to think in USD in our product; we encourage our users to think in BTC. However, with the big `BTCUSD` price blinking with a `$` symbol the user is inclined to think in USD.
We could introduce a mode that allows less experienced users to see more USD values (according to the current price) when opening the position to make it easier to understand the relationships between the values and how e.g. the `required margin` is calculated.

**Comment by bonomat** [comment]
> This could be done by displaying the dollar value of the margin as well, so one can see that the 100 contracts at the current price are represented by the margin. This would make it easier to understand the relationship between these values for less experienced users.

I don't think this can work. While `1` contract on BTCUSD is `$1`, this is not the case for ETHUSD. 
Displaying the `margin` in `USD` would even be more confusing as there is no relation to the `1` ETHUSD contract.

Look at this: 

<img width="583" alt="image" src="https://user-images.githubusercontent.com/224613/188759367-d5044274-32bf-4ca4-97f7-d2eb3a58c303.png">

At the time of writing, the margin was `$15.49`. 

> [...] However, with the big BTCUSD price blinking with a $ symbol the user is inclined to think in USD.

Maybe we should remove this blinking thing if this is the reason why you think that users are inclined to think in USD?

**Comment by da-kami** [comment]
> Maybe we should remove this blinking thing if this is the reason why you think that users are inclined to think in USD?

Maybe that is the solution, but we do need to display the price somewhere, because in the end that is what defines your bet 😅

I still think it would help to tell the user how the `margin` is calculated. Maybe displaying the equivalent dollar value is not the solution, but it would be nice where this value is coming from. Other exchanges explain this in their documentation - that could also be an option. 
It would help to build trust in the product if there is more transparency here - and if people are supposed to check it in code we can link to the code ;)

**Comment by bonomat** [comment]
We can make the price smaller and instead show a candle chart :) 

And then show the formula when hovering over the price. 

Fun fact though: we still don't know the _exact_ formula bitmex uses. But we know ours, so we can tell that to the user :)

**Comment by holzeis** [comment]
> We can make the price smaller and instead show a candle chart :)

I like that, as it will also indicate that I am betting on a rate changing over time. Implicitely also giving me the history of e.g. the bitcoin USD price. One could use that information to say ok, it went down for quite some time - I am going long now.

**Comment by bonomat** [comment]
This project is unmaintained
