### ISSUE TITLE
Contract symbol selection is lost after clicking the trade or wallet button

### ISSUE THREAD

**Issue by holzeis** [itchysats/itchysats#2905]
![Image](https://user-images.githubusercontent.com/382048/188922231-83e6ce9b-c7c0-4e28-ba36-67f8199df17c.gif)

**Comment by bonomat** [comment]
Hint for whoever grabs this: we need to remember the _last_ path when switching back from wallet. Might be worth changing the logic a bit how the selector works and don't bind it to the path params.
