### ISSUE TITLE
Monitor BitMEX API RSS Feed for downtimes and update announcements

### ISSUE THREAD

**Issue by holzeis** [itchysats/itchysats#2914]
One way of implementing this could be by integrating a RSS feed plugin into a element room.. After a quick google search I found that, but haven't looked into it in more detail.

https://github.com/maubot/rss

- RSS Feed: https://blog.bitmex.com/api_announcement/feed/
- BitMEX API Changelog: https://www.bitmex.com/app/apiChangelog

**Comment by klochowicz** [comment]
> https://github.com/maubot/rs

I just tried to check it out, but I get 404 on this link 😭 have you mistyped the repo?

**Comment by holzeis** [comment]
There was a **s** missing 🙈

**Comment by klochowicz** [comment]
Thanks for the suggestion! I'll try to add it to grafana, which should be simpler than adding matrix bot infrastructure, and also would allow alerts.

**Comment by klochowicz** [comment]
@holzeis are you working on this or is it up for grabs? (if I remember correctly, you have tried to experiment with the grafana plugin?)

**Comment by holzeis** [comment]
@klochowicz it has been deprioritised in favor of the electron wrapper and since then I haven't worked on it.. go ahead and take it 😉

**Comment by klochowicz** [comment]
I made some headway before the weekend:


- the RSS plugin works, I have managed to add a dashboard with the feed: https://itchysats.grafana.net/d/l6A4UVV4k/bitmex?orgId=1
- Grafana does not support alerts from tables yet :( 
- the above means that the way to go is using a grafana managed alert, but that for some reason can't retrieve data from data source ("plugin not available" error), eventhough exploring the data source in "Explore" works just fine. I have sent an email to Grafana and will update the ticket once I know more.

**Comment by klochowicz** [comment]
turns out that grafana doesn't provide support for 3rd-party plugins, the RSS author mentioned that it can't be used for alerting; I was pointed to another plugin that might work with that, but the overhead of implementing it is quite high - after trying it out I came to the conclusion that a matrix bot might be easier to implement (where would we host it?)

**Comment by bonomat** [comment]
This project is unmaintained
