### ISSUE TITLE
Starting maker or taker deamon with testnet seeds fails with ChecksumMismatch on bdk 0.21

### ISSUE THREAD

**Issue by holzeis** [itchysats/itchysats#2917]
The bdk bump to version 0.21 broke the testnet maker and taker seed files. Deleting them and letting itchysats recreate them works just fine, though.

```
$ cargo run --bin maker -- --password dev testnet
    Finished dev [unoptimized + debuginfo] target(s) in 0.51s
     Running `target/debug/maker --password dev testnet`
2022-09-09 07:39:26  INFO shared_bin::logger: Initialized logger
2022-09-09 07:39:26  INFO maker: Running version: 0.6.1-83-gac3c438
2022-09-09 07:39:26  INFO maker: CFDs created with this release will settle after 24 hours
Error: ChecksumMismatch
```

**Comment by holzeis** [comment]
Might be that our seeds where always corrupted and just the newest bdk version added a check? What would that mean for existing users?

**Comment by klochowicz** [comment]
I have created #2918 , which of course only hides the issue, but at least it unblocks testnet, so it's less stressful to investigate.

**Comment by bonomat** [comment]
> Deleting them and letting itchysats recreate them works just fine, though.

Deleting the wallet db should fix it as the checksum is in the db. Don't delete the seed because that's were your money is ;) I wonder if this is a bug int he bdk... 

// edit// confirmed. Deleting `/taker-wallet` dir fixes it. 

// edit2// it's critical because the resulting wallet is different meaning the money is gone. So no good upgrading to 0.21

**Comment by bonomat** [comment]
Update: it already fails with 0.20. It looks like the resulting wallet is really different. 
 
I've created a simple showcase [here](https://github.com/bonomat/bdk-showcase) and reported a ticket here: https://github.com/bitcoindevkit/bdk/issues/750

**Comment by bonomat** [comment]
We've received a response. I'll give this a try. 

https://github.com/bitcoindevkit/bdk/issues/750#issuecomment-1243815463

**Comment by holzeis** [comment]
> Don't delete the seed because that's were your money is ;)

I wasn't suggesting that as a solution, but rather as an observation that the regenerating the seed file works.
