### ISSUE TITLE
Taker to accept domain for maker

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#292]
At the moment the taker has an argument `maker` which is a `SocketAddr`. For usability it would be good to support domains. Same applies if this is not a commandline argument but configurable through the UI.

**Comment by thomaseizinger** [comment]
Inline with https://github.com/comit-network/hermes/issues/229, I would like to solve this by using multi-addresses.

**Comment by thomaseizinger** [comment]
Going to close this in favor of #229.

**Comment by thomaseizinger** [comment]
Re-opening because https://github.com/itchysats/itchysats/issues/229 missed to implement this.
