### ISSUE TITLE
Run ci workflow only if file have changed

### ISSUE THREAD

**Issue by holzeis** [itchysats/itchysats#2937]
Currently the whole CI workflow is executed regardless of the change. e.g. if we only change something in the frontend the daemon tests and clippy jobs are also run. We could save a lot of execution time if we'd execute jobs only if the corresponding folder has changed - https://github.com/dorny/paths-filter

**Comment by bonomat** [comment]
Totally in favor of this!

**Comment by klochowicz** [comment]
awesome find! the same applies to release, where we only change a markdown file 🙄

**Comment by klochowicz** [comment]
I don't think that addressing that is feasible without  #2743  (we really need to be able to easily express which path is Rust source code, and manually listing dozens of crates in so many CI jobs is a real pain, especially when this can change).

I will proceed with re-doing #2743 as a part of this ticket.
