### ISSUE TITLE
Can not change leverage on the mobile phone

### ISSUE THREAD

**Issue by holzeis** [itchysats/itchysats#2961]
Using the taker ui from the mobile phone it is not possible to move the leverage slider.

**Comment by klochowicz** [comment]
the whole slider thing seems a bit unintuitive and probably should be changed; it's not discoverable at all what are the permitted leverage values. a text input with `-+` signs would be better (but then we also should give instant feedback if someone types an invalid value.

**Comment by bonomat** [comment]
This project is unmaintained
