### ISSUE TITLE
All users get notified about rc (unreleased) versions

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#2971]
Whilst running ItchySats on citadel, I've noticed that I get a notification that I should upgrade to "0.6.2-rc" for the best experience. 

This is confusing, because no-one can really upgrade to this version.

**Comment by bonomat** [comment]
Why was this release created in the first place? 
I guess we could add a check if it is a final release or RC.

**Comment by luckysori** [comment]
I will delete the weird release I created ASAP. I didn't realise it would lead to this annoying problem, sorry.

**Comment by luckysori** [comment]
The temporary release that caused this problem no longer exists in this repository. I think we can close this issue because we should just be careful when creating new releases (I wasn't careful).
