### ISSUE TITLE
Troubles with authentication when running taker on `master` 

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#2972]
I'm running into troubles with both latest Docker image and binary.

- docker master errors with:
`Error: insecure secret key config`

docker fails both with and without providing password explicitly, even with a fresh config.

- `dev-taker` (and `cargo run --bin taker`) just show that we're not authenticated on the feed, displaying annoying information that the daemon is not running; nothing seems to be working.
excerpt from the logs:
```
2022-09-19 08:29:12 DEBUG http: Handled request method=GET path=/api/version status=200 OK
2022-09-19 08:29:12 DEBUG http: Handled request method=GET path=/api/feed status=401 Unauthorized
```

were there any necessary steps that I'm missing?

**Comment by holzeis** [comment]
I am running into the same issue of `insecure secret key config`. Couldn't reproduce the issue with cargo run --bin taker though.

**Comment by holzeis** [comment]
For development you need to manually rebuild the taker-frontend with

```
cd taker-frontend
yarn install
yarn build
```

otherwise the frontend hosted by the daemon will be outdated.

**Comment by holzeis** [comment]
> A SecretKey is primarily used by [private cookies](https://rocket.rs/v0.5-rc/guide/requests/#private-cookies). See the [configuration guide](https://rocket.rs/v0.5-rc/guide/configuration/#secret-key) for further details. It can be configured from 256-bit random material or a 512-bit master key, each as either a base64-encoded string or raw bytes.

> When running in any other profile with the secrets feature enabled, providing a key of 0 or not provided a key at all results in a failure at launch-time:

According to the documentation a random secret key needs to be generated `.merge(("secret_key", ".....")`otherwise an insecure secret key config error will be thrown.. unless you run in the debug profile.


https://api.rocket.rs/master/rocket/config/struct.SecretKey.html
