### ISSUE TITLE
Wrap itchysats into android app

### ISSUE THREAD

**Issue by holzeis** [itchysats/itchysats#2983]
With [Neon](https://neon-bindings.com/) you can create native Node modules like you might in C or C++, but with none of the fear and headaches associated with unsafe systems programming. This has already been done for the taker-electron.

Using that node module we could run itchysats on any environment providing a node environment. For android that could be implemented with [Android JS](https://android-js.github.io/)

**Comment by klochowicz** [comment]
.I concur that that's the **faster** way (especially if androidjs "just works") , and that's why we're going with it here; but safety when using nodejs and electron might be a bit much 😂

**Comment by bonomat** [comment]
This project is unmaintained
