### ISSUE TITLE
Create a ItchySats homebrew cask

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#2985]
[Homebrew](https://brew.sh/) is the easiest way  to install & update apps on MacOS. It is also fairly easy to integrate with (originally by providing a custom tap).

it would be as simple as `brew install itchysats`.

Docs: https://docs.brew.sh/Cask-Cookbook

**Comment by bonomat** [comment]
Is the idea to install the Electron App (#2889) or ItchySats as a service file?

**Comment by klochowicz** [comment]
> Is the idea to install the Electron App (#2889) or ItchySats as a service file?

Electron App. 

the are 2 different entities in homebrew:
- cask - binary files
- formulae - CLI tools, background services

**Comment by klochowicz** [comment]
I have created our own homebrew tap and added the cask for itchysats: https://github.com/itchysats/homebrew/pull/1

When it becomes stable, we can submit the cask to the main cask repo, to make it just a bit easier for users, but it's not essential as it's just a one line difference:

#  with our own tap
``` 
brew tap itchysats/homebrew
brew install itchysats
```
OR
`brew install itchysats/homebrew/itchysats`

# without our own tap
`brew install itchysats`

**Comment by klochowicz** [comment]
Looking at homebrew docs, we should wait with submitting app to the official Cask repo until we reach the following requirement

>    An app from a code repository that is not notable enough (under 30 forks, 30 watchers, 75 stars).


if we submitted earlier, we risk getting rejected, and that's a good reason to keep being rejected in the future.

source: https://docs.brew.sh/Acceptable-Casks

**Comment by klochowicz** [comment]
I'm closing this as done as https://github.com/itchysats/homebrew/pull/1 got merged
