### ISSUE TITLE
Pick random port for electron app

### ISSUE THREAD

**Issue by holzeis** [itchysats/itchysats#2992]
As itchysats will run on the local machine we might get into conflict with another service running on the same port. By randomely choosing an open port this could be prevented.

**Side note** Would choosing an random open port on startup also allow for the app to run multiple times? I guess there will be at least some issues with the database.

**Comment by klochowicz** [comment]
as a temporary workaround, maybe we could choose a less-used port? `8000` is not a good one as it is often used by other HTTP services running on the machine. `7113` from umbrel could be a good temporary band-aid for the first release.

**Comment by holzeis** [comment]
I don't think the workaround will take less time than picking a random open port.. see also https://github.com/sindresorhus/get-port
