### ISSUE TITLE
Allow for basic or bearer auth for prometheus /api/metrics endpoint

### ISSUE THREAD

**Issue by Restioson** [itchysats/itchysats#3001]
Since #2903, Prometheus can no longer authenticate to scrape the /api/metrics endpoint. Prometheus does not support adding cookies to scraping endpoints, so we cannot provide a cookie for Prometheus to use. I am marking this as a 'bug' as this currently means that metrics don't work in versions deployed from master (e.g testnet setup).

Possible solutions: 
- Allow for basic auth to this endpoint again. I have taken a look locally at this but I realise it may be unwanted/controversial. I believe that the motivation for #2903 was mostly user experience, so in this case it shouldn't matter as this only touches how the automation works, but perhaps there are other considerations here. 
- Modify rocket-cookie-auth to be able to take a session token in some format through an `Authorization: Bearer` header. We would also need to have a way to generate a bearer token for Prometheus to use, and ensure that it would always be up to date.

**Comment by bonomat** [comment]
Another (maybe temporary) solution would be to just remove the authentication from the metrics endpoint. It's not that the data is that sensitive.

**Comment by klochowicz** [comment]
> Another (maybe temporary) solution would be to just remove the authentication from the metrics endpoint. It's not that the data is that sensitive.

temporary fix: https://github.com/itchysats/itchysats/pull/3002

**Comment by Restioson** [comment]
Thanks!

Is there any preference on whether basic with password or bearer with token would be preferred for a longer term solution?

**Comment by holzeis** [comment]
IMHO I would go for basic auth - as we already have an implementation and bearer tokens do not bring any additional value - since we would need to create one with a long period of validity or otherwise update the token regularly. 

We should though make sure we are sending basic auth credentials only over an ssl encrypted connection.

**Comment by Restioson** [comment]
Just to clarify, have we decided to leave /metrics unauthenticated and recommend that the /metrics endpoint is only exposed locally and not to the public internet?

**Comment by klochowicz** [comment]
> Just to clarify, have we decided to leave /metrics unauthenticated and recommend that the /metrics endpoint is only exposed locally and not to the public internet?

We did a temporary patch to make sure things still work; if there's a nice way to authenticate it it would still be good. 
Another way to deal with this would be disabling it by default (after all, no-one except us needs this).

**Comment by Restioson** [comment]
Ok, in that case I'll fix up #3017 and perhaps we can merge it?

**Comment by bonomat** [comment]
This project is unmaintained
