### ISSUE TITLE
Can't log into maker and taker from the same browser

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#3004]
We are using the same cookie name for maker and taker making it impossible to loginto both from the same browser as you overwrite the cookie when logging into the other app.

**Comment by luckysori** [comment]
I haven't experienced this locally hmm. Is it still the case?

**Comment by holzeis** [comment]
I guess it will only happen locally because the domain is the same. It shouldn't be a problem when you have it deployed to separate endpoints.

**Comment by bonomat** [comment]
> I guess it will only happen locally because the domain is the same. It shouldn't be a problem when you have it deployed to separate endpoints.

Do you think there is anything we can do?

**Comment by Restioson** [comment]
> We are using the same cookie name for maker and taker making it impossible to loginto both from the same browser as you overwrite the cookie when logging into the other app.

Can the cookie name include the role maybe?

**Comment by holzeis** [comment]
> > I guess it will only happen locally because the domain is the same. It shouldn't be a problem when you have it deployed to separate endpoints.
> 
> Do you think there is anything we can do?

There is the issue with the session state again. Because the same cookie could work for both. 😉

But anyhow. You could add an hosts entry for e.g taker.local and maker.local pointing to 127.0.0.1. that way the cookie would be stored for different domains and should work, I guess.

Alternatively we could also setup a reverse proxy, but I guess that's an overkill.

**Comment by Restioson** [comment]
That seems a little more complex than having two cookies with different names - is there a reason that this shouldn't work?

**Comment by holzeis** [comment]
> That seems a little more complex than having two cookies with different names - is there a reason that this shouldn't work?

No, different cookie names will definitely also work. But it requires code changes.

**Comment by bonomat** [comment]
This project is unmaintained
