### ISSUE TITLE
Keep taker's failed rollover data if maker could have succeeded

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#3019]
I'm [rewriting the punishment transaction issue](https://github.com/itchysats/itchysats/issues/907) and I've just had a realisation.

We should never just let the taker fail a rollover at the last step and forget about everything that has already been negotiated. We need to remember all the information, because it is the _only_ way that we can safely non-collaboratively close the CFD! Otherwise we can be held hostage by the maker:

- They can publish the new commit transaction, but they don't have to (to their own detriment, but still).
- We must not publish the old commit transaction, because they can punish us if we do so.

In order to keep the CFD alive, I think we are already doing the correct thing: allowing takers to catch up if they fall behind.
But we need to be able to model this in-between state more explicitly if we want to be able to close the CFD without the maker's permission. That means we cannot just pretend that nothing happened and not update the DLC.

Looking at the code, the `Dlc` struct must be updated as usual, except for the new entry to

https://github.com/itchysats/itchysats/blob/4961726fd5106d8c77dfa0047460be26e66634ed/model/src/cfd.rs#L1990

which should reflect the fact that there's missing information (the `revocation_sk_theirs`).

The new design should allow us to:

- Catch up by using the _second to last_ commit TXID in the list of revoked commit transactions.
- Unilaterally close the CFD by publishing the _current_ commit transaction.

The only unfortunate and unavoidable power that the maker has over a taker that is lagging behind is the ability to commit to the _second to last_ commit transaction without punishment. But this was already the case.

**Comment by bonomat** [comment]
This project is unmaintained
