### ISSUE TITLE
Add `monitor` tests for restart logic

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#3035]
On restart of the application we load all open CFDs in the `daemon::monitor::Actor`, re-hydrating the `monitor::Cfd` aggregate. This particular logic in `daemon::monitor` is untested because the `daemon-tests` do not restart the actor system from pre-existing state in the database. The lack of tests has resulted in us introducing bugs such as https://github.com/itchysats/itchysats/issues/3028.

We want to add tests to the `daemon::monitor` module. I envision some sort of mocking needed so that the `monitor::Actor` can be tested, but we might also be able to get away with only testing the aggregate re-hydration in some sort of unit test.

_Originally posted by @da-kami in https://github.com/itchysats/itchysats/issues/3029#issuecomment-1259014378_

**Comment by bonomat** [comment]
This project is unmaintained
