### ISSUE TITLE
Do not log an error if `blocked_peers.toml` is missing

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#3039]
We see this [on Grafana](https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bsetup%3D%5C%22testnet%5C%22,%20container%3D%5C%22maker%5C%22%7D%20%7C%3D%20%60Failed%20to%20send%20offers:%20Failed%20to%20negotiate%20protocol:%20Protocol%20negotiation%20failed%60%20%7C%20json%22,%22queryType%22:%22range%22,%22hide%22:true%7D,%7B%22refId%22:%22B%22,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bsetup%3D%5C%22testnet%5C%22,%20container%3D%5C%22maker%5C%22%7D%20%7C%3D%20%6012D3KooWEnMDZJY5kFbo69pXN8M5K2FgugTwDqJbDFzfFKfRFLzt%60%20%7C%20json%20%7C%20level%20%3D%20%60WARN%60%22,%22queryType%22:%22range%22,%22hide%22:true%7D,%7B%22refId%22:%22C%22,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bsetup%3D%5C%22testnet%5C%22,%20container%3D%5C%22maker%5C%22%7D%20%7C%3D%20%60blocked%20peer%60%20%7C%20json%22,%22queryType%22:%22range%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%22now-14d%22,%22to%22:%22now%22%7D%7D).

I think we should differentiate between a missing `blocked_peers.toml` file and being unable to access or use that file. The former shouldn't be an error.

**Comment by Restioson** [comment]
Would a warning be appropriate? I can take a look at this later this afternoon

**Comment by bonomat** [comment]
Warning or maybe even info. How about a simple message like 'no blocked_peers provided, not blocking anyone'

**Comment by luckysori** [comment]
Yeah, I was thinking about `INFO`. I only opened this issue to remember that I wanted to tweak that myself 😃
