### ISSUE TITLE
Rotate log file on size

### ISSUE THREAD

**Issue by holzeis** [itchysats/itchysats#3057]
We used https://github.com/tokio-rs/tracing/tree/master/tracing-appender in the XMR-BTC project with a `never` appender:

https://github.com/comit-network/xmr-btc-swap/blob/9e85637419594f69d05e0d03767d66b07001a0ae/swap/src/cli/tracing.rs#L19

We should be able to define a writer for `tracing::appender`, the [repo readme](https://github.com/tokio-rs/tracing/tree/master/tracing-appender) states:

| Using any type implementing [std::io::Write](https://doc.rust-lang.org/std/io/trait.Write.html) in a non-blocking fashion.

When looking around I found https://github.com/BourgondAries/file-rotate which I think offers what we want and seems to be still under active development. As far as I could see it implements `std::io::Write` we we should be able to use it with `tracing-appender`. Haven't given it a try though.

You could give it a "quick try" and timebox it so we don't end up with a rabbit hole.

_Originally posted by @da-kami in https://github.com/itchysats/itchysats/pull/2999#discussion_r979772452_

**Comment by bonomat** [comment]
This project is unmaintained
