### ISSUE TITLE
Replace archived upload release asset action

### ISSUE THREAD

**Issue by holzeis** [itchysats/itchysats#3074]
[`actions/upload-release-asset@v1.0.2`](https://github.com/actions/upload-release-asset) seems to be archived and not actively maintained anymore. We should consider switching to https://github.com/softprops/action-gh-release

**Comment by bonomat** [comment]
I've mentioned this about a year ago 😅 https://github.com/itchysats/itchysats/issues/289

**Comment by bonomat** [comment]
This project is unmaintained
