### ISSUE TITLE
Publish electron binaries for linux

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#3093]
Depending on the linux distro the appropriate way could be:
- AppImage (distro-agnostic)
- RPM (redhat-based distros)
- snap
- DEB (Debian/Ubuntu)
- pacman (Arch)

**Comment by klochowicz** [comment]
as a bonus we could also publish the package onto snap store, some bitcoin-related apps are there: https://snapcraft.io/search?q=bitcoin

**Comment by holzeis** [comment]
electron-builder seems to support all above mentioned linux distros - see also https://www.electron.build/configuration/linux

**Comment by klochowicz** [comment]
> electron-builder seems to support all above mentioned linux distros - see also https://www.electron.build/configuration/linux

yes, exactly. We just need to build them :)

**Comment by bonomat** [comment]
This project is unmaintained
