### ISSUE TITLE
Internally retry transaction publication upon failure

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#3097]
Currently we assume that, once we have a transaction, it will be published. If we fail to publish a transaction we only retry once the application is restarted.

Create a retry mechanism for `TryBroadcastTransaction` that distinguishes `transient` and `permanent` errors:

- `transient`: Any error related to connection problems / temporary unavailability
    - Can use https://docs.rs/backoff/latest/backoff/ for retries
    - After `x` retries a `transient` error should become a `permanent` error so the user gets notified.  
        - We can also opt for "retry forever" (i.e. no change to a permanent error) but the user should get notified.
- `permanent`: Any error related to the transactions being malformed / incorrect (this should not happen, but *in case* it happens the user should get notified)

Upon permanent errors we want to have a notification for the user. We can scope simple UI notifications into this ticket, i.e. the user should see that there is a problem with publishing the transaction in the user interface. It might be worth recording such a state in separate event(s) on  the `Cfd` because it can be relevant for the user even after a restart.

Note: We currently already ignore errors where the the other party published the transaction (or more generally speaking: the output is already spent); this should stay as is.

Out of scope:

Dealing with scenarios where the state is "wrong" because we have a transaction but cannot publish it because another transaction was already published by the other party. *Most* of these scenarios should fix itself once the other transaction gets confirmed - under the assumption that `model::Cfd` and `projection::Cfd` handle state correctly.

**Comment by bonomat** [comment]
This project is unmaintained
