### ISSUE TITLE
Fee bumping for CETs

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#3099]
If CET was not included within `x` blocks we bump the fee. 

For the CET we should be able to achieve this with CPFP, i.e. spend the output again to bump the fee. 
Figuring out the best way to achieve this is part of this ticket.

@bonomat please add information where you see fit :)

**Comment by bonomat** [comment]
Nothing to add here :)

**Comment by bonomat** [comment]
This project is unmaintained
