### ISSUE TITLE
Time to publishing `lock-tx` after accept

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#311]
It can take really a lot of time until we go from `ContractSetup` after accepting an order to `PendingOpen` - i.e. the lock tx was published. I don't really understand what is taking so long. We are talking about `30` secs+

What can cause this to take so long?

**Comment by thomaseizinger** [comment]
Signing / serializing / sending CETs I assume.

**Comment by da-kami** [comment]
seem to be expected, closing for now :)
