### ISSUE TITLE
Additional DB refactoring

### ISSUE THREAD

**Issue by DeliciousHair** [itchysats/itchysats#314]
#88  has been addressed about as much as we can for the moment via #295. However, the task is somewhat incomplete owing to features that have not yet been implemented in `sqlx`. This issue is thus a placeholder to track the external issues that will enable a more complete refactoring here. In particular:

- [ ] https://github.com/launchbadge/sqlx/issues/1489
- [ ] https://github.com/launchbadge/sqlx/pull/1455
- [x] https://github.com/launchbadge/sqlx/discussions/1502
- [ ] https://github.com/launchbadge/sqlx/issues/1494

**Comment by thomaseizinger** [comment]
I just had an epiphany in regards to https://github.com/launchbadge/sqlx/issues/1493.

Custom derives are essentially just code generation, meaning they are bound to the same module privacy rules as hand-written code. Thus, if a custom derive can generate code, it must be possible to write this code by hand.

@DeliciousHair I don't know how we failed to implement `sqlx::Type` manually but it must be possible somehow.

Perhaps the correct combination is:

- derive `sqlx::Type` without adding `sqlx(transparent)`
- implement `Encode` and `Decode manually`

**Comment by DeliciousHair** [comment]
> I don't know how we failed to implement `sqlx::Type` manually but it must be possible somehow.

Sounds plenty reasonable to me, I'll give it a shot!

**Comment by klochowicz** [comment]
closing as outdated.
