### ISSUE TITLE
Fee bumping for punish transactions

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#3160]
Very similar to bumping fees for CETs, see #3099 
We have to ensure to get punish in before the CET timelock expires.

**Comment by bonomat** [comment]
> Bumping a punish transaction can be tricky, because I think we can run into a race between the revoked-CET and the punish transaction.

That's the reason why we have a timeout on the CET: if a malicious user publishes a revoked commit, we have [12 confirmations](https://github.com/itchysats/itchysats/blob/a81ec50a9a058d760e59963b33a4e74acb09edc4/crates/model/src/cfd.rs#L67) time to the punish transaction. Which means, we have to get the transaction into a block in this timeframe or the malicious user might indeed publish an outdated CET.

**Comment by luckysori** [comment]
> That's the reason why we have a timeout on the CET: if a malicious user publishes a revoked commit, we have [12 confirmations](https://github.com/itchysats/itchysats/blob/a81ec50a9a058d760e59963b33a4e74acb09edc4/crates/model/src/cfd.rs#L67) time to the punish transaction.

So there is no "fee race" before those 12 blocks are mined, right? Only the currently valid transaction (punish) would be considered by the miners, because they cannot actually include the "revoked" CET in a block yet.

**Comment by bonomat** [comment]
> So there is no "fee race" before those 12 blocks are mined, right? Only the currently valid transaction (punish) would be considered by the miners, because they cannot actually include the "revoked" CET in a block yet.

Yes, correct.

**Comment by bonomat** [comment]
This project is unmaintained
