### ISSUE TITLE
Stop dialing if protocol negotiation fails once

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#3161]
We recently introduced a mechanism to stop dialing if we know that protocols should fail. We leverage the `identify` protocol and, if available, we use the list of supported listener protocols from our peers to determine if certain protocols should be dialed at all.

I propose to expand this (perhaps even replace it) by trusting the result of a failed negotiation due to a `multistream_select::NegotiationError::Failed` error. That error is emitted when a "protocol negotiation [has] failed because no protocol could be agreed upon".

I suggest that we should remember and record such failures when dialing, so that we stop trying to dial protocols that will inevitably fail. This improves on the current solution, because the `identify` protocol can fail. Without the information that we get from the `identify` protocol, we choose to allow all dialer protocols. Because of that we sometimes continuously dial and fail to certain peers. Here's [an example](https://itchysats.grafana.net/goto/fmTdjmIVz?orgId=1) for the deprecated offer protocol on testnet.

**Comment by bonomat** [comment]
This project is unmaintained
