### ISSUE TITLE
Ensure that rocket always starts and provide feedback in the UI

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#3166]
Result of https://github.com/itchysats/itchysats/discussions/3129

We make our startup more resilient and provide more feedback about the applications status to the user in the ItchySats UI. 

First, we will have to make sure that there are no blocking errors that can prevent rocket (which serves the UI) from starting. 
Second, the UI needs to get information about the application status.

I propose a `/status` endpoint where we can query the daemon for the status. We could also do this as part of the feed, but that is more tricky because that would be more of an alerting system (with "fire" and "resolve") like in Grafana. I think a simple status endpoint that can be queried initially and then periodically in an interval is a simpler solution. Internally we can have a `SystemStatus` actor that manages the system status state.

Given that we have some environments (notably Umbrel) where we cannot easily specify meaningful external health checks I lean towards this proposal.

**Comment by bonomat** [comment]
This project is unmaintained
