### ISSUE TITLE
Feature: Limit order & Take Profit

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#3171]
A `limit order` is a direction given to buy or sell a security at a specific price or better. 
A `take-profit order` is a type of limit order that specifies the exact price at which to close out an open position for a profit. 

In other words expressed for the novice trader who wants to automate things and just watch the price to move.
In other words expressed. We want a feature which let's the user to
- open a position (long or short) if the price is `>=` or `<=` X.
- close the said position if the price is `>=` or `<=` Y.

This is a feature which can come handy.

**Comment by bonomat** [comment]
@da-kami : do you want to add something here or did I describe this feature correctly?

**Comment by bonomat** [comment]
Somehow related to https://github.com/itchysats/itchysats/issues/2924: closing the position should take the maker's price.

**Comment by luckysori** [comment]
One thing worth remembering is that the `take-profit` order only works reliably with collaborative settlement.

**Comment by bonomat** [comment]
This project is unmaintained
