### ISSUE TITLE
Automated validation of collaborative settlement proposals

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#319]
Currently, automated validation are not validated on the on the maker side. 
We should validate if the given amounts and price proposed by the taker in the collaborative settlement proposal are sane. 

This involves taking the current price and comparing it with the proposed price. 
For simplicity the taker currently sends over the amounts as well (i.e. the proposed payout). We might want to remove that and just go by price and come up with the amounts by price + payout curve.

**Comment by thomaseizinger** [comment]
They can now be validated because we expose the proposed settlement price.
