### ISSUE TITLE
Monitor sync stops indefinitely 

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#3208]
Follow up of https://github.com/itchysats/itchysats/pull/3197 and https://github.com/itchysats/meta/issues/89

We can [observe on Grafana](https://itchysats.grafana.net/goto/3z7aOrS4z?orgId=1) that when starting the `testnet` setup with an old version of the `mainnet` db eventually the `Sync` gets stuck - no new `Sync` is triggered in the monitor anymore.

There is no `Error` or `panic` recorded in the logs. Electrum should be reachable because the wallet is still syncing.

I think the problem is likely the `sync` function being stuck, and no new `Sync` being triggered (because the current one never finishes). I am not exactly sure what causes this yet.

**Comment by klochowicz** [comment]
this matches the experience on my Linux machine - it just never finishes.

maybe it's time to write our own async client?

**Comment by da-kami** [comment]
After applying a fix for "getting stuck" when processing responses (#3209 ) we keep running the problem of exiting sync every time we trigger it because we keep running into this error when we start the sync:

```
2022-10-20 23:06:16	(no unique labels)	
{"timestamp":"2022-10-20T23:06:16.536473861Z","level":"ERROR","fields":{"error":"Failed to subscribe to header notifications"},"target":"daemon::monitor","span":{"name":"Sync monitor"}}
```

It is surprising that we only run into this problem now, because that piece of code was not changed. We always re-subscribed on every sync. I am not entirely sure where this problem is coming from and if it is related to the batch solution we implemented. 

That said: Currently we are *not monitoring* on the testnet setup. More investigation needed why we run into this new problem.

**Comment by da-kami** [comment]
Additionally it appears that the batch implementation runs into the timeout introduced in #3209 quite often, when the sync worked we saw the respective log quite often: 

```
2022-10-20 10:05:35	(no unique labels)	
{"timestamp":"2022-10-20T10:05:35.332175454Z","level":"WARN","fields":{"message":"Not all responses received because timeout reached","requests_sent":"7617","responses_received":7436,"timeout":"10s"},"target":"daemon::monitor","span":{"name":"Sync monitor"}}
```

🤔 Somehow the blockstream Electrum server is not available or we are sending too many requests? So far we never ran into limits - or we never noticed before.
