### ISSUE TITLE
wallet sync calls `batch_script_get_history` internally when configured with `Electrum` blockchain

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#3210]
When setting up BDK with the Electrum blockchain and calling `wallet_sync`, then effectively `WalletSync::wallet_setup` will be called, which internally calls `batch_script_get_histroy`:

https://github.com/bitcoindevkit/bdk/blob/master/src/blockchain/electrum.rs#L142

Note: I noticed this in the logs, because we still see `batch_script_get_history` related errors when the wallet is syncing.

This might be another (small?) part of our memory growth. I find the implementation quite complex and could not fully understand with what scripts `batch_script_get_history` will be called, so it's hard for me to estimate how much memory we are talking about.

---

We cannot easily overcome this problem without reporting the memory growth problem in `rust_electrum_client` upstream.

**Comment by bonomat** [comment]
This project is unmaintained
