### ISSUE TITLE
Stop trying to fetch `olivia` attestations that have been erased

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#3273]
At some point, `olivia` stops serving announcements and attestations that are old. This is okay, because considerably old announcements and attestations shouldn't be useful to anyone.

But we have at least two CFDs in ItchySats which care about old attestations. This can be seen in [our Grafana logs](https://itchysats.grafana.net/goto/HC64JgFVk?orgId=1).

We should identify these CFDs and consider modifying them or removing them if they're somehow actually closed. The motivation is to not produce 2 absolutely useless log events every 30 seconds.

**Comment by bonomat** [comment]
This project is unmaintained
