### ISSUE TITLE
Withdraw funds

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#335]
One core feature which is missing is to allow taker and maker to withdraw all funds from the wallet.

**Comment by bonomat** [comment]
In case adding it to the UI adds too much complexity, I'd vote for a simple cli command. 

Eitherway, this feature is about withdrawing what's in the wallet. If there are pending CFDs and get settled afterwards, he'd need to withdraw again. Meaning, the user has to first settle all CFDs and then withdraw the funds.

**Comment by thomaseizinger** [comment]
I vote for CLI command.

**Comment by da-kami** [comment]
#462
