### ISSUE TITLE
Taker does not reconnect when maker daemon is restarted

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#346]
Not sure if this should be treated as bug?

Problem is: The taker does not see in any way that a maker restarts. There is also no error.
Once a maker restarts, the taker currently also has to be restarted, but once we do this over wire the taker will never know unless being told.

**Comment by thomaseizinger** [comment]
We would have to add some kind of `ping` messages to detect dead connections and restart once we witness a problem.

**Comment by bonomat** [comment]
This is especially useful in the preview setup where we hot-reload the maker whenever there is a new version available.

**Comment by klochowicz** [comment]
so far we have added the shutdown of the taker when maker goes offline #488 , reconnection is related to #623 (we need to be at least in known state to the user to attempt reconnections)

**Comment by klochowicz** [comment]
Closed by #681
