### ISSUE TITLE
Do not track timestamps with nanosecond precision

### ISSUE THREAD

**Issue by DeliciousHair** [itchysats/itchysats#352]
Trivial change to DB structure to remove ns from timestamp + delay data but requires checking that this does not cause conflicts with `SystemTime::now()` instances elsewhere in the codebase.

**Comment by thomaseizinger** [comment]
The solution for this is likely to have our own `Timestamp` type that has only a precision of seconds.

**Comment by DeliciousHair** [comment]
resolved
