### ISSUE TITLE
Improve roll-over knowledge in the UI

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#368]
At the moment we just transition to `Open` again (so the database already knows based on the appending state), but we don't display anything in the UI, and don't have means to easily know that we rolled over based on the state, because we don't reason about multiple states so far.

**Comment by bonomat** [comment]
I'd like this feature to be implicit, i.e. the user does not actively have to `roll over` but it happens automatically everytime she comes online. 

I imagine it like this: 

- user sees a set of open CFD positions each with their deadline. 
- if the user does not come online until the deadline, we assume, the counterparty will settle. 
- if the user comes online any time before the deadline, all of his CFD positions will be automatically extended for another term (e.g. 24h)
- if the user wants to exit a position, he has to actively ask to _settle_ (or in the future, open a counter position)

**Comment by thomaseizinger** [comment]
> if the user comes online any time before the deadline, all of his CFD positions will be automatically extended for another term (e.g. 24h)

This will need some more refinement. Taken literally, we would have rollover every second or however quick we can do it.

The notion of online/offline is a bad indicator to automatically trigger this I think.

We can only do things while we are online anyway, meaning what we really need to focus on is time:

How soon _after_ we started the contract would you expect a rollover?

In other words, for how long can a contract sit there and _not_ be rolled over?

**Comment by bonomat** [comment]
My reasoning is that the contract duration/expiry is an implementation necessity: given the lack of dynamic liquidation it is too risky to have contracts which are open for a long time or forever.

> This will need some more refinement. Taken literally, we would have rollover every second or however quick we can do it.

Fair point, we should be able to come up with a simple heuristic here: since we plan to have hourly attestation points, we don't need to rollover ever second but roll over for the next full hour in 24h.

> How soon after we started the contract would you expect a rollover?
> In other words, for how long can a contract sit there and not be rolled over?

If we have 1h windows, then ~1h?

**Comment by bonomat** [comment]
closing this in favor of #456
