### ISSUE TITLE
Replace `Buy` and `Sell` enum with something more appropriate

### ISSUE THREAD

**Issue by DeliciousHair** [itchysats/itchysats#373]
Extends #357 and ties to #365.

This enum doesn't actually belong in the logic flow, so it's current use is somewhat ad-hoc and a bit confusing.

**Comment by da-kami** [comment]
Would it be appropriate to use `long` and `short` instead of `buy` and `sell` here or would this also be confusing?

**Comment by DeliciousHair** [comment]
That was my thinking, yes.

**Comment by DeliciousHair** [comment]
resolved via #433
