### ISSUE TITLE
Provide UI feedback for failed actions

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#378]
This ticket describes what I already started in https://github.com/comit-network/hermes/pull/296.

In order to give proper UI feedback for actions, we need to:

1. synchronously send the message to the actor within the HTTP handler
1. check the return value for any errors

We cannot (2) with the current approach of always logging the error. I suggest to continue the effort in https://github.com/comit-network/hermes/pull/296 and simply get rid of the `log_error` macro entirely and instead using `spawn_fallible` to handle the combination of sending a message asynchronously but also logging the error.

**Comment by klochowicz** [comment]
Solved by #467  and #474.

**Comment by klochowicz** [comment]
> Solved by #467 and #474.

to be precise: these PRs removed usage of `log_error` from the HTTP handlers, not from other parts (that work can be done as part of a different PR).
