### ISSUE TITLE
Taker should be able to withdraw previously made settlement proposal

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#396]
Taker can't do anything with a settlement proposal when the maker does not react.

It could either:
- propose a new settlement (price could have changed?)
- commit

Moreover, clicking the action could happen as a result of user error, and the user should be able to undo it (especially that in this case nothing goes on-chain yet)

**Comment by thomaseizinger** [comment]
Outdated as the user only has one option in the new UI.
