### ISSUE TITLE
P/L calculation should take tx fees into account

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#403]
At the moment our P/L calculation is based on what the user provided at margin. The actual profit is however less tx fees which can be quite confusing. 

For example: 
In this contract I made 1.09% profit
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/224613/138183051-6dd6a5fe-5dd1-4cdc-8ba8-76bac8c6ef8f.png">

but on-chain I will only receive: `0.00007577`. Meaning, I actually made a loss :)

see https://mempool.space/testnet/tx/7bc402317c241869b17e90d9d34e5a99a33c9b36f0138b2c321d4a96731a2228

**Comment by da-kami** [comment]
I think this should be done as part of #278 
We can do it separately though before / after #278 but should be careful to update #278 in case the model changes.

**Comment by bonomat** [comment]
The P/L is already based on the actual payout which includes tx fees.
