### ISSUE TITLE
Margin should take funding tx fee into account

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#404]
Similar to #403 the margin shown in the UI is not correct. 
We should update the margin and substract the tx fee we paid for in the lock tx . 
Alternatively, we say the user has to provide `margin` to the output address, meaning, he has to spend `margin+fees`.

Note, this has also implications on all our calculations such as P/L, liquidation price and payout curve

**Comment by DeliciousHair** [comment]
Just an extra thought on this, if we can clearly document the pedagogy for all of this somewhere, the changes requires (and subsequent edits to any logic) will be very, very easy. As is, the payout curve and profits are computed completely independent of any fees, which is of course incorrect.

**Comment by bonomat** [comment]
This ticket is wrong: the margin shown in the UI (and used in the CFD) is the amount in tx_lock.
