### ISSUE TITLE
Mock wallet beyond contract setup

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#449]
Currently, we have a mocked wallet actor in the actor tests, but so far we cannot go beyond the contract setup, because the transaction verification steps of the production code fail. 

Objective of this ticket is to have a passing test that asserts on `PendingOpen`, i.e. get the test system to go past the contract setup.

**Comment by klochowicz** [comment]
@da-kami is it not implemented already?

**Comment by da-kami** [comment]
#453
