### ISSUE TITLE
Explore possibility to use a mock framework

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#450]
With starting to use the mock actors in the actor tests we started implementing our own mock framework. Of course that is possible, but we should give existing mock frameworks a try. 

Objective of this ticket is to have a look at https://docs.rs/mockall/0.10.2/mockall/ and see if we can easily use it. 
This is on top of existing tests that we have already written. If we are able to use the mock framework for more complex tests, we might as well just use it overall and don't re-invent the wheel.

**Comment by klochowicz** [comment]
I've opened #458 which refactors the existing tests - IMHO the subsequent tests will be easier to write with these changes.
