### ISSUE TITLE
Taker only receives one offer

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#455]
On latest master the taker does not receive new offers.

1. Maker create offer
2. Taker post order
3. Maker accept order
4. Maker create new offer
5. Fail: Taker does not see new offer

**Comment by klochowicz** [comment]
I believe I've managed to reproduce it in a test. Will work tomorrow morning on a fix & will submit both in a PR.

**Comment by klochowicz** [comment]
I can't reproduce the issue on the latest master (running locally, with clean DB). I was able to see the second offer straight away.

**Comment by bonomat** [comment]
Weird... let me check again.

**Comment by bonomat** [comment]
can confirm, might have been a glitch.
