### ISSUE TITLE
Automate roll-over

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#456]
Right now the user has to trigger roll-over of a contract. This should be automated, e.g. on an regular interval the contracts should be rolled-over for another term (e.g. 24h). 

This will simplify our UI because it removes the user to manually have to roll-over. 

This only applies for the Taker, the Maker should still have to manually accept/decline the roll-over request.

**Comment by da-kami** [comment]
I assume that the implementation should be similar to what is described in https://github.com/comit-network/hermes/issues/368#issuecomment-947155785, i.e. we roll-over every hour
