### ISSUE TITLE
Settle or commit

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#457]
Right now the Taker has to decide between settling and committing. It is not clear how and why he should chose one over the other. 

Instead, we should always try to settle first and then, if it fails because the maker does not respond, commit on-chain.

**Comment by scratchscratchscratchy** [comment]
@bonomat I think this is outdated, please re-open if still needed

**Comment by bonomat** [comment]
It's still valid: we always go for `collaborative close` but never for `commit`+`cet`. 

This should happen in the backend automatically.

**Comment by thomaseizinger** [comment]
Done in the frontend now based on having a maker connection or not.
