### ISSUE TITLE
Faulty states and transitions

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#473]
When modelling the behavior of cfd state machine, as of the codebase when #469 merged, we noticed several problems with that state machine. These problems are mostly unguarded state transitions that can cause weird side effects. 
Some of these problems *are expected to* go away when we tackle refactoring the state machine as described in epic #357 (and related tickets, see #357).

However, it is hard to keep track of these problems over the course of the refactoring, so this is an effort to write down problems related to the state machine before the refactoring. Once the refactoring is done we can come back to this epic and tick things off, or decide to tackle problems that still exist on top. 

Here is a rendered version of the state machine as merged in #469:

![MVP sequence diagram](http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/comit-network/hermes/57dbc2ca1c147b7abca82fe26a2be3c0bcc0e66e/docs/asset/mvp_cfd_state_machine.puml)

Problem list (critical things first):

- [ ] `handle_cfd_roll_over_completed` does not have any guard when transitioning a state back into `Open`. Even final states would transition the cfd back into `Open` if a maker accepts a roll-over request at a later point. Roll-over should be properly guarded. **What is on the blockchain should always have priority in decision making, i.e. if we witness a transaction in chain that makes the cfd final we cannot transition to anything else anymore.**
- [ ] `ContractSetup` should not be blindly cleaned up to `SetupFailed` upon startup. See: #364 
- [ ] `Accepted` state is unused and should be removed. Transitioning into `ContractSetup` directly is correct.
- [ ]  `Rejected` is not treated as proper final state in `handle`; it is only implied that once we are in `Rejected` we cannot transition into any other state. We expect that this problem will be solved by not handling `accept` and `reject` as part of the cfd state machine. The cfd should not know about being `Rejected` at all, this is the concern of the order/offer.

**Comment by thomaseizinger** [comment]
I believe this is outdated.
