### ISSUE TITLE
`-generate-seed` is a bit cumbersome

### ISSUE THREAD

**Issue by 1010Tom** [itchysats/itchysats#505]
Having to add the argument `--generate-seed` is a bit cumbersome, especially that you have to add it once and then not again. 

Ideally it would not be required and the seed would be automatically generated. Or, `generate-seed` is ignored if a seed was already generated before.

**Comment by da-kami** [comment]
yes, I'd propose to just auto-generate on first startup. On the xmr-btc project we do that and did not get complaints (e.g. about money not been there after changing data dir).
