### ISSUE TITLE
Improve error message when providing decryption fails due to wrong maker-id

### ISSUE THREAD

**Issue by 1010Tom** [itchysats/itchysats#509]
At the moment when providing an invalid maker-id (pubkey) we get an not very informative error message: 

```
Error: early eof
```

This error occurs because decryption fails because the makers pubkey was specified incorrectly. The noise library only knows that the encryption fails. We should add a meaningful error message using `context()` where in the codec where the decryption happens.

**Comment by luckysori** [comment]
This seems related to the legacy network stack.
