### ISSUE TITLE
Cannot deposit funds because I don't know the address

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#516]
Wanted to play with the latest demo today and got stuck on the first screen with 0 balance. Couldn't find the address to deposit money anywhere.

Version: 0.1.1

**Comment by bonomat** [comment]
This was fixed and is merged but it looks like the released docker image is faulty  (does not include the fix)
 
Commit that fixes this: https://github.com/itchysats/itchysats/commit/f39f206ce8173e3937a22e75b6c2666cb14d0ab1

Proposal, release a new version 0.1.2 and trash 0.1.1
