### ISSUE TITLE
Telegram & Twitter in the UI so people can contact us

### ISSUE THREAD

**Issue by scratchscratchscratchy** [itchysats/itchysats#518]
Telegram join link: https://t.me/joinchat/ULycH50PLV1jOTI0
Twitter: https://twitter.com/itchysats

**Comment by klochowicz** [comment]
I'd go one step further, and would allow link to the github, so any issues could be reported there too!

**Comment by thomaseizinger** [comment]
I propose a footer with contact and further links!
