### ISSUE TITLE
One-click demo

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#520]
We want the following user experience:

1. Download
2. Start
3. See UI

This is currently blocked by our command line parameters.

**Comment by klochowicz** [comment]
As the maker IP address, maker-id, and the fact that we're operating on testnet will not change in the near future, perhaps we could hardcode this information if the user does not provide it explicitly? either as clap defaults or an env file that gets shipped with the early versions?

Note: the generate seed parameter is gone:  #527

**Comment by thomaseizinger** [comment]
An easy first solution could definitely be clap defaults! Later we can remove the command-line parameters entirely and replace them with a settings screen.

**Comment by thomaseizinger** [comment]
I think this is outdated for now.
