### ISSUE TITLE
Being able to trigger `Buy` should be more restricted

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#522]
Currently the user can click `Buy` unconditionally as soon as an order is present.

We should at least validate:

- The balance is enough to fulfill the margin

I propose to just add this condition to the `order != null` condition for now. Additionally a tooltip that shows what is the problem. More creative: Display link to wallet under button if the balance is not enough (...).

Going down the route of adding proper validation by using a form and e.g. `formik` is a bit of a rabbit hole, so I would postpone that to later.

**Comment by klochowicz** [comment]
additionally, I'd say that the amount should be within the possible range, otherwise it should not be possible to click "buy".
