### ISSUE TITLE
No indication and validation in the taker about valid order range

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#525]
the new UI lost the ability to communicate about the available offers from the maker.

I tried ordering $103 from the maker, and it failed during contract setup with a really confusing error:
`Failed to setup contract with maker: CET signatures don't verify: no enc sig from other party for price range 55360..=55363`

**Comment by bonomat** [comment]
I'm not sure the error fits to what you are describing: 
If you got that far, the maker has accepted the order  already (i.e. it was a valid request) but you failed during contract setup. 

This error should not happen though and would rather indicate a bug.

**Comment by klochowicz** [comment]
I've spawned this particular error as a separate bug (#603 ). The UI/UX issue raised here still stands (I had no idea whether maker was being able to accept, or whether I had enough money in my wallet to get transaction - both of these conditions are not checked/communicated to the user in case it fails.
