### ISSUE TITLE
Add additional price feed to daemon

### ISSUE THREAD

**Issue by 1010Tom** [itchysats/itchysats#533]
PR #529 adds a hotfix for showing the index price of BTC/USD and not the ask/bid in the UI.

This was done so that we have constantly price information in the UI which reflects the actual price (i.e. what the oracle will attest to eventually). The ask/bid price is taken from the order and might be undefined if no order was created. 

We should extend however the daemon with this logic. The current daemon price feed does not be representing all prices we need - it only shows `bid`/`ask` but we want the index price. 
The way we internally use the price is also not correct in all cases. 
For example, profit/loss is currently calculated using bid/ask price but the oracle will sign the index price. 
We should clean this up, but this might take more effort. 

It just happens that we want to use `BXBT` from Bitmex but this price has actually not much todo with the current bids/asks. 
Imho we should introduce a new price feed for the BTC/USD price and _duplicate_ the logic we have around retrieving the price from Bitmex. 

_Originally posted by @da-kami in https://github.com/itchysats/itchysats/pull/529#discussion_r747230065_

**Comment by thomaseizinger** [comment]
Needs more discussion, continue here: https://github.com/itchysats/itchysats/discussions/1108
