### ISSUE TITLE
Balance is not centered

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#536]
The majority of the UI uses a centered layout, but the balance is not centered.

![image](https://user-images.githubusercontent.com/5486389/141377453-b4d34afb-b116-4b29-92c6-1650734923bf.png)

**Comment by thomaseizinger** [comment]
@da-kami @bonomat How do you feel about issues like this?

**Comment by bonomat** [comment]
I personally have a hard time noticing these things and look more on functionality. For example, in your screenshot there is no order available and input quantity is 0 --> maybe best is to disable the buttons and show a note that there is not enough liquidity available. 

Anyway, back to topic of this issue: _centered_ might not be the best choice because then the navbar looks unbalanced?

**Comment by thomaseizinger** [comment]
> For example, in your screenshot there is no order available and input quantity is 0 --> maybe best is to disable the buttons and show a note that there is not enough liquidity available.

I recorded a separate bug for what happened there: https://github.com/itchysats/itchysats/issues/538

> Anyway, back to topic of this issue: centered might not be the best choice because then the navbar looks unbalanced?

What do you mean unbalanced?
I am talking about red vs yellow:

![image](https://user-images.githubusercontent.com/5486389/141379226-1b81b600-8092-4680-b990-5811fd77e0dc.png)

**Comment by bonomat** [comment]
I meant that `on-chain balance` seems to be centered between the menu button on the left and the moon on the right. 
If you move it to the center of the page, then the space between the menu on the left is bigger than the space between the moon on the right.... but then again, I'm not sure if this is better or worse :) 

![image](https://user-images.githubusercontent.com/224613/141384316-f287dfa9-d0f8-4bef-ade2-2b1e6dd5369c.png)

**Comment by thomaseizinger** [comment]
> I meant that `on-chain balance` seems to be centered between the menu button on the left and the moon on the right.
> If you move it to the center of the page, then the space between the menu on the left is bigger than the space between the moon on the right.... but then again, I'm not sure if this is better or worse :)

I see what you are saying. Sounds to me like the balance should not be part of the nav bar but just part of the main UI.

**Comment by thomaseizinger** [comment]
During testing this morning, I thought it would actually be nice if the balance would be right next to the "Required margin"?

**Comment by bonomat** [comment]
> During testing this morning, I thought it would actually be nice if the balance would be right next to the "Required margin"?

I've fixed it with moving it out of the nav bar atm.
