### ISSUE TITLE
Cannot open 2nd position without restart

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#538]
To reproduce:

1. Start latest preview
2. Open position
3. Liquidation price drops to 0 and I cannot edit a quantity

I think this is because we don't have an offer from the maker.

Effectively, I only had 1 go at opening a position, then I had to restart the app to try again.

**Comment by da-kami** [comment]
This should hopefully be fixed with https://github.com/itchysats/itchysats/pull/530 - I'll see to get that merged.
I'll keep it open until I can confirm that the problem is fixed.

**Comment by bonomat** [comment]
related to #550

**Comment by da-kami** [comment]
Fixed by https://github.com/itchysats/itchysats/pull/559 which fixes #550
