### ISSUE TITLE
Go long button is always enabled in the taker

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#542]
New taker UI never disable disables the "buy" button

**Comment by da-kami** [comment]
duplicate of #522

**Comment by bonomat** [comment]
> duplicate of #522

what he said

**Comment by klochowicz** [comment]
> duplicate of #522

IMHO they were not duplicates, these 2 issues had a distinct feature scope - this one was simply porting from the old UI, the other one adds new functionality.

Anyway, I forgot to reference the issue in my Friday's PR: #545. It should have been closed :)
