### ISSUE TITLE
Change log level of `alive` endpoint

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#543]
The `/alive` endpoint is spamming the logs big times. It would be good to remove or reduce the log level for this endpoint only.

**Comment by klochowicz** [comment]
I had a look at it, unfortunately Rocket does not allow tailoring its logs yet :( (it won't make it for v0.5 at all).

I'll remove it from the maker and reinstate it for the taker (it has no use for the automated maker anyway, it's only use-case is the UI noticing that the backend is dead).

**Comment by klochowicz** [comment]
more comprehensive fix will be done by addressing: https://github.com/itchysats/itchysats/issues/482
(it will remove the need for utilising that endpoint altogether)

**Comment by thomaseizinger** [comment]
Closing in favor of https://github.com/itchysats/itchysats/issues/482.
