### ISSUE TITLE
"At the current rate you would receive" does not match "Unrealized P/L"

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#557]
This might be a user error on my side but I don't understand why these two metrics disagree:

![image](https://user-images.githubusercontent.com/5486389/141701526-3b74eb39-da07-4e08-9e1b-3d59bb6ccb0b.png)

P/L indicates that I am making a loss but right next to it, it says that I will be making a profit.
I also don't understand what "At the current rate" actually means. Does this refer to the exchange rate? Interest rate?

**Comment by da-kami** [comment]
As discussed today in the morning:

`Unrealized P/L` represents profit or loss, i.e. a plus or minus on your margin.
`At the current rate you would receive` represents the complete payout. 

It would help to relate these, i.e. display 

```
    Margin
+/- Unrealized P/L
-------------------
    Payout
```

How exactly we want to display it should be decided when tackling the issue - the most important thing is to make the relationship between the three values clear.
