### ISSUE TITLE
Actor test for maker-taker connection edge case(s)

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#560]
In https://github.com/itchysats/itchysats/pull/559 we fixed a problem where failing to send on an "outdated" connection that was not cleaned up would would lead to `handle_broadcast_order` failing. More specifically we would early-exit the loop over all takers resulting in some never receiving the order. This problem would only happen in some cases, which were likely related to how we looped over the elements in the hashmap and their order.

As @klochowicz pointed out we should think about how a test could cover that this behaviour is fixed.
Prior to the fix the issue could be reproduced like this:

1. start maker
2. start taker
3. check that orders arrive on taker
4. keep maker running, restart taker
5. check that no orders arrive on taker after the initial one.

Note, that it remains unclear if we always could reproduce it, since it depends on the connection hashmaps's order and the way we loop over it.

In order to write an actor test covering this issue we will need the possibility to simulate "restarting" an actor.
This requires to be able to not only start, but also shutdown an actor. Once shutdown, starting the actor again is trivial.

Additionally, testing this issue to the full extent *might* require adding more determinism. If we would be able to make the taker's identity fixed in maker_inc_connections then we can test with fixed identities. However, introducing dedicated network identities is out of scope for this issue.

**Comment by thomaseizinger** [comment]
Pretty outdated, closing for now.

**Comment by klochowicz** [comment]
We have certainly introduced the capability for this and tested a few edge-cases around it when adding the heartbeats. If any bug gets discovered, we can always test the fix with a new test.
