### ISSUE TITLE
Encorporate UI projections into actor system

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#572]
Currently, the projections necessary for the UI are happening outside of the actor system in the "rocket layer" via multiple `tokio::sync::watch` channels and the `ToSseEvent` trait. This has multiple downsides:

1. It is not tested as part of our integration test because our tests start at a different layer. We don't want to change the layer we are testing at.
2. It introduces complexity in the actors because they need to send updates on various "watch" channels.

To fix these problems, we want to introduce a dedicated _projection_ actor which takes care about applying the projection for the UI. The goal is manifold:

1. Reduce the logic happening in the rocket layer. `ToSseEvent` can likely go away as part of this.
2. Reduce the complexity for other actors in what needs to be updated when. All they should care about is sending updates to the projection actor.
3. Improve test coverage. With a dedicated actor that does the projection, we should be able to write assertions in our integration tests that are closer to the UI.

**Comment by bonomat** [comment]
Reopening: #645 set the ground work but did not solve this ticket yet.

**Comment by klochowicz** [comment]
This has been addressed in the PRs:

#697  #709 #708  #719
