### ISSUE TITLE
Authorize taker

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#576]
At the moment, we don't authorize actions from the taker. In other words, anyone knowing an order ID can perform any action on a CFD.

We need to associate the public key of the taker with the CFDs and check them upon every incoming command.

**Comment by klochowicz** [comment]
We've done with implementing `verify_peer_id()`

https://github.com/itchysats/itchysats/blob/master/model/src/cfd.rs#L1446

**Comment by da-kami** [comment]
Closing, follow up to be actioned: https://github.com/itchysats/itchysats/issues/2891
