### ISSUE TITLE
Version check during first connection between maker and taker

### ISSUE THREAD

**Issue by 1010Tom** [itchysats/itchysats#577]
We should have a version compatibility check between maker and taker. 

For example, the taker could say to the maker `running version X.Y.Z` and the maker returns his version. If they not match, either party should cut the connection.

**Comment by thomaseizinger** [comment]
1. Introduce a `Hello` message that is sent by the taker once they are connected.
2. Introduce the concept of a "network version" that is sent across in `Hello`
3. If the "network version" doesn't match, disconnect the taker.

Given this, we will need to bump the "network version" constant every time we make breaking changes to the messages.
