### ISSUE TITLE
Error during contract setup

### ISSUE THREAD

**Issue by klochowicz** [itchysats/itchysats#603]
When I tried to get an order of $103 dollars recently, I got this error:

`Failed to setup contract with maker: CET signatures don't verify: no enc sig from other party for price range 55360..=55363`

**Comment by da-kami** [comment]
I saw the same one a long time ago. @thomaseizinger do you think it's possible/worth to write a proptest so we can reproduce this more deterministically?

**Comment by da-kami** [comment]
@klochowicz do you remember the flow of what happened? 
e.g. did you try to open a position again or was this the first one after a longer period of time that was opened?

I am asking because it could also be related to messaging / communication. I don't think it is, but we cannot rule it out yet.

**Comment by da-kami** [comment]
I don't think this is super critical, because if this fails it should fail on both sides, nevertheless we should look into it.

**Comment by thomaseizinger** [comment]
> I saw the same one a long time ago. @thomaseizinger do you think it's possible/worth to write a proptest so we can reproduce this more deterministically?

What _property_ would you want to test here? I can't think of anything.

**Comment by klochowicz** [comment]
> @klochowicz do you remember the flow of what happened? e.g. did you try to open a position again or was this the first one after a longer period of time that was opened?
> 
> I am asking because it could also be related to messaging / communication. I don't think it is, but we cannot rule it out yet.

I don't remember unfortunately ;(

**Comment by thomaseizinger** [comment]
I think outdated. Hasn't happened in a long time.
