### ISSUE TITLE
Store taker details to each CFD

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#604]
With #601 we store the taker's pk and not a random uuid. It would be good to associate the taker's id with their CFD. 

_Originally posted by @bonomat in https://github.com/itchysats/itchysats/pull/601#pullrequestreview-808016555_

**Comment by thomaseizinger** [comment]
There is already a ticket for the actual authorization (https://github.com/itchysats/itchysats/issues/576) which basically assumes that we need to store the taker's pubkey with the CFD. 

Is it worth splitting this task even further up with this ticket just concerning itself with storing the pubkey?

**Comment by bonomat** [comment]
Probably not. Let's close this in favor of #576
