### ISSUE TITLE
Taker UI authentication 

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#609]
Implement basic auth for taker.

**Comment by thomaseizinger** [comment]
I think you might misunderstand the idea of OAuth. OAuth is about granting permissions to other systems (like "Sign in with GitHub"). I don't think there is a need for supporting dedicated identity providers?

**Comment by bonomat** [comment]
Note: we cannot use the same approach as for the maker where we print the password on the console. That's because we expect the user to run this application on an umbrel node and he won't be able to read the logs.

**Comment by thomaseizinger** [comment]
> Note: we cannot use the same approach as for the maker where we print the password on the console. That's because we expect the user to run this application on an umbrel node and he won't be able to read the logs.

Good point. Probably needs an initial setup screen where the user can choose a password and then we save it to the DB.

**Comment by lukechilds** [comment]
>Note: we cannot use the same approach as for the maker where we print the password on the console. That's because we expect the user to run this application on an umbrel node and he won't be able to read the logs.

We have some functionality built into Umbrel for this where each app gets a unique `$APP_PASSWORD` environment variable passed to it which contains a cryptographically secure random password in plain text. The user is displayed the same password in the Umbrel UI so they can copy/paste it over.

You could support it by passing the env var to your taker binary via a flag like `--password=$APP_PASSWORD` in `docker-compose.yml`.
