### ISSUE TITLE
Allow taker to put complete balance into position

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#640]
As a user I don't want to have funds sitting around in the internal wallet of the tool. 
I would transfer funds and then expect to put all of them into a position. Don't really see the point of keeping funds in the internal wallet for longer.

So, I think we should add a `max` / `all-in` feature, so that users can open positions with the complete balance. 
This will also make tracing profit and loss over multiple positions easier, because I can record my initial balance and then see how it progresses without keeping the "current balance" into account (because it should be always 0).

**Comment by klochowicz** [comment]
I'm not sure if this is possible - we can increment by `size_per_parcel` (lot size), so even if we added the button, it would still likely to leave some change in the wallet :)

**Comment by bonomat** [comment]
I'd say we reopen if this comes as a request from our users. 
For now, it I'm closing this is as this is quite old and it is not straight forward to be implemented.
