### ISSUE TITLE
Too many "opening" states

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#658]
I don't think there is any value in showing the states "Order requested", "Contract setup" and "Pending Open" to the user. I think we can simplify all of them to "Opening" / "Pending Open".

@bonomat @da-kami ?

**Comment by klochowicz** [comment]
IMHO  think it's a good idea to show the progress of the CFD setup to the user - it keeps them reassured that things are ticking along, working as expected. Perhaps there's a different way to do that to the user than changing the state though

**Comment by thomaseizinger** [comment]
This has been simplified.
