### ISSUE TITLE
False `Connection Error` in UI

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#659]
I'm clearly connected to a maker, the taker is running and everything is on the same machine. Nevertheless, I keep getting these errors from time to time. 

![image](https://user-images.githubusercontent.com/224613/142797073-d04d8596-ce3b-41ac-a3df-ad366718e6ee.png)

Something must be wrong with this check.

**Comment by bonomat** [comment]
ping @klochowicz

**Comment by bonomat** [comment]
maybe it has something todo with running in dev mode.

**Comment by klochowicz** [comment]
can you see anything in the logs? (in either taker or maker daemon?). 
it might be the dev mode indeed, as you likely have 2 instances of the frontend running (on port 3000 and 8000)

Another thing that might help a bit would be trying to increase the heartbeat timeout, e.g. to 10s:
https://github.com/itchysats/itchysats/blob/master/daemon/src/lib.rs#L51

**Comment by klochowicz** [comment]
@bonomat does the same happen with the UI embedded in the daemon, the one on port 8000?

**Comment by bonomat** [comment]
> @bonomat does the same happen with the UI embedded in the daemon, the one on port 8000?

 yea, doesn't seem to happen with the embedded UI. Closing this and will reopen if I see it happening.
