### ISSUE TITLE
Fee estimation for tx_lock

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#677]
Right now the fees are hard-coded at 1 sat/vbyte which could become a problem as transactions might be pending for too long. Some of our states depend on the tx_lock being included so we should try to ensure that this will happen in a realistic timeframe 

#491 will take a more sophisticated approach. 

We should estimate the fees (e.g. using the wallet) at time of contract creation for a target block. I propose to hardcode the target block at 2 for the start and we can think about making this configurable later on.

**Comment by bonomat** [comment]
I underestimated the size of this ticket: it turns out that changing the fee for the commit transaction involves various changes in the library as well as in our protocol.

- the fee of tx_commit depends on this constant (https://github.com/comit-network/maia/blob/6d18a152f4f1c1d306677d39f32ddcdc3d44421c/src/protocol/transactions.rs#L96)
- we would need to pass into `create_cfd_transactions` a new parameter for the fee with which the constant above is multiplied (https://github.com/comit-network/maia/blob/6d18a152f4f1c1d306677d39f32ddcdc3d44421c/src/protocol.rs#L83)
- this fee needs to be communicated between both parties, so it needs to be part of a Msg

Initially I thought that it would be a much smaller change, e.g. that we had this fee already in place and all we would need to change is how we would come up with this fee (e.g. by estimating it according the current network situation). 
That's unfortunately not the case. 

Since this was just a temporary solution for https://github.com/itchysats/itchysats/issues/491 I'm not sure if we should go for this anymore but rather focus on https://github.com/itchysats/itchysats/issues/491 instead. 
Also, https://github.com/itchysats/itchysats/issues/491 will make this solution redundant. 

What do you think @thomaseizinger

**Comment by bonomat** [comment]
CC @da-kami / @thomaseizinger / @itchymax / @scratchscratchscratchy : I've updated the ticket description. I think we should prioritize this and #491 afterwards.

**Comment by thomaseizinger** [comment]
> We should estimate the fees (e.g. using the wallet) at time of contract creation for a target block. I propose to hardcode the target block at 3 for the start and we can think about making this configurable later on.

Sounds good to me!

To make this more transparent to the user, we could:

1. Let the maker estimate it and share it 50:50 with the taker
2. Include the expected fee in the order that is sent to the taker
