### ISSUE TITLE
Quantity input feels sluggish

### ISSUE THREAD

**Issue by 1010Tom** [itchysats/itchysats#688]
The quantity input feels sluggish, that's because every input is being sent to the server and then updates the UI. 

Imho best is to do an initial calculation of the margin in the frontend and then, after clicking Long/Short, send to the backend and show the actual calculated numbers in the confirmation dialog.

**Comment by 1010Tom** [comment]
cc @scratchscratchscratchy @da-kami @bonomat : what do you think?

**Comment by thomaseizinger** [comment]
> The quantity input feels sluggish, that's because every input is being sent to the server and then updates the UI.

An alternative solution here would be to:

1. Debounce the input events
2. Make sure it is asynchronous (i.e. the fetching is not blocking the UI)

**Comment by thomaseizinger** [comment]
Lol, we are also firing `calculateMargin` twice.

Once via `useEffect` and once in the `onChange` handler :man_facepalming: 

Before we move this calc into the frontend, we should first fix all of these issues and if it still doesn't help, we can think about alternative solution.
