### ISSUE TITLE
Non collaborative close

### ISSUE THREAD

**Issue by rishflab** [itchysats/itchysats#689]
The old taker ui and new ui 2 distinct buttons  for collab and non-collab close.
The new taker UI is hardwired for collab close.

We need to:
Call the non-collab close endpoint when the maker status is offline
Call the collab close endpoint when the maker status is online

Hints:

pass in maker status to `CfdWithAuxData` 
see ` fn available_actions()`;
UI can be informed by "cfd actions", that are currently set per Cfd
they are inside CfdWithAuxData
non-collab settlement is called "Commit"
collab settlement is called "Settle"
in the old UI (maker), we're using the available actions here: maker-frontend/src/components/cfdtables/CfdTable.tsx:182
the new UI, instead of adding multiple icons, should just switch between the "settle" and "commit" actions (always prefer settle)

**Comment by thomaseizinger** [comment]
I think this has been completed now.
