### ISSUE TITLE
Model `contract_setup` as an explicit state machine

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#698]
At the moment `contract_setup` is an _implicit_ state machine (i.e. it is an async function. Those get compiled into a state machine with every `await` being a transition point).

This turned out to be clunky because:

- any `?` aborts the entire function, making it impossible to access the "current state" (read: local variables)
- we need to pass channels in to send and receive messages
- constructing those channels is cumbersome on the call-site as well

What we should do instead is model an explicit state machine that can produce messages and transition upon received ones ie something like:

```rust
pub struct ContractSetup {
	state: State // private field to hide inner representation
}

impl ContractSetup {
	fn next_message(&self) -> Message;
	fn is_complete(&self) -> bool;
	fn recv_message(&mut self, msg: Message) -> Result<()>;
}

enum State {
	State0(...),
	State1(...),
	State2(...),
	...
}
```

The idea is that our newly introduced `CfdAggregate` can produce an instance of `ContractSetup` when calling `start_contract_setup`. The domain model _module_ would own the `ContractSetup` code and thus is the only one that can access the internals. The actors would only be the "drivers" that push the state machine forward by connection it with IO.

Once the `ContractSetup` state machine is complete (signaled by the `is_complete` function), it can be passed again to the `CfdAggregate` via `setup_contract(...)` (currently this just takes the `Result` of `fn setup_contract`). `CfdAggregate::setup_contract` is a _command_ in event-sourcing terms and will produce an event according to the final state of `ContractSetup` (could be completed, failed, rejected ...).

This will allow us to model all of this outside of actors in an [IO-free](https://sans-io.readthedocs.io/how-to-sans-io.html) way.

**Comment by rishflab** [comment]
I like this idea. There is going to be heaps of boilerplate but I think we can solve that using macros/generics.

Looked into integrating this with the actor system and event sourcing:

`Command` handlers can send/forward commands to appropriate actors or they can be processed internally by method call. If the method call returns an error, we should send ourselves an failure event. This event is processed by the handler and updates the event machine state. Anytime the state is updated we should get the commands and send the to ourselves.

```rust
// commands
struct Start;
struct SendMsg1;

pub enum Command {
    SendMsg1(SendMsg1),
}

// events
struct SentMsg1;
struct SendMsg1Failed;
struct ActorStarted;

pub enum Event {
    ActorStarted(ActorStarted),
    SentMsg1(SentMsg1),
    SendMsg1Failed(SendMsg1Failed),
}

pub struct MakerContractSetup {
    taker: xtra::Address<maker_inc_connections::Actor>,
    state: State,
}

#[xtra_productivity]
impl MakerContractSetup {
    async fn handle(&mut self, command: SendMsg1, ctx: &mut Context<Self>) -> xtra::Result {
        if Err(..) = self.taker.send(command).await? {
            ctx.address().send(SendMsg1Failed)
        } else {
            ctx.address().send(SentMsg1)
        }
    }

    // events
    async fn handle(&mut self, event: SendMsg1Failed, ctx: &mut Context<Self>) -> xtra::Result {
        self.state = self.state.update(Event::SendMsg1Failed(event));
    }

    async fn handle(&mut self, event: SentMsg1, _ctx: &mut Context<Self>) -> xtra::Result {
        self.state = self.state.update(Event::SentMsg1(event));
    }

    async fn handle(&mut self, event: ActorStarted, ctx: &mut Context<Self>) -> xtra::Result {
        self.state = self.state.update(Event::ActorStarted(event));
        for cmd in self.state.command() {
            ctx.address().send(cmd)
        }
    }
}

enum State {
    s1,
    s2,
    s3,
}

/// we can use a state machine macro library to reduce boilerplate
/// eg. https://github.com/rustic-games/sm
impl State {
    pub fn update(&self, event: Event) -> State {
        match (&self, event) {
            (State::s1, Event::SentMsg1(_)) => State::s2,
            (State::s2, Event::SendMsg1Failed(_)) => State::s3,
            _ => {}
        }
    }

    pub fn command(&self) -> Vec<T> {
        match self {
            State::s1 => vec![SendMsg1],
            State::s2 => {}
            State::s3 => {}
        }
    }
}
```

**Comment by rishflab** [comment]
We can also build larger protocols by composing smaller protocols:

```rust

/// Parent state machine

// commands
struct Rollover;
struct ContractSetup;

// events
struct RollOverComplete;
struct RollOverFailed;
struct SetupContractComplete;
struct SetupContractFailed;

pub struct MakerCfd {
    state: MakerCfdState,
}

/// the whole cfd protocol composed of multiple smaller protocols
/// I am not sure how rehydration of this state from events will work
pub enum MakerCfdState {
    Started,
    ContractSetup(MakerContractSetup),
    Rollover(MakerRollover),
}

impl xtra::Actor for MakerContractSetup {}

```

**Comment by thomaseizinger** [comment]
Thanks @rishflab !

Couple of questions regarding the proposed design:

- Why does this design need to interact with our actor model? Can we design the state machine in a way that it _doesn't_ know about events / commands and instead, an actor is just a "driver" of the state machine?
- I would like the state machine to be the source of truth for how to progress, i.e. The actor should actively _ask_ the state machine, what the next step is. See the outlined API at the top with `next_message`.

**Comment by rishflab** [comment]
>     * Why does this design need to interact with our actor model? Can we design the state machine in a way that it _doesn't_ know about events / commands and instead, an actor is just a "driver" of the state machine?

It doesn't have to but if we make an actor also a state machine we can greatly reduce the amount of boilerplate.
We can directly map `events -> state_machine_inputs` and  `commands -> state_machine_outputs`.  

I think we have different ideas on what an actor can be. 
I think a domain object (eg. a cfd or order) can be an actor which should be a state machine. eg. a contract setup actor is a state machine which is a part of a hierarchical  cfd state machine which is also an actor. 
I think you think that actors should be things which manage multiple domain objects which have state machines. eg. a rollover actor drives multiple rollover state machines.

>     * I would like the state machine to be the source of truth for how to progress, i.e. The actor should actively _ask_ the state machine, what the next step is. See the outlined API at the top with `next_message`.

Agree with this. I am doing this but the method is `command` instead of `next_message`

**Comment by thomaseizinger** [comment]
> I think a domain object (eg. a cfd or order) can be an actor which should be a state machine. eg. a contract setup actor is a state machine which is a part of a hierarchical cfd state machine which is also an actor.
I think you think that actors should be things which manage multiple domain objects which have state machines. eg. a rollover actor drives multiple rollover state machines.

Part of the recent efforts of introducing dedicated actors for the protocols was to _not_ have a 1-to-N mapping between actor and domain object because it is cumbersome to code.

I would like to keep the domain model as pure and free from any particular programming paradigm (like actors) as possible. If we implement the entire contract-setup protocol as a state machine, it should be possible to test and run this in isolation without the need of actors. Yet, building an actor that acts as "glue" between other components like IO and the database should be easy and fairly thin.

Something like:

```rust
#[xtra_productivity]
impl Actor {
    async fn handle(&mut self, message: Message, ctx: &mut Context<Self>) -> xtra::Result {
      	let next = self.state.recv_message(message);

		match next {
			Some(message) => // send message
			None => self.complete() // `None` means we are done, apply state machine to Cfd and let domain model figure out what the result means
		}
    }
}
```

We will have to deal with the fact that sending a message might not work, plus there should probably be a timeout across the entire execution that triggers eventually:

```rust
#[xtra_productivity]
impl Actor {
    async fn handle(&mut self, timeout: Timeout ctx: &mut Context<Self>) -> xtra::Result {
      	let next = self.state.timeout(timeout);

		match next {
			Some(message) => // send message
			None => self.complete() // `None` means we are done, apply state machine to Cfd and let domain model figure out what the result means
		}
    }
}
```

What I think will be important is that we keep the _decision_ on what happens next within the state machine (depicted as `self.state` here). As such, we always need to "ask" what do do next as we apply a state change.

I think we are getting somewhere here. To summarize, the requirements we need to deal with are:

- Actor should ask state machine for next action and execute it
- Actor must "notice" timeout and inform state machine about it
- State machine should(?) tell actor what the timeout for the next message is (like: "tell me if you don't receive a message within the next 30 seconds")
- This timeout message might be the only one where the actor actually needs to send a message to itself

What you have modeled above already goes into this direction. However, I am yet to see the benefit of the actual contract-setup-state-machine being an actor. If the relationship is 1-to-1 between what is currently the `setup_taker::Actor` and the state machine, then they can just make function calls, no need to send messages.

**Comment by da-kami** [comment]
@luckysori do you think we will ever do this? Probably can be closed :)
