### ISSUE TITLE
The quantity in the UI has to be rounded to 100 precision

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#729]
You cannot go more precise than 100-steps on BitMEX. To allow a proper hedging calculation we should apply the same on the taker UI.

**Comment by rishflab** [comment]
I don't fully understand this ticket:

From bitmex we get a USD/BTC price with 2 decimal place precision eg. 58921.23

If we allow the taker to select a quantity with higher precision eg. 1000.29182 USD
