### ISSUE TITLE
Stale price on maker

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#756]
The offer price is stale. The UI-integrated Bitmex price is updated correctly, but the long price (on the button) remains stale.

On what condition is a new order created @bonomat ?
I even witnessed once that the price for the long position was lower than the reported Bitmex price... (unfortunately don't have a screenshot)

Are we updating the orders correctly or is this a UI problem? @itchymax

**Comment by bonomat** [comment]
What do you mean with stale? Could you take the offer? Then it was not stale :D 

Best is if you add screenshots and logs. Otherwise it is hard to see what happened. 

The maker is updating his offer whenever a new rate comes in and/or when an order was taken. 
It can however be that the ask/bid price are different to the index price

**Comment by da-kami** [comment]
After opening multiple CFD positions over time I think the problem is the maker - I was able to open CFDs, but the price of the new order never changed, even though the index price had moved.

The long price has been the same since I created the ticket. `58,229.04` - it did not move once in the last hour. That *can* be, but it is unlikely. The index price moved quite a lot. I saw prices between `57,800` and `58,100`. Again, it's possible that the bid/ask just does not move like the index. But it's a bit weird. 

Here is a current screenshot, I'll see to keep it running and add more information:

![image](https://user-images.githubusercontent.com/5557790/143961349-6f991caf-74d9-49c4-a2c9-62ea02c5b19e.png)

**Comment by bonomat** [comment]
as a reference you could open bitmex and check the ask/bids there

**Comment by bonomat** [comment]
It looks like the maker does not receive new rates through the `quote` endpoint. That's why the automation does not update the rate but uses the last available one.

**Comment by thomaseizinger** [comment]
Closing in favor of https://github.com/itchysats/itchysats/issues/758. Very likely the same bug.
