### ISSUE TITLE
Price updates from BitMEX failing

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#758]
We keep seeing this error in the logs:

```
2021-11-30 00:24:15  WARN Error on websocket stream: WebSocket protocol error: Connection reset without closing handshake
2021-11-30 00:24:15  WARN Failed to read quote from websocket
```

Make sure we don't fail reading from the stream if e.g. we can't process a `Quote`

**Comment by da-kami** [comment]
I think this might be related to #756 
I also don't see payout / P/L changes on the taker, so I think the price within the daemons (on both sides) is just stale because we fail to fetch it from BitMEX.

**Comment by da-kami** [comment]
Note that this is a serious problem, because a lot of logic / features depend on up to date price information. E.g. collaborative settlement would run into trouble without an up to date price.

**Comment by thomaseizinger** [comment]
I've also seen these warnings several times. A restart should - for now - fix the issue.

**Comment by da-kami** [comment]
> I've also seen these warnings several times. A restart should - for now - fix the issue.

At times we keep running into this issue again and again. At the moment (at least on my machine) I see this error on every run. Restart does not help, because it just happens again (at the moment after about 2 minutes after startup). Also, on Umbrel there is no simple restarting the container.

I think we have to report price errors back to the UI, so the user can react!

If this problem is related to rate-limits we have to re-think what can be done. The taker container on umbrel will just run - there is no easy stopping of an app. 

I think we need to things to tackle the problem of "outdated price":

1. Avoid running into the problem in the first place
2. If we still run into the problem report it back to the UI so the user at least knows. 

I don't think we have to disable collaborative close in such a scenario. But the user should know that the price is outdated. Anything else is very confusing, because the UI price feed comes from BitMEX directly and the price might heavily diverge.

**Comment by da-kami** [comment]
After having a look in the code: I think we just need to re-connect to the websocket in case we run into an error. - Updating the description.
