### ISSUE TITLE
Check electrum network against argument

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#816]
We should check the connected electrum being the same network as the application. Otherwise weird things might happen (transactions will never be found). 

Note: maybe bdk does that already?

**Comment by luckysori** [comment]
Has this been fixed or verified?

**Comment by Restioson** [comment]
I'm checking now if this is still an issue but am running into a few (maybe related?) issues.

**Comment by Restioson** [comment]
It looks like this silently fails and will show the wallet having a balance of 0 as well as there being no maker offers, so this issue is not fixed.
