### ISSUE TITLE
Sometimes old positions are not shown in UI initially 

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#834]
I am not sure what causes this, but since it happened several times I thought I report it. If somebody else had the problem please let me know. 

What happens: 

1. Start daemon
2. Open UI
3. No (open) positions are shown
4. Open a new position
5. Suddenly there are two positions, because there was an existing Open position that is only displayed now.

**Comment by da-kami** [comment]
Probably related to not consistently sending over CFDs upon startup. Check the code for loading and sending CFDs over the feed initially.

**Comment by thomaseizinger** [comment]
Likely fixed, if not please reopen.
