### ISSUE TITLE
Tile layout make-over 

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#872]
Next **funding rate** information
* Timestamp when it will occur
* Costs

Historical:
* When was the CFD opened?
* When was the last funding round and at what cost?

As part of this we want a makeover of the tile. Please ping once picking up this ticket.

**Comment by bonomat** [comment]
I thought I'd post some of the mock-ups we have: 

![image](https://user-images.githubusercontent.com/224613/145757822-7831e181-d977-4715-95c3-f6d2971f965c.png)

![image](https://user-images.githubusercontent.com/224613/145757853-a68a5b3a-3198-43dc-b5b2-785812407e4c.png)

![image](https://user-images.githubusercontent.com/224613/145757874-df27d1ba-c092-45b4-9512-041466b10b08.png)

![image](https://user-images.githubusercontent.com/224613/145757887-f7219ad1-3cf4-48be-b3da-76a109058214.png)

**Comment by thomaseizinger** [comment]
I really want to see the **dollar** value of margin, P/L and payout in UI. The first thing after opening a CFD I did today was opening a converter and calculating the initial P/L in dollars.

**Comment by bonomat** [comment]
> I really want to see the **dollar** value of margin, P/L and payout in UI. The first thing after opening a CFD I did today was opening a converter and calculating the initial P/L in dollars.

I see how this is confusing but you need to change the way how you think about this financial instrument. Since your collateral is Bitcoin profit and losses are measured in Bitcoin and not in Dollars. 

I think P/L in Dollar terms is confusing. Think of this: 

- Assume you have 0.1 BTC as margin at $50k/BTC. 
- Price increases by 10% to $55k You still have 0.1BTC in 

You now have 
- 0.1 BTC in margin = $5.5k
- you made 0.01BTC in unrealized P/
--> what's your P/L? $550? What about the $0.5k you earned by just holding your maring? So $6.05k (5.5k+550)? 

now, BTC drops to $45k/BTC

- 0.1 BTC in margin = $4.5k
- additionally you made a loss of 0.01BTC 
--> what's your P/L? -$450? $4.05k (4.5k-450)? 
--> how would you represent this number in %?

**Comment by thomaseizinger** [comment]
> I see how this is confusing but you need to change the way how you think about this financial instrument. Since your collateral is Bitcoin profit and losses are measured in Bitcoin and not in Dollars.

I understand all of that. But my issue is that when I went long, I had a dollar price displayed (quantity is in dollars). So I am thinking: I put 100$ in, then I also want to see my P/L and payout in dollars.

We'd obviously have to settle on how to exactly calculate that based on what you wrote above but the fact I am investing in one currency and only see my gains in another is confusing to me.

**Comment by klochowicz** [comment]
as a user I would love to see an estimate of payout dollars. Doing a google search for an estimated payout every time I wonder how much I gained/lost from my invested quantity is too cumbersome 😭

**Comment by da-kami** [comment]
Here is my "list of things" I consider "missing" for CFD positions in the UI atm:

- [ ] opening datetime of a CFD 
- [ ] last rollover datetime (I think this has to be independent of the opening datetime to be able to do a proper calc)
- [ ] closing price (once closed)
- [ ] event that will close the CFD (should be updated with every rollover)
  - [ ] relative time until the event
  - [ ] event id (--> it has to be verifyable! - best would be link to Olivia explorer so one can also look it up in case needed) 

I don't think all of these have to be immediately visible, some could be hidden. But we have to be able to access this information.
Open for discussion :)

**Comment by thomaseizinger** [comment]
I assume all of your "datetime" values are possibly relative. For example, I'd like to see: "opened 7 days ago" and not "opened on 14/12/2021". Rollover as such is tricky to display. I think that one should probably be expressed in terms of the funding rate, i.e. "next funding period in 3h" and next to it, it should show you how much you will get charged!

I am less convinced about the event ID, I think that is almost a technical detail that should be hidden behind some "advanced" switch in the UI, or debugging info. Element has a "view-source" action per message for example:

![image](https://user-images.githubusercontent.com/5486389/146926514-8f0e6559-3378-4ef0-87d0-e5b1c62f9156.png)

**Comment by bonomat** [comment]
Can you explain why the date is relevant? 
For me the date is irrelevant and all I need to see is: 

- opening price
- current P/L 
- accrued interest (funding rate) (might be better if included in the current P/L )
- next funding rate (e.g. per hour/ per day)

**Comment by thomaseizinger** [comment]
As long as we have a notion of displaying multiple positions (and not adding them together), the opening date is how you mentally differentiate them.

"The one I opened yesterday". "My position from last week is doing well."

If we wouldn't be technically constrained, all the contracts should be added together I guess? We could display them as one and simply limit that you can only sell your position in the same quantities as you bought them because we obviously have different DLCs on chain.

**Comment by thomaseizinger** [comment]
I didn't realize it until now but we do we even have tiles or mutliple entries at all?

We can only have one position right? Shouldn't that one change in quantity and what we are currently displaying is actually the order history?

**Comment by da-kami** [comment]
> I didn't realize it until now but we do we even have tiles or mutliple entries at all?
> 
> We can only have one position right? Shouldn't that one change in quantity and what we are currently displaying is actually the order history?

We do have multiple positions and tiles. Each CFD is it's own setup. I don't think you can accumulate it into one position. We could try, but that would make difference price (...) even more confusing.

**Comment by da-kami** [comment]
> Can you explain why the date is relevant? [snip]

In addition to what @thomaseizinger said (i.e. the association of the CFD with time, "the CFD I opened yesterday") this is also needed for:

1. Verifyability: I want to be able to check that the price displayed as opening price is actually the price that *was* the opening price at the time.
2. The association of "how long has this already been going", i.e. how old is my position. Of course you can also calculate that from e.g. what was the initial margin and how much of that did I already pay in interest (...), but the date helps me with not needing to do that.

**Comment by thomaseizinger** [comment]
> We do have multiple positions and tiles. Each CFD is it's own setup. I don't think you can accumulate it into one position. We could try, but that would make difference price (...) even more confusing.

I think from a financial point of view, positions are per trading pair and you sum up the quantity. The different opening prices only affects your unrealized P/L. Isn't that what BitMex does?

**Comment by da-kami** [comment]
> I assume all of your "datetime" values are possibly relative. For example, I'd like to see: "opened 7 days ago" and not "opened on 14/12/2021". Rollover as such is tricky to display. I think that one should probably be expressed in terms of the funding rate, i.e. "next funding period in 3h" and next to it, it should show you how much you will get charged!

I think the time until potential expiry (until oracle event) should be relative. 
When it comes to the opening time I would probably say: Both the timestamp and the relative time (maybe display the relative time but have e.g. a tooltip with the timestamp). This is for verifyability again. I want to be able to verify that the displayed opening price is sane. I think it would be great to be able to do that. 
Note: We might not need this immediately, but I think we should thrive for being more transparent than what's currently out there. 


> I am less convinced about the event ID, I think that is almost a technical detail that should be hidden behind some "advanced" switch in the UI, or debugging info. Element has a "view-source" action per message for example:

Totally fine with "hiding" is in advanced information, but I think we have to at least plan for displaying this. This is vital information for verifyability!

**Comment by klochowicz** [comment]
For my use-case, having absolute times even for the expiry/next oracle event is crucial. I put a event/reminder for exact time it would expire - one can set-up a tooltip or something to show the relative time when hovered over, but the absolute time IMHO is most useful.

**Comment by da-kami** [comment]
> > We do have multiple positions and tiles. Each CFD is it's own setup. I don't think you can accumulate it into one position. We could try, but that would make difference price (...) even more confusing.
> 
> I think from a financial point of view, positions are per trading pair and you sum up the quantity. The different opening prices only affects your unrealized P/L. Isn't that what BitMex does?

How would that work given all the different parameters (quantity, leverage, price -> liquidation price)?
I think it might be possible, but I am not sure to thrive for it (yet). I think it will make the user interface more complicated to understand. 

Consider: How would you be able to "close" part of this complete position then? I don't want to be forced to close all of my positions at once...
We could potentially group the positions into one big long/short. But again, not sure that actually makes things easier (to understand).
