### ISSUE TITLE
Api tests

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#890]
We should add tests for our Http Api to ensure no breaking changes. 

#888 found that a `serde_derive` has been accidentally removed. These random breaks are bad because if not caught early enough they could break the automation. In this case, the automation was not able to serialize the timestamp anymore and hence autoclosing positions was broken. 

We should add tests for our Http Api which alert if something was changed.

**Comment by thomaseizinger** [comment]
Best solved via snapshots tests of all models. Needing to fix those should be alerting enough.

**Comment by klochowicz** [comment]
our testnet setup with auto-taker should be already capable of spotting API breakages. If anything, we can extend the testing surface if we ever encounter any issues.

(alternatively, Rocket is capable of testing HTTP API too).

Should we close the issue or do you guys feel we should still have snapshot tests?

**Comment by thomaseizinger** [comment]
> Should we close the issue or do you guys feel we should still have snapshot tests?

More tests for the serialization of the API models wouldn't hurt but I think it is overall pretty low risk!

**Comment by luckysori** [comment]
Agree with final conclusion.
