### ISSUE TITLE
Secure sensitive data with password

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#897]
Currently, we are storing the seedfile unencrypted on disk. The seedfile is used to derive the internal wallet's descriptor. With https://github.com/itchysats/itchysats/issues/865, that will change to a passphrase but we will have to store that on disk as well.

We should introduce a password-derived encryption scheme that we can use to encrypt this information on disk.

Challenges:

- Delay p2p network communication until unlocked (cannot derive identity key until we have the seed)
- Delay wallet initialization until unlocked (cannot derive descriptor until we have the seed)

Related issues: https://github.com/itchysats/itchysats/discussions/753, https://github.com/itchysats/itchysats/issues/865
Relation section in vision document: https://github.com/itchysats/itchysats/blob/master/docs/VISION.md#always-available-ui

**Comment by klochowicz** [comment]
I believe this should be addressed along with  #2967 .
For the full node perspectives, we could assume that they are isolated network nodes and there's some degree of protection there. For Electron, the data sits in `Application Support` folder and could be accessed easier.

**Comment by bonomat** [comment]
Does this make sense for users who run with `--password` (e.g. Raspiblitz, Cloud9, etc)? The problem is that you could start with a different password and then we won't be able to open `taker_seed` anymore. 

Which means, on platforms where we don't have control over how the password is generated we couldn't make use of this.

**Comment by klochowicz** [comment]
it will be tricky, but if we want to support  #1065 on any of these platforms, we should figure out something, because an unencrypted `taker_seed` would get saved to the Downloads folder...

**Comment by bonomat** [comment]
This project is unmaintained
