### ISSUE TITLE
Use `xtra-productivity` everywhere

### ISSUE THREAD

**Issue by luckysori** [itchysats/itchysats#905]
We still manually implement `xtra::Actor` and `xtra::Message` in a lot of situations.

Since we introduced `xtra-productivity`, we can reduce a lot of this boilerplate.

_Originally posted by @thomaseizinger in https://github.com/itchysats/itchysats/pull/861#discussion_r769181920_

**Comment by luckysori** [comment]
On a related note, I would try to follow the principal of only ever using a message type for _one_ layer. That is between two different actors or even messages that an actor sends to themself (perhaps via a spawned task).

That way we can always modify what the message has and does without breaking other layers, and we don't need to use the `message_impl = false` attribute, which I find awkward.

**Comment by thomaseizinger** [comment]
> That way we can always modify what the message has and does without breaking other layers, and we don't need to use the `message_impl = false` attribute, which I find awkward.

Yes that has primarily been introduced for our tests (where the mocks need to implement the same interface). It wasn't much intended to be used in production.

**Comment by luckysori** [comment]
> > That way we can always modify what the message has and does without breaking other layers, and we don't need to use the `message_impl = false` attribute, which I find awkward.
> 
> Yes that has primarily been introduced for our tests (where the mocks need to implement the same interface). It wasn't much intended to be used in production.

That's good to know! It wasn't obvious to me, but it definitely felt weird to use.

**Comment by thomaseizinger** [comment]
Adding this one to the milestone as it is a nice one to do async over the holidays.

**Comment by luckysori** [comment]
Grepping the codebase reveals that we only have one manual impl for `xtra::Handler` in a test, which is intentional.
