### ISSUE TITLE
Permit publication of punish transaction if counterparty publishes revoked commit transaction

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#907]
Now that we are confident that our rollover protocol is stable[1], we are ready to introduce the feature of punishing the counterparty if they publish a revoked (old) commit transaction. This is already supported by `maia`, so it's just a matter of adding some logic to `itchysats`.

The reason why we were hesitant to introduce this (very important) functionality was because we did not want to run into situations where the punished party didn't "mean" to publish the revoked commit transaction. The punishing party has no way of knowing what the intentions of their counterparty are, nor do they have a practical alternative to punishing a revoked commit transaction published by their counterparty. From this I conclude that **publishing a punish transaction should be handled automatically by both parties**.

In order to reduce the number of punishments, we can ensure that a party that knows that they are behind in the state of the CFD compared to their counterparty does not nonchalantly publish a commit transaction that would inevitably see them getting punished. Only takers can fall behind in rollovers according to our rollover protocol[2], so I propose to **prevent takers from force-closing[3] a CFD through the UI if their CFD is lagging behind**. This is not a perfect solution because:

- We would have to explain what's going on with a tooltip, making the UI more complex.
- The maker could theoretically hold the taker hostage. This would be fixed with https://github.com/itchysats/itchysats/issues/3019.

The taker could still be able to manually trigger such a transaction if they hit a particular endpoint. At that stage it would be on them to face the likely consequences (loss of funds).

How would a taker know that they are behind in the state of the CFD? We should model it explicitly. This is equivalent to what is outlined in https://github.com/itchysats/itchysats/issues/3019, so it would make sense to tackle that issue first before we proceed with this one.

[1]: We rarely run into a situation where one party falls behind in the state of the CFD because of a partially failed rollover. And when we do, we are able to recover by letting parties roll over from a specific commit TXID.
[2]: The maker always finishes first, so it's only the taker that can fail to receive the last bit of information that would allow them to finish the rollover protocol.
[3]: Force-closing is only available via the UI if the taker is not connected to the maker.

**Comment by thomaseizinger** [comment]
Descoped because it is not too critical right now. Would require forking the software.

**Comment by thomaseizinger** [comment]
We now have a real-world case where this feature would be needed: https://github.com/itchysats/itchysats/issues/1617

**Comment by bonomat** [comment]
This project is unmaintained
