### ISSUE TITLE
No new quote from bitmex

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#925]
When trying to debug #759 I realized that the quote is not updating. 

The maker was started at `18:54`, last offer has timestamp `1639907340` (in seconds) or `20:49`. 

```
data:{"bid":"47137","ask":"47137.5","last_updated_at":1639907340}
```

Note: the maker still produces offers with the outdated quote!

Note2: This only happened locally, both, mainnet and testnet maker have up2date quotes.

**Comment by thomaseizinger** [comment]
Are you saying that after `20:49`, there wasn't any new quote?

It is quite hard to make an automated decision of what "outdated" means. Should we extend the new-offer endpoint with a parameter where you can configure the max age of the quote? Should we remove the quote entirely from the maker and have it be controlled completely externally?

**Comment by bonomat** [comment]
> Are you saying that after 20:49, there wasn't any new quote?

Yes. Unfortunately I don't have any logs for this run :/ 

> Should we remove the quote entirely from the maker and have it be controlled completely externally?

I was thinking of exactly this. 
We could change the current subscription to get the BTCUSD index price which we should use for P/L computation. 
The bid/ask quotes is something an application on top can take care of.

**Comment by thomaseizinger** [comment]
> We could change the current subscription to get the BTCUSD index price which we should use for P/L computation.
> The bid/ask quotes is something an application on top can take care of.

Does it really make sense to do P/L inside the application but quotes outside?

I was thinking of removing the socket to bitmex entirely (for the maker binary). Wouldn't you want to calculate P/L against the counter-offer?

**Comment by bonomat** [comment]
> Does it really make sense to do P/L inside the application but quotes outside?

I thought we wanted to have all the price information inside the application. Subscribing to the bitmex pricefeed through the UI was just a quick solution. 
I'd be fine eitherway. 

For the maker, I agree, it would make sense to keep all of it outside. 

> Wouldn't you want to calculate P/L against the counter-offer?

I would calculate the _unrealized_ P/L using the BTCUSD index pricefeed. The _realized_ P/L is then the actual P/L we get when closing our position.

**Comment by thomaseizinger** [comment]
> For the maker, I agree, it would make sense to keep all of it outside.

Okay, that is what I was talking about :)
Wouldn't change anything for the taker for now.

Switching to index price for unrealized P/L is a different issue IMO.

**Comment by thomaseizinger** [comment]
Closed in favor of https://github.com/itchysats/itchysats/issues/946.
