### ISSUE TITLE
Tile layout make-over 

### ISSUE THREAD

**Issue by bonomat** [itchysats/itchysats#943]
Next **funding rate** information
* Timestamp when it will occur
* Costs

Historical:
* When was the CFD opened?
* When was the last funding round and at what cost?

relevant discussion #942

**Comment by da-kami** [comment]
Closing this in favor of #244 
UI changes will be done together with finishing the funding rate implementation.

The only change listed in this ticket that is not related to the funding rate is 

> When was the CFD opened?

which might not be necessary as discussed in #942 

We might still incorporate it into the changes if deemed necessary.
