### ISSUE TITLE
Use async-native esplora backend

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#947]
At the moment, we are using the https://github.com/bitcoindevkit/rust-electrum-client as the backend for BDK.

BDK also has a `reqwest`-based esplora backend: https://github.com/bitcoindevkit/bdk/blob/master/src/blockchain/esplora/reqwest.rs

We already depend on `reqwest`, meaning doing this would cut down our dependency tree and compile times. Additionally, this one is using `async` and thus provides a better integration with our codebase. the `electrum-client` is using its own background thread IIRC.

Open problems:

- We are using the same client for monitoring and the implementation of `EsploraBlockchain` is completely hidden behind a trait. Thus we cannot access the necessary functionality that we need for monitoring.

**Comment by thomaseizinger** [comment]
Reasons why this is tech-debt:

- The electrum client we are currently using is blocking which can cause all sorts of weirdness in an async system.
- Swapping to BDK's esplora client is non-trivial because their futures don't implement Sync https://github.com/bitcoindevkit/bdk/issues/165

**Comment by bonomat** [comment]
This project is unmaintained
