### ISSUE TITLE
Re-add re-broadcasting of transactions upon startup

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#953]
https://github.com/itchysats/itchysats/pull/665 temporarily removed re-broadcasting from housekeeping due to the changes in the model.

Broadcasting is currently handled by `wallet::Actor` which doesn't actually align very well with the responsibilities of a wallet (tracking coins and keys to sign transactions).

We want to move this functionality to `monitor::Actor` which already has the responsibility of connecting to the blockchain interacting with it. `monitor::Actor` also already has a startup procedure in which it re-hydrates an aggregate from all CFD events to figure out, what needs to be done. Re-broadcasting transactions can nicely be added there IF broadcasting itself is made a responsibility of `monitor::Actor`.

Solve this issue in two steps:

1. Move `TryBroadcastTransaction` from `wallet::Actor` to `monitor::Actor`
2. Implement re-broadcasting of transactions as part of `monitor::Actor`'s startup procedure

**Comment by luckysori** [comment]
@thomaseizinger: What is the plan for the wallet balance? If it currently lives in the `wallet::Actor` but we're moving broadcasting to the "monitor" actor because it interacts with the blockchain, shouldn't we do the same with the balance? 

Furthermore, if the `wallet::Actor` ends up only doing signing, does it still need to be an actor?

**Comment by thomaseizinger** [comment]
> @thomaseizinger: What is the plan for the wallet balance? If it currently lives in the `wallet::Actor` but we're moving broadcasting to the "monitor" actor because it interacts with the blockchain, shouldn't we do the same with the balance?

Uhm, I think I would draw the line as follows:

- A wallet is about tracking ownership of keys and as a result coins, deriving said keys & addresses.
- Hiding this ownership behind an abstraction (actor) is useful. It allows us to safely access it concurrently via message passing, plus makes the implementation swappable.
- The state of a wallet is secret and must be protected.

Computing the balance requires scanning the blockchain for keys / addresses. In theory, we could use an "offline" wallet from BDK and thus not have any IO in that actor. That would require us to re-implement quite a bit of BDK functionality so not sure if it is worth it.

The broadcasting of TX is literally just a pass-through function call and doesn't need any of the state that is needed for balance + signing. Considering how easy it is to move that one, I think it is worth moving.

Summary: I would keep the balance in `wallet::Actor` because:

- It is convenient to implement that way
- Scanning and reporting the balance is not actually part of the `wallet::Actor`'s **public** API and thus it is not as critical to violate the "what belongs where" consideration here[^1]

[^1]: Putting stuff where it belongs is primarily useful because it allows us to hide implementation details and define coherent modules. Anything that violates this AND shows up in the public API will cause a lot more friction than something that is private. The fact that our wallet scans for new coins in the background and reports this to the UI is completely hidden from the rest of the system. Changing this (and testing for changeability is a good test for encapsulation) would be trivial because almost nothing in the system relies on _where_ this happens only _that_ it happens.
