### ISSUE TITLE
Better handling of available `CfdActions`

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#955]
Currently, we are not asserting in the tests, which `CfdActions` are possible in the current state. The actions are what the UI and any other client depends so it is crucial that we assert these to avoid bugs in clients.

On that note, the `CfdActions` is currently unified across both binaries which leads to weird code like this:

https://github.com/itchysats/itchysats/blob/f5b135f9000cfaf3db3fabf55bc81445e3bec68f/daemon/src/routes_taker.rs#L126-L134

Instead of using an enum here, it would be better to create 1 dedicated route per action and use rocket's [`uri!`](https://docs.rs/rocket/0.5.0-rc.1/rocket/macro.uri.html) macro to return a type-safe URI for the dedicated route. That would allow us to create precisely control, which binary has which routes.

Additionally, it would decouple the client because the client would just `POST` against the given URL instead of hard-coding it.

**Comment by thomaseizinger** [comment]
An attempt in fixing this was made here: https://github.com/itchysats/itchysats/pull/1082

**Comment by bonomat** [comment]
This project is unmaintained
