### ISSUE TITLE
Introduce domain event for `ContractSetupStarted`

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#957]
(Read this assuming https://github.com/itchysats/itchysats/issues/956 is implemented).

Currently, the first event that we emit in a CFD is either `SetupFailed` / `OfferRejected` or `ContractSetupComplete`. This causes several problems:

1. The projection actor does not learn that the contract is actually already being setup, thus cannot give any feedback to the user.
2. On a technical level, it should be impossible to setup the same contract twice (i.e. start it again while the first one is running). The current model does not prevent this because we don't have any event that we can `apply` and could thus use for reasoning about it.

Both of these problems can be fixed if `Cfd#start_setup_contract` is turned into a _command_ and thus returns an `Event`.

**Comment by thomaseizinger** [comment]
This will fix a regression introduced by #665 where the CFD is in state `Setting up` and _still_ shows the two actions even though contract setup has already started:

![image](https://user-images.githubusercontent.com/5486389/147201533-e5b4a766-222e-410c-bcd2-e33713902827.png)

**Comment by klochowicz** [comment]
Resolved by #991
