### ISSUE TITLE
Price feed for taker and maker

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#96]
In order to be able to price the CFD as the maker we will need the current price feed. Given, that the maker might want to open counterpositions on Bitmex we should potentially use the Bitmex price feed.

This will enable: https://github.com/comit-network/hermes/issues/33

**Comment by thomaseizinger** [comment]
See also: https://github.com/comit-network/hermes/discussions/77

Bitmex price feed sounds good to me.

Oracle and daemons should likely have independent price feeds at runtime (i.e. don't get the feed from the oracle).
