### ISSUE TITLE
Investigate coins not found in development mode

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#965]
We sometimes run into the problem that we start with 0 balance when using our development seeds.
Perhaps #838 is related to this issue.

We should investigate, how bdk scans for coins (enable some logs?) and see how to resolve the issue. The original thinking was, because we use electrum as a backend, we should be able to re-scan from scratch on every startup and find ALL coins.

**Comment by thomaseizinger** [comment]
Adding this to the milestone because it is seriously annoying.

Ideas on how to debug this:

- Enable logs in BDK
- Go back to BDK's sqlite database so we have a set of UTXOs to start with on startup
- Try and use the esplora backend instead of the electrum backend in BDK for our wallet (we need to keep the electrum_client dependency for monitor, so don't get too confused by https://github.com/itchysats/itchysats/pull/815).

**Comment by da-kami** [comment]
+1 on seriously annoying. I keep running into this problem upon almost every local test run.
@thomaseizinger do you think that bringing back the SQlite database to cache wallet state would help? At the moment we still only use the in-memory wallet, but I remember we discussed bringing back the wallet db. We should probably #838 into the milestone if we want to tackle this.

**Comment by thomaseizinger** [comment]
So the bug reliably goes away if we scan more than 100 transactions which leads me to conclude that:

- this can also happen in production as soon as the user has been using the wallet for a while
- there seems to be a bug in BDK where repeated scans do not pick up balances discovered after the initial scan of 100 addresses

**Comment by thomaseizinger** [comment]
> Try and use the esplora backend instead of the electrum backend in BDK for our wallet (we need to keep the electrum_client dependency for monitor, so don't get too confused by

We can't do that unfortuntely because the esplora backend doesn't work with the `async-interface`: https://github.com/bitcoindevkit/bdk/issues/165.

I tried using `ureq` which is horribly slow because it is a blocking client but it doesn't fix the issue anyway.
