### ISSUE TITLE
Split `taker` binary into multiple

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#984]
https://github.com/itchysats/itchysats/issues/978 discusses an alternative way of providing a seed to the application. This conflicts architecturally with how the current binary works.

Instead of trying to find a solution that satisfies all usecases, we can simply split the binary into two and make a dedicated one that is used within the umbrel docker image.

This will simplify the situation a lot because we can just access the umbrel-specific env variables `APP_SEED` etc and don't have to design any abstractions around it or introduce concepts like commandline parameters that are otherwise not used.

**Comment by thomaseizinger** [comment]
For reference, the goal here is a to design the interface of our binaries around how they are being used. It will probably require some more thinking around what that means in each case.

For example, it is a legit usecase to use the docker image outside of umbrel. Should the user have to specify umbrel specific env variables for that? Probably not!

At the same time, it isn't particularly docker-native to rely on the filesystem much. Things like kubernetes for example rely on being able to spawn new instances of containers with the same arguments to result in the same behaviour. Not that we will be running within k8s soon but you get the idea. Docker and filesystem don't play that well together.

We don't have to solve all these concerns at once, the seed is certainly the most pressing. So whatever design we use, I think it is important for the binary that runs within docker requires the seed to be external and doesn't have the "auto-create on startup" functionality. Coupled with docker's default of ephemeral filesystems, the current container design is just waiting for someone to put money into it and not backing up the seed.

The next problem we will need to solve is externalising the database and stop relying on the FS here as well for the docker container.

Probably worth looking into how other apps in umbrel solve this.

**Comment by bonomat** [comment]
Oldie but goldie... not planned at the moment :)
